### ISSUE TITLE
OMNA-Registration of Load Control

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#11]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-10 23:22:31 UTC</td></tr><tr><td>Submitter's name</td><td>Joaquin Prado -Test</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Please ignore</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Load Control</td></tr><tr><td>Object Description</td><td>Test please ignore</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=3689a7c1-cd40-45c3-9643-f9ec862acefb_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/3689a7c1-cd40-45c3-9643-f9ec862acefb_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=3689a7c1-cd40-45c3-9643-f9ec862acefb_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Test.
