### ISSUE TITLE
OMNA-Registration of Firmware Update

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#125]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-04-24 06:29:33 UTC</td></tr><tr><td>Submitter's name</td><td>Baochen Sun</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Firmware Update</td></tr><tr><td>Object Description</td><td>test</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=e0022bb4-6de6-4ab8-9136-e05e6cd5f788_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/e0022bb4-6de6-4ab8-9136-e05e6cd5f788_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=e0022bb4-6de6-4ab8-9136-e05e6cd5f788_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Object a duplication of Object ID 05 *Firmware Update*
