### ISSUE TITLE
[South East Water] Gas Readings - 10313

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#140]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-04-29 06:27:33 UTC</td></tr><tr><td>Submitter's name</td><td>Andrew Forster-Knight</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>South East Water</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Gas Readings</td></tr><tr><td>Object Description</td><td>Object to periodically log readings from any gas sensor (eg H2S, VOCx, methane etc)</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=6665c2b1-193d-4411-a2c7-b6cfad9aa673_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/6665c2b1-193d-4411-a2c7-b6cfad9aa673_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=6665c2b1-193d-4411-a2c7-b6cfad9aa673_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

- [ ] The object ID allocation for this object will be reserved as 10313
- [ ] The object URN allocation for this object will be reserved as oma:lwm2m❌10313

A new branch South East Water has been created in the LwM2M registry for the WG to review your object

 - [ ] Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/SE-Water

**Observations to be addressed**
  - [ ] Object version updated to 1.0
  - [ ] LwM2M verision updated 1.0
  - [ ] Object ID updated to 10313
  - [ ] Object urn updated to urn:oma:lwm2m❌10313
  - [ ] The description in your submission is ```Object to periodically log readings from any gas sensor (eg H2S, VOCx, methane etc)``` but in the object the description is ```Periodic gas sensor measurements```

Steps | Actions
-- | --
1 | Submit object using the tool
2 | Staff evaluates Object. Comments added for the submitter to resolve
3 | Submitter submits a Pull Request to the nominated branch with your object
4 | Staff validates PR
5 | IPSO Working Group discuss the submitted Object registration
6 | Any issues will require the submitter to update the PR accordingly
7 | Staff validates object again after submitters updates
8 | IPSO Working Group Chair will merge the object
9 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by mojanm** [comment]
Inconsistency between reusable resource 6041 as used in this object and its registration. Here it is shown to be of type String while it's being registered to have type Integer.

**Comment by seanmcilroy29** [comment]
There's a note at the bottom of the object from the submitter
```new resource (nominally 6041) has yet to be added. This will be an integer value representing 0-86400 seconds for how long a sensor should wait/warm-up before a reading is taken```

I will inform the submitter to ensure the resource is added once it's agreed by the WG.

**Comment by seanmcilroy29** [comment]
See PR #149

**Comment by seanmcilroy29** [comment]
Resource Agreed See - #167 #243
