### ISSUE TITLE
[Vaisala] Reusable Resources Quality  - 6042

### ISSUE THREAD

**Issue by dirtyha** [OpenMobileAlliance/lwm2m-registry#151]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-05-13 11:37:13 UTC</td></tr><tr><td>Submitter's name</td><td>Harri Hytönen</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Vaisala</td></tr><tr><td>Type of registration</td><td>Reusable resources</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=99242bc4-791e-44a0-a21b-64c9aed466de_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/99242bc4-791e-44a0-a21b-64c9aed466de_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=99242bc4-791e-44a0-a21b-64c9aed466de_Object.xml">Load Editor with object</a></td></tr>

**Comment by dirtyha** [comment]
Typo in value range, should have been from -8999 to 8999

**Comment by seanmcilroy29** [comment]
See - PR #153 
RR PR incorporates dirtyha typo in Range Enumeration from -8500 - 8500 to -8999 to 8999

**Comment by dirtyha** [comment]
Due to interest on this specific quality value range, we decided to open it a little bit. Basically it is a Vaisala specific coding used by our existing products. If a measurement device has quality control algorithms, it may then report:

INVALID (-8500)  : Measurement value shall not be used
UNCHECKED (0) : Measurement value has not undergone any quality checks
SUSPICIOUS  (6500) : Measurement value contains uncertainty, for example statistic with low number of samples
ACCEPTED (8500) : Measurement value is good for use 

Other values in the range (-8999..8999) are reserved for quality levels that are done at later phases at server side. Generally speaking, the larger the value, the "better" the measurement is.

**Comment by seanmcilroy29** [comment]
@dirtyha - your comment has been submitted to PR #153 for Working Group members to review.
Can all future comments be submitted directly to this PR.

**Comment by seanmcilroy29** [comment]
Please note the comments submitted to PR #156 by the Working Group for your review.

**Comment by jpradocueva** [comment]
See PR #159  previous PRs are superseded

**Comment by seanmcilroy29** [comment]
#159 - Approved 9/19/19
