### ISSUE TITLE
[UNITS] Problems with Units in Common.xml file

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#156]
IPSO agreed to follow up SenML units notation.
In OMNA Reusable Resources table, the Common.xml file, contains some units that cannot be mapped directly to SenML units.

---

PR #155 updates the Units in the Common.xml that can be easily mapped to SenML units. 

IPSO WG needs to review the list of Reusable Resources  that cannot be mapped directly to SenML units, without creating potential problems on already registered Objects.

**Reusable Resources with problems in the "Units" element**:
- [x] 5503 is in "ms"
- [x] 5705 is in "degree"
- [x] 5805 is in "Wh"
- [x] 5815 is in "varh"
- [x] 5825 is in "min"
- [x] 5903 is in "ms"
- [x] 5904 is in "ms"

**Comment by jpradocueva** [comment]
First units validation implies around 197 errors as a result of using SenML notations:


Error | Time | Description | ObjectID and/or ResourceID
-- | -- | -- | --
Critical |   | Limited verification | No links to TS and Vorto links are verif
Critical |   |   | ied
551 |   | Incorrect Unit value (ms) | 5503
551 |   | Incorrect Unit value (degree) | 5705
551 |   | Incorrect Unit value (Wh) | 5805
551 |   | Incorrect Unit value (varh) | 5815
551 |   | Incorrect Unit value (min) | 5825
551 |   | Incorrect Unit value (ms) | 5903
551 |   | Incorrect Unit value (ms) | 5904
551 |   | Incorrect Unit value (Seconds) | 6000
551 |   | Incorrect Unit value (Seconds) | 6001
551 |   | Incorrect Unit value (Seconds) | 6019
551 |   | Incorrect Unit value (Seconds) | 6040
405 |   | Invalid XML Schema ref | 1
412 |   | Incorrect Type value | 1:11
412 |   | Incorrect Type value | 1:13
412 |   | Incorrect Type value | 1:14
412 |   | Incorrect Type value | 1:17
412 |   | Incorrect Type value | 1:18
412 |   | Incorrect Type value | 1:19
412 |   | Incorrect Type value | 1:20
417 |   | Incorrect Unit value (mV) | 3:7
417 |   | Incorrect Unit value (mA) | 3:8
417 |   | Incorrect Unit value (KB) | 3:10
417 |   | Incorrect Unit value (dBm) | 4:2
417 |   | Incorrect Unit value (dBm) | 4:2
417 |   | Incorrect Unit value (bytes) | 5:1
417 |   | Incorrect Unit value (bytes) | 5:6
417 |   | Incorrect Unit value (bytes) | 5:7
417 |   | Incorrect Unit value (Deg) | 6:0
417 |   | Incorrect Unit value (Deg) | 6:1
417 |   | Incorrect Unit value (Meters per seco... | 6:6
417 |   | Incorrect Unit value (Kilo-Bytes) | 7:2
417 |   | Incorrect Unit value (Kilo-Bytes) | 7:3
417 |   | Incorrect Unit value (Byte) | 7:4
417 |   | Incorrect Unit value (Byte) | 7:5
417 |   | Incorrect Unit value (Seconds) | 7:8
417 |   | Incorrect Unit value (minutes) | 10:1
405 |   | Invalid XML Schema ref | 21
417 |   | Incorrect Unit value (ms) | 2052:1
417 |   | Incorrect Unit value (ms) | 2052:2
417 |   | Incorrect Unit value (ms) | 2052:3
417 |   | Incorrect Unit value (ms) | 2052:4
417 |   | Incorrect Unit value (ms) | 2052:5
417 |   | Incorrect Unit value (ms) | 2053:6
417 |   | Incorrect Unit value (ms) | 2053:7
417 |   | Incorrect Unit value (ms) | 2053:8
417 |   | Incorrect Unit value (ms) | 2053:9
417 |   | Incorrect Unit value (ms) | 2055:1
417 |   | Incorrect Unit value (Byte) | 2055:2
417 |   | Incorrect Unit value (Byte) | 2056:1
417 |   | Incorrect Unit value (ms) | 2057:1
417 |   | Incorrect Unit value (ms) | 2057:2
417 |   | Incorrect Unit value (ms) | 2057:3
417 |   | Incorrect Unit value (ms) | 2057:4
417 |   | Incorrect Unit value (ms) | 3200:5503
417 |   | Incorrect Unit value (ms) | 3302:5903
417 |   | Incorrect Unit value (ms) | 3302:5904
417 |   | Incorrect Unit value (Wh) | 3305:5805
417 |   | Incorrect Unit value (varh) | 3305:5815
417 |   | Incorrect Unit value (min) | 3310:5825
417 |   | Incorrect Unit value (Wh) | 3311:5805
417 |   | Incorrect Unit value (Wh) | 3312:5805
417 |   | Incorrect Unit value (degree) | 3314:5705
417 |   | Incorrect Unit value (degree) | 3332:5705
417 |   | Incorrect Unit value (degree) | 3336:5705
202 |   | Description is different for same Obj... | 3380
462 |   | Type is different | 3380:6038
202 |   | Description is different for same Obj... | 3380
417 |   | Incorrect Unit value (Ws) | 3388:910
417 |   | Incorrect Unit value (ms) | 3388:505
417 |   | Incorrect Unit value (ms) | 3390:127
417 |   | Incorrect Unit value (ms) | 3390:128
417 |   | Incorrect Unit value (ms) | 3391:139
417 |   | Incorrect Unit value (ms) | 3391:140
417 |   | Incorrect Unit value (ms) | 3393:106
417 |   | Incorrect Unit value (ms) | 3393:108
417 |   | Incorrect Unit value (ms) | 3394:5903
417 |   | Incorrect Unit value (ms) | 3394:5904
417 |   | Incorrect Unit value (ms) | 3395:203
417 |   | Incorrect Unit value (ms) | 3395:204
417 |   | Incorrect Unit value (byte) | 3396:908
417 |   | Incorrect Unit value (ms) | 3396:102
417 |   | Incorrect Unit value (ms) | 3396:124
417 |   | Incorrect Unit value (Ws) | 3396:910
417 |   | Incorrect Unit value (h) | 3396:930
417 |   | Incorrect Unit value (ms) | 3397:102
417 |   | Incorrect Unit value (ms) | 3397:138
417 |   | Incorrect Unit value (Ws) | 3397:910
417 |   | Incorrect Unit value (h) | 3397:930
417 |   | Incorrect Unit value (ms) | 3399:102
417 |   | Incorrect Unit value (Ws) | 3399:910
417 |   | Incorrect Unit value (h) | 3399:930
417 |   | Incorrect Unit value (ms) | 3401:5503
417 |   | Incorrect Unit value (ms) | 3404:652
417 |   | Incorrect Unit value (kW) | 10242:6
417 |   | Incorrect Unit value (kvar) | 10242:7
417 |   | Incorrect Unit value (kvarL) | 10242:8
417 |   | Incorrect Unit value (kvarC) | 10242:9
417 |   | Incorrect Unit value (kVA) | 10242:10
417 |   | Incorrect Unit value (kW) | 10242:16
417 |   | Incorrect Unit value (kvar) | 10242:17
417 |   | Incorrect Unit value (kvarL) | 10242:18
417 |   | Incorrect Unit value (kvarC) | 10242:19
417 |   | Incorrect Unit value (kVA) | 10242:20
417 |   | Incorrect Unit value (kW) | 10242:26
417 |   | Incorrect Unit value (kvar) | 10242:27
417 |   | Incorrect Unit value (kvarL) | 10242:28
417 |   | Incorrect Unit value (kvarC) | 10242:29
417 |   | Incorrect Unit value (kVA) | 10242:30
417 |   | Incorrect Unit value (kW III) | 10242:34
417 |   | Incorrect Unit value (kvar III) | 10242:35
417 |   | Incorrect Unit value (kvarL III) | 10242:36
417 |   | Incorrect Unit value (kvarC III) | 10242:37
417 |   | Incorrect Unit value (kVA III) | 10242:38
417 |   | Incorrect Unit value (kW/h III) | 10242:41
417 |   | Incorrect Unit value (kvar/h III) | 10242:42
417 |   | Incorrect Unit value (kvarL/h III) | 10242:43
417 |   | Incorrect Unit value (kvarC/h III) | 10242:44
417 |   | Incorrect Unit value (kVA/h III) | 10242:45
417 |   | Incorrect Unit value (kW) | 10243:6
417 |   | Incorrect Unit value (kvar) | 10243:7
417 |   | Incorrect Unit value (kvarL) | 10243:8
417 |   | Incorrect Unit value (kvarC) | 10243:9
417 |   | Incorrect Unit value (kVA) | 10243:10
417 |   | Incorrect Unit value (kW/h) | 10243:14
417 |   | Incorrect Unit value (kvar/h) | 10243:15
417 |   | Incorrect Unit value (kVA/h) | 10243:16
417 |   | Incorrect Unit value (km/h) | 10244:1
417 |   | Incorrect Unit value (kW) | 10244:4
417 |   | Incorrect Unit value (Wh) | 10244:5
417 |   | Incorrect Unit value (Wh/km) | 10244:6
417 |   | Incorrect Unit value (km) | 10244:7
417 |   | Incorrect Unit value (minute) | 10244:12
417 |   | Incorrect Unit value (Ah) | 10244:15
417 |   | Incorrect Unit value (mV) | 10244:18
417 |   | Incorrect Unit value (mV) | 10244:19
417 |   | Incorrect Unit value (Celsius) | 10244:20
417 |   | Incorrect Unit value (Celsius) | 10244:21
417 |   | Incorrect Unit value (Celsius) | 10244:25
417 |   | Incorrect Unit value (rpm) | 10244:26
417 |   | Incorrect Unit value (Celsius) | 10244:27
417 |   | Incorrect Unit value (degrees) | 10245:2
417 |   | Incorrect Unit value (dBm) | 10245:11
417 |   | Incorrect Unit value (bytes) | 10249:6
417 |   | Incorrect Unit value (bytes) | 10249:7
417 |   | Incorrect Unit value (mA) | 10254:0
417 |   | Incorrect Unit value (Wh) | 10257:5805
417 |   | Incorrect Unit value (Celcius) | 10257:12
417 |   | Incorrect Unit value (Celcius) | 10257:13
417 |   | Incorrect Unit value (Celcius) | 10257:14
417 |   | Incorrect Unit value (Celcius) | 10257:15
417 |   | Incorrect Unit value (Kelvin) | 10257:16
417 |   | Incorrect Unit value (m^3 / s) | 10257:17
417 |   | Incorrect Unit value (m^3 / s) | 10257:18
417 |   | Incorrect Unit value (m^3) | 10257:20
417 |   | Incorrect Unit value (m^3) | 10257:21
417 |   | Incorrect Unit value (mA) | 10258:0
201 |   | Name is different for same Object ID | 10260
202 |   | Description is different for same Obj... | 10260
413 |   | Incorrect Type/Operation combination | 10260:3
201 |   | Name is different for same Object ID | 10260
202 |   | Description is different for same Obj... | 10260
417 |   | Incorrect Unit value (Seconds) | 10266:6000
417 |   | Incorrect Unit value (Seconds) | 10266:6001
417 |   | Incorrect Unit value (Seconds) | 10267:6000
417 |   | Incorrect Unit value (Seconds) | 10267:6001
417 |   | Incorrect Unit value (Seconds) | 10268:6000
417 |   | Incorrect Unit value (Seconds) | 10268:6001
417 |   | Incorrect Unit value (Seconds) | 10269:6000
417 |   | Incorrect Unit value (Seconds) | 10269:6001
417 |   | Incorrect Unit value (Seconds) | 10270:6000
417 |   | Incorrect Unit value (Seconds) | 10270:6001
417 |   | Incorrect Unit value (Seconds) | 10271:6000
417 |   | Incorrect Unit value (Seconds) | 10271:6001
417 |   | Incorrect Unit value (Seconds) | 10272:6019
417 |   | Incorrect Unit value (Seconds) | 10273:6019
417 |   | Incorrect Unit value (Seconds) | 10274:6019
417 |   | Incorrect Unit value (Seconds) | 10275:6019
417 |   | Incorrect Unit value (Seconds) | 10276:6019
417 |   | Incorrect Unit value (Seconds) | 10277:6019
417 |   | Incorrect Unit value (Seconds) | 10278:6019
417 |   | Incorrect Unit value (Seconds) | 10279:6019
417 |   | Incorrect Unit value (Seconds) | 10280:6019
417 |   | Incorrect Unit value (Seconds) | 10281:6019
417 |   | Incorrect Unit value (Seconds) | 10282:6019
417 |   | Incorrect Unit value (Seconds) | 10283:6019
417 |   | Incorrect Unit value (Seconds) | 10284:6019
417 |   | Incorrect Unit value (Seconds) | 10290:6000
417 |   | Incorrect Unit value (Seconds) | 10290:6001
417 |   | Incorrect Unit value (Seconds) | 10291:6000
417 |   | Incorrect Unit value (Seconds) | 10291:6001
417 |   | Incorrect Unit value (Seconds) | 10291:6040
417 |   | Incorrect Unit value (Seconds) | 10292:6000
417 |   | Incorrect Unit value (Seconds) | 10292:6001
417 |   | Incorrect Unit value (Seconds) | 10292:6040
417 |   | Incorrect Unit value (dBm) | 10309:4

**Comment by mkgillmore** [comment]
Units to be resolved at OMA f2f meeting july 16-18th

**Comment by mkgillmore** [comment]
@jpradocueva @akeranen Good news,  a second Senml registry will be created that will include ms, WH, KWH, etc

I think we only need to change degree to deg?

**Comment by jpradocueva** [comment]
@mkgillmore great news! Once the registration has taken place we will update the Common.xml file and prepare the corresponding PRs against existing Objects that are affected by the changes.

With regards to the "degree unit. In SenML there is no a symbol called "degree".
The symbols related to degrees are:

Symbol     |   Description
---------- | -------------
Cel             |  degrees Celsius
lat               |  degrees latitude
lon              | degrees longitude

So, I hope that that will be resolved as we need it for  RR 5705 which unit is set to "degree".

**Comment by jpradocueva** [comment]
Related IETF draft to address pending issues on units: https://tools.ietf.org/html/draft-bormann-senml-more-units-03#section-3. It is added here for reference.

**Comment by jpradocueva** [comment]
@akeranen @hannestschofenig I see that the above IETF draft has been partially implemented in SenML Lists in https://www.iana.org/assignments/senml/senml.xhtml. 
All the secondary seem to be missing. Do you know if it will be implemented a later stage?

**Comment by akeranen** [comment]
Yes, the draft just needs to go further for the new registry to be implemented on the IANA site. @cabo and @jaimejim are on it.

**Comment by jpradocueva** [comment]
Ok, thanks. I will wait until it is implemented in order to see what we need to do.
The "deg" was not implemented with the rest of the units. I guess that it will be implemented in the second part.

**Comment by jpradocueva** [comment]
PR #223  provides a resolution to the low-hanging fruit issues with Units. This PR introduce basic changes that don't imply any change in the Object version; e.g. change from "Seconds" to "s", Or "Celsius" to "Cel", etc

**Comment by jpradocueva** [comment]
@cabo @jaimejim when can we expect that the following table will be incorporated to the the SenML Registry?
The OMA registry for LwM2M cannot accept further registrations until this table is added to the SenML Registry:

![image](https://user-images.githubusercontent.com/3258579/64816022-b102c600-d55b-11e9-9cb1-edd0db9e54fa.png)

**Comment by jpradocueva** [comment]
@mkgillmore   Independently of when or how the above table containing the secondary Units is implemented in the SenML Registry. The  IPSO WG needs to resolve the following problems with Units on Reusable Resources or Objects already registered with OMNA:

- [ ] **Reusable Resources**

Description | Reusable Resource
 -- | --
Incorrect Unit value (degree) | 5705

In SenML there are three type of degrees:

Symbol | Description | Type | Reference
-- | -- | -- | --
Cel | degrees Celsius | float | [RFC8428]
lat | degrees latitude[1] | float | [RFC8428]
lon | degrees longitude[1] | float | [RFC8428]

RR 5705 is allocated to **Compass Direction** and the units are expressed as **degrees** which doesn't exist in SenML registry.

>Note: https://tools.ietf.org/html/draft-bormann-senml-more-units-03#section-3 contains the unit **deg** but it wasn't implemented.

**Comment by jpradocueva** [comment]
@mkgillmore these are the pending problems with Units on LwM2M Objects already registered with OMNA.
These problems need to be resolved by the IPSO WG as these units doesn't exist in SenML even after implementing the pending secondary units table:

Description | ObjectID : ResourceID
 -- | --
 Incorrect Unit value (Ws) | 3388:910
 Incorrect Unit value (Ws) | 3396:910
 Incorrect Unit value (Ws) | 3397:910
 Incorrect Unit value (Ws) | 3399:910
 Incorrect Unit value (kvarL) | 10242:8
 Incorrect Unit value (kvarC) | 10242:9
 Incorrect Unit value (kVA) | 10242:10
 Incorrect Unit value (kvarL) | 10242:18
 Incorrect Unit value (kvarC) | 10242:19
 Incorrect Unit value (kvarL) | 10242:28
 Incorrect Unit value (kvarC) | 10242:29
 Incorrect Unit value (kW III) | 10242:34
 Incorrect Unit value (kvar III) | 10242:35
 Incorrect Unit value (kvarL III) | 10242:36
 Incorrect Unit value (kvarC III) | 10242:37
 Incorrect Unit value (kVA III) | 10242:38
 Incorrect Unit value (kW/h III) | 10242:41
 Incorrect Unit value (kvar/h III) | 10242:42
 Incorrect Unit value (kvarL/h III) | 10242:43
 Incorrect Unit value (kvarC/h III) | 10242:44
 Incorrect Unit value (kVA/h III) | 10242:45
 Incorrect Unit value (kvarL) | 10243:8
 Incorrect Unit value (kvarC) | 10243:9
 Incorrect Unit value (kvar/h) | 10243:15
 Incorrect Unit value (kVA/h) | 10243:16
 Incorrect Unit value (km/h) | 10244:1
 Incorrect Unit value (km) | 10244:7
 Incorrect Unit value (rpm) | 10244:26
 Incorrect Unit value (degrees) | 10245:2

**Comment by jpradocueva** [comment]
Reply from Carsten on updates to the SenML Registry:

>The discussion we had during WG adoption raised a couple minor points, but nothing we couldn't handle during a WGLC. So if Jaime can do a chair's review soon, we could WGLC the document afterwards, say, until about Sep 30. 
Deg can be registered right away, but adding the second table requires iesg approval; so we should submit to iesg by, say, Oct 1 and could be approved by the end of the month, barring surprises. This is optimistic, but not unrealistic at all.

**Comment by jpradocueva** [comment]
Latest changes are suggested in: https://tools.ietf.org/html/draft-ietf-core-senml-more-units-01

**Comment by akeranen** [comment]
* Ws: J
* kvarL and kvarC: kvar (with L and C part already in description)
* kVA and kvar are in [more-units-02](https://tools.ietf.org/html/draft-ietf-core-senml-more-units-02#page-5)
* all instances of "III" should be removed (to description?)
* all "kvar/h" and "kW/h" should be clarified (/removed) (might be [unintentional](https://en.wikipedia.org/wiki/Kilowatt_hour#Misuse_of_watts_per_hour))

**Comment by cabo** [comment]
kW/h would be a power increase (a nano-Chernobyl?).
This (and kvar/h) is very likely kWh and kvarh.

**Comment by seanmcilroy29** [comment]
20 Unit values currently not registered with SenML or SenML Draft :

Error/unit not available in SenML |  Comments
-- | -- 
| Incorrect Unit value (Ws) | contacting submitter for clarification 
| Incorrect Unit value (kvarC) | contacting submitter for clarification
| Incorrect Unit value (kvarL) | contacting submitter for clarification
| Incorrect Unit value (kW III) | contacting submitter to remove III to description
| Incorrect Unit value (kvar III) | contacting submitter to remove III to description
| Incorrect Unit value (kvarL III) | contacting submitter to remove III to description
| Incorrect Unit value (kvarC III) | contacting submitter to remove III to description
| Incorrect Unit value (kVA III) | contacting submitter to remove III to description
| Incorrect Unit value (kW/h III) | contacting submitter to remove III to description
| Incorrect Unit value (kvarL/h III) | contacting submitter to remove III to description
| Incorrect Unit value (kvarC/h III) | contacting submitter to remove III to description
| Incorrect Unit value (kVA/h III) | contacting submitter to remove III to description
| Incorrect Unit value (kW/h) |contacting submitter for clarification
| Incorrect Unit value (kvar/h) | contacting submitter for clarification
| Incorrect Unit value (kVA/h) | contacting submitter for clarification
| Incorrect Unit value (km) | 
| Incorrect Unit value (rpm) | 
| Incorrect Unit value (Kelvin) | 
| Incorrect Unit value (m^3 / s) | 
| Incorrect Unit value (m^3) |

**Comment by cabo** [comment]
On Nov 27, 2019, at 12:25, Sean Mcilroy <notifications@github.com> wrote:
> 
> 20 Unit values currently not registered with SenML or SenML Draft :
> 
> Error/unit not available in SenML	Comments
> Incorrect Unit value (Ws)	contacting submitter for clarification

The registered unit is J (Joule)

> Incorrect Unit value (kvarC)	contacting submitter for clarification
> Incorrect Unit value (kvarL)	contacting submitter for clarification

The units are kvar here (to be in the secondary registry), the capacitive or inductive aspect is not part of the unit

> Incorrect Unit value (kW III)	contacting submitter to remove III to description
> Incorrect Unit value (kvar III)	contacting submitter to remove III to description
> Incorrect Unit value (kvarL III)	contacting submitter to remove III to description
> Incorrect Unit value (kvarC III)	contacting submitter to remove III to description
> Incorrect Unit value (kVA III)	contacting submitter to remove III to description
> Incorrect Unit value (kW/h III)	contacting submitter to remove III to description
> Incorrect Unit value (kvarL/h III)	contacting submitter to remove III to description
> Incorrect Unit value (kvarC/h III)	contacting submitter to remove III to description
> Incorrect Unit value (kVA/h III)	contacting submitter to remove III to description

The “III” aspects of the quantities are, again, not part of the unit.

> Incorrect Unit value (kW/h)	contacting submitter for clarification
> Incorrect Unit value (kvar/h)	contacting submitter for clarification
> Incorrect Unit value (kVA/h)	contacting submitter for clarification

These are very likely incorrect and should be kWh, kvarh, kVAh (to be in the secondary registry).
(Rates of change for power usage are rarely used.)

> Incorrect Unit value (km)	

To be in the secondary registry

> Incorrect Unit value (rpm)	

The registered unit is called 1/min

> Incorrect Unit value (Kelvin)	

The registered unit is called K

> Incorrect Unit value (m^3 / s)	

The registered unit is called m3/s

> Incorrect Unit value (m^3)	

The registered unit is called m3

Grüße, Carsten

**Comment by jpradocueva** [comment]
@cabo do you have a deadline by when the secondary registry will be implemented? We have around 150 errors in our OMNA LwM2M Registry due to incorrect units awaiting which are awaiting for this secondary table.

**Comment by seanmcilroy29** [comment]
Incorrect Unit values removed in updated Objects 10242 & 10243

Error removed | Object:RR
-- | --
Incorrect Unit value (kvarL) | 10242:8
Incorrect Unit value (kvarC) | 10242:9
Incorrect Unit value (kvarL) | 10242:18
Incorrect Unit value (kvarC) | 10242:19
Incorrect Unit value (kvarL) | 10242:28
Incorrect Unit value (kvarC) | 10242:29
Incorrect Unit value (kW III) | 10242:34
Incorrect Unit value (kvar III) | 10242:35
Incorrect Unit value (kvarL III) | 10242:36
Incorrect Unit value (kvarC III) | 10242:37
Incorrect Unit value (kVA III) | 10242:38
Incorrect Unit value (kW/h III) | 10242:41
Incorrect Unit value (kvar/h III) | 10242:42
Incorrect Unit value (kvarL/h III) | 10242:43
Incorrect Unit value (kvarC/h III) | 10242:44
Incorrect Unit value (kVA/h III) | 10242:45
Incorrect Unit value (kvarL) | 10243:8
Incorrect Unit value (kvarC) | 10243:9
Incorrect Unit value (kvar/h) | 10243:15
Incorrect Unit value (kVA/h) | 10243:16

**Comment by seanmcilroy29** [comment]
Outstanding submitted Object unit errors resolved in Revised-Common branch

Error |   | Incorrect Description | PR 
-- | -- | -- | --
417 |   | Incorrect Unit value (Ws) | #387 
417 |   | Incorrect Unit value (minute) | #381 
417 |   | Incorrect Unit value (rpm) | #381 
417 |   | Incorrect Unit value (GB) | #390 
417 |   | Incorrect Unit value (Mbit/s) | #390 
417 |   | Incorrect Unit value (MB/s) | #390 
417 |   | Incorrect Unit value (m/h) | #390 
417 |   | Incorrect Unit value (cm) | #390

**Comment by seanmcilroy29** [comment]
IPSO Working Group agreed to accept ``Ws`` - Watt per second, for registration

**Comment by jpradocueva** [comment]
All issue resolves.
IPSO WG agreed to accept ```Ws``` as a unit. It was added to the LWM2M_senml_unitls.xml file.
