### ISSUE TITLE
Request for reserving a 100 ObjectID in range 7700 - 7799

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#157]
Dear OMA Helpdesk,

uCIFI is an industry alliance created and composed of Smart City and Smart Utility international companies : https://ucifi.com . The goal of the uCIFI alliance is to provide a common data model for the smart city objects which are required in the many smart streetlight, smart traffic, smart waste, smart parking and other smart city projects. The uCIFI Technical Workgroup has decided to define standard smart city objects based on LwM2M and as a complement of existing IPSO objects. We have already defined 33 new types of smart city objects and their resources, and should be ready to register them in the OMA registry in the 2nd half of the year.Question: would it be possible to reserve a range of Object ID for our uCIFI Alliance ? Would you agree to reserve the range from 7700 to 7799 for uCIFI smart city objects ?Thanks in advance.

Best regards,The uCIFI Technical Team.

**Comment by seanmcilroy29** [comment]
The allocated Object ID Range reservation in the ext-label table is from 3500 to 3599 - http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#extlabel

**Comment by seanmcilroy29** [comment]
this issue can be closed

**Comment by mkgillmore** [comment]
This can be close as the IPSO WG agreed
