### ISSUE TITLE
[TMO] Temp: 10304 - OMNA-Registration of WiFi Scan

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#16]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-14 23:23:21 UTC</td></tr><tr><td>Submitter's name</td><td>Joe Baird</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>T-Mobile</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>WiFi Scan</td></tr><tr><td>Object Description</td><td>Allow wi-fi scan data to be sent to the LWM2M server. The data can be used to provide crowd-sourced location lookup or setup</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=8d344bf2-1b6d-4660-b054-272c534972d4_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/8d344bf2-1b6d-4660-b054-272c534972d4_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8d344bf2-1b6d-4660-b054-272c534972d4_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
@joebaird  a new branch called [TMO] has been created to submit your new registrations. Once the PRs are submitted we will validate them and the discussion with the working group will start. Please be aware that we are creating the new registration process as we go along, changes to the guidelines should be expected.

**Comment by joebaird** [comment]
Thank you @jpradocueva

**Comment by ScottTaftPotter** [comment]
@joebaird, we are closing this issue and the TMO feature branch  for now. You can resubmit at any time.
