### ISSUE TITLE
[Action Item] LwM2M TS constraints on the RR description field

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#162]
LwM2M TS constraints on the RR description field needs to be reviewed as they are considered too restrictive i.e for updating typo's 

*the registered Description field of a Reusable Resource is also a frozen characteristic*

Matt/Ari to raise this issue with the DMSE WG.

**Comment by akeranen** [comment]
@hannestschofenig to the agenda?

**Comment by mkgillmore** [comment]
Has a pull request been submitted to update the TS? @hannestschofenig

**Comment by akeranen** [comment]
Same as #163

**Comment by mkgillmore** [comment]
@akeranen Can I close this and keep 162 open?

**Comment by akeranen** [comment]
@mkgillmore can close this and keep #163 open
