### ISSUE TITLE
[Action Item] Updating registered RR Names

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#163]
Some registered  RR Names are deemed too generic and should be reviewed with a view to of updating them - An example is RR 6027 Stop

Currently the TS outlines
**the Name, ID, Operation, Type, Range and Units are frozen characteristics (same applies to the Definition) when the
Reusable Resource is registered at [OMNA] cannot be changed when such a
Resource is specified in the definition of a hosting Object.**

Action Item Matt/Ari to discuss updating the TS with DM&SE
Working Group to review the current Guidelines to specify the requirements for RR 'Name' submissions

**Comment by akeranen** [comment]
@hannestschofenig to the agenda?

**Comment by mkgillmore** [comment]
DMSE and IPSO WG jointly agree on changing the descriptions without changing the rev.  In the future, editorial changes will affect the third digit of the version.

**Comment by jpradocueva** [comment]
@mkgillmore @hannestschofenig if I understand correctly, DMSE agrees that Reusable Resources inserted in an Object can have a customize description.
In that case, some one needs to put a PR against the TS Core: 7.3.2 Reusable Resources
*... bulet point 2*

>the registered Description field of a Reusable Resource is also a frozen characteristic; when extension is required to fit the real need of the Object hosting such a Resource, that extension must be mentioned in the Object specification but outside of the Description field itself; furthermore any extension MUST be compatible with the content of the registered Description field.

Once this statement is revised, we will update the LwM2M Editor code to allow changes in the Description and to stop the validation (where both descriptions are compared).

With regards to the 3rd digit of the version.
* what does it mean? 
* Are we introducing 3 digits to define an Object Version?

**Comment by hannestschofenig** [comment]
From the Montreal meeting minutes:

The group asked whether we should allow updating the description of the resources (editorial changes only) without increasing the version number of the object/re-issuing reusable resources. 

Conclusion: 
   - IPSO will make editorial changes to the reusable resource description where needed. 
   - David suggest to enhance the description in Section 7.3.2. Reusable Resources in the LwM2M Core specification with regards to the evolution of the reusable resource.
[JP] The TS needs to be updated to reflect this change. In the TS the description is defined as frozen, that it cannot be changed.

   - Invite Joaquin to future IPSO call to provide background about third version number digit and its usage. In particular, if the reusable resource description is changed is the third digit of all objects that make use of this reusable resource required to increase the third digit of the version number.
[JP] A new presentation will be ready by Thursday 25th July, OMA-IPSO-2019-0090-INP_How_FileName_Versioning_Works_in_OMA

**Comment by akeranen** [comment]
Seems we have reasonable way forward for descriptions, but how about **names**? Same rules?

**Comment by jpradocueva** [comment]
The LwM2M Editor Tool was updated to allow changes in the description of RR. 
Months later, there were changes to the RR description and the tool start showing validation errors. 
Now we need to reverse the changes in the LwM2M Editor Tool to DON'T allow changes in the RR description. Once this change is done, we will validate the content of the repository and pending PRs.

**Comment by mkgillmore** [comment]
Need Ari to review @akeranen
