### ISSUE TITLE
OMNA-Registration of Digital Input

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#166]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-06-11 06:25:37 UTC</td></tr><tr><td>Submitter's name</td><td>Sangho Lee</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Wayble</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Digital Input</td></tr><tr><td>Object Description</td><td>This object provides emergency information according to the button push pattern (short, double, long).</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=eae978c6-6135-4980-83fc-19864de61ab1_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/eae978c6-6135-4980-83fc-19864de61ab1_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=eae978c6-6135-4980-83fc-19864de61ab1_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
The submitted Registration is an extract match from Object ID 3200 - Digital Input.
If you'd like to submit a unique object, please register via the [Editor tool ](https://devtoolkit.openmobilealliance.org/OEditor/). To aid in your submission, user [guidelines](https://wiki.openmobilealliance.org/display/TOOL/Introduction+to+LightweightM2M)are available
