### ISSUE TITLE
[OpenLX SP] Measured Particle Size - RR 6043

### ISSUE THREAD

**Issue by envirocoder** [OpenMobileAlliance/lwm2m-registry#169]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-06-17 16:37:58 UTC</td></tr><tr><td>Submitter's name</td><td>A Robinson</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>OpenLX SP Ltd</td></tr><tr><td>Type of registration</td><td>Reusable resources</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=c7f14a9b-5e09-4526-94ad-df533a464e38_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/c7f14a9b-5e09-4526-94ad-df533a464e38_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=c7f14a9b-5e09-4526-94ad-df533a464e38_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
- [ ] Reusable Resource allocation ID 6043
- [ ] Update/add details to submitted Object - See #170 
   - [ ]  Please note the submitted Reusable Resource Unit `um` isn't a standard within [SenML](https://www.iana.org/assignments/senml/senml.xhtml). Can you update with a unit defined in SenML or indicate `To Be  Defined.`

**Comment by envirocoder** [comment]
Hello, thanks for this -- can you just give me a bit of guidance on the unit. 

The resource unit for my need is micrometers (since particles in the air are tiny). 

taking http://openmobilealliance.org/tech/profiles/lwm2m/3396.xml as an example I saw it includes milliseconds, but this is not in SenML.
`<Units>ms</Units>
<Description>Remaining approximated time of any ongoing colour change process which requires a variation of the light output over a period of time higher or equal to one 100ms interval....</Description></Item>`
I would assume this referred to milliseconds.

What's the guidance on si prefixs?
Should I use um for micrometers or m and put a comment that it will be scaled or should I put a prefix in i.e. 1e-6m?

rfc8428 states:
>  Use of System of Units (SI) prefixes such as "k" before the unit
>         is not recommended.  Instead, one can represent the value using
>         scientific notation such as 1.2e3.  The "kg" unit is an
>         exception to this rule since it is an SI base unit; the "g" unit
>         is provided for legacy compatibility.

but I haven't seen these prefixes used in IPSO resources anywhere else?

Thanks

**Comment by seanmcilroy29** [comment]
@akeranen - Can you offer guidance on this unit proposal?

**Comment by akeranen** [comment]
Hi @envirocoder, instead of using unit prefixes the current recommended way is to put the scale into the value, i.e., unit is still "m" but the value would be e.g., 42e-9. On the wire you can use that (exponent) syntax in the JSON format or with CBOR use the float or decfrac types.

**Comment by envirocoder** [comment]
Thanks, for your advice on this.
Changes contained in PR #190

**Comment by seanmcilroy29** [comment]
RR merged - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/190
RR published to registry - http://openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html
