### ISSUE TITLE
[TMO] Temp: 10305 OMNA-Registration of Activity

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#17]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-14 23:26:22 UTC</td></tr><tr><td>Submitter's name</td><td>Joe Baird</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>T-Mobile</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Activity</td></tr><tr><td>Object Description</td><td>Ability to report step counting and time information.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=3a9482d5-a67e-4316-8fa4-1dc6d5ad690a_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/3a9482d5-a67e-4316-8fa4-1dc6d5ad690a_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=3a9482d5-a67e-4316-8fa4-1dc6d5ad690a_Object.xml">Load Editor with object</a></td></tr>

**Comment by ScottTaftPotter** [comment]
@joebaird, we are closing this issue and the TMO feature branch  for now. You can resubmit at any time.
