### ISSUE TITLE
[OpenLX SP] Particulates - 10314

### ISSUE THREAD

**Issue by envirocoder** [OpenMobileAlliance/lwm2m-registry#170]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-06-17 16:42:39 UTC</td></tr><tr><td>Submitter's name</td><td>A Robinson</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>OpenLX SP Ltd</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Particulates</td></tr><tr><td>Object Description</td><td>Particulate air quality sensor to report a particulates measurement.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=ea034c81-fed5-473a-aa25-57087ddabb84_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/ea034c81-fed5-473a-aa25-57087ddabb84_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=ea034c81-fed5-473a-aa25-57087ddabb84_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

- [ ] The object ID allocation for this object will be reserved as 10314
- [ ] The object URN allocation for this object will be reserved as oma:lwm2m❌10314
- [ ] Reusable Resource allocation ID 6043

A new branch, `OpenLx`  has been created in the LwM2M registry for the WG to review your object

**Steps**
 - [ ] Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/OpenLx

**Observations to be addressed**
  - [ ] The submitted object **fails validation**. Line 1 - `This XML file does not appear to have any style information associated with it. The document tree is shown below.` replace with `<?xml version="1.0" encoding="UTF-8"?>`
  - [ ] Object version updated to 1.0
  - [ ] Object ID updated to 10314
  - [ ] Object urn updated to urn:oma:lwm2m❌10314
  - [ ] Update/add details to omitted Reusable Resource with 6043 ID to the Object
     - [ ] Please note the submitted Reusable Resource Unit `um` isn't a standard within [SenML](https://www.iana.org/assignments/senml/senml.xhtml). Can you update with a unit defined in SenML or indicate`To Be Defined`. 

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request to the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
@envirocoder - To start the review process could you submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/OpenLx

As a note, the Working Group are meeting tomorrow

**Comment by seanmcilroy29** [comment]
@envirocoder - To start the review process, please could you submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/OpenLx

As a note, the Working Group are meeting tomorrow, so if the PR is submitted the WG will review this object

**Comment by envirocoder** [comment]
Thanks, contained in PR #190

**Comment by seanmcilroy29** [comment]
Object merged - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/190
Object published to registry - http://openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html
