### ISSUE TITLE
OMNA-Registration of Test Object

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#177]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-06-19 09:26:57 UTC</td></tr><tr><td>Submitter's name</td><td>Sean Mcilroy</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Test Org</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Test Object</td></tr><tr><td>Object Description</td><td>test Description</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=1672ac84-fc72-46bf-88cc-76cc06185874_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/1672ac84-fc72-46bf-88cc-76cc06185874_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1672ac84-fc72-46bf-88cc-76cc06185874_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Test line 1 of xml
