### ISSUE TITLE
[Action Item] Add a new re-usable resource ”Measurement Context” (R, string)

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#180]
Add a new re-usable resource ”Measurement Context” (R, string)
- Machine readable, standard set of measurement context metadata
- What standard to use?
- Who will keep this standard up-to-date?

**Comment by mkgillmore** [comment]
@dirtyha Can you be available sometime between 7/16-7/18 to discuss via GoToMeeting?

**Comment by dirtyha** [comment]
Hi, I'm currently on vacation and unable to attend. I'm back to the office
on July 25th.

Br,
Harri

to 11. heinäk. 2019 klo 18.42 mkgillmore <notifications@github.com>
kirjoitti:

**Comment by akeranen** [comment]
This one needs quite a bit more thinking and design work but is very important going forward. But not urgent. Should be aligned with (TBD) design in OneDM.

**Comment by seanmcilroy29** [comment]
See PR - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/516
