### ISSUE TITLE
[Action Item] Harmonise resource 'Application Type' to all sensor objects.

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#181]
Harmonise resource 'Application Type' (5750) for all sensor objects.
- [ ] Working Group to create a table with all the ID'd Objects and RRs that require to be modified & forward to OMA Staff
- [ ] OMA Staff Implement the changes required to Harmonise resource 'Application Type'

**Note: Required to be implemented by end Sept 2019**

**Comment by seanmcilroy29** [comment]
Info moved from Issue #160 
A call with @akeranen revealed that adding re-usable resource (Application Type) implicitly to IPSO object is not possible. So, my proposal is to explicitly add it to IPSO objects by creating a new object version.

The following IPSO objects are missing Application Type (5750) reusable resource, possibly accidentally.

ID	Name
3301	Illuminance
3302	Presence
3303	Temperature
3304	Humidity
3305	Power Measurement
3310	Load Control
3313	Accelerometer
3314	Magnetometer
3315	Barometer

**Comment by akeranen** [comment]
Also addressed by #403

**Comment by seanmcilroy29** [comment]
See PR - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/516
