### ISSUE TITLE
[Action Item] Add new optional resource 'Timestamp'

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#184]
Create PR to add new optional resources ”Timestamp” (5518) to all sensor objects
- Application can then explicitly read measurement time provided in the object model

**Comment by dirtyha** [comment]
I propose that optional resource 'Timestamp' is added to IPSO smart objects 3200-3350 which represent a sensor:

3200-3203 (analog and digital input/output where a sensor can be connected)
3300-3305
3313-3328
3330-3332
3334-3336
3346

The excluded are objects that represent a controller, actuator or something similar to change device state. I'm not sure if "Timestamp" is needed for them, at least I see no need for us (Vaisala). Maybe for some applications the timestamp could tell when the state was actually changed in the device initiated by the server or done at the device from UI.

**Comment by akeranen** [comment]
Seems to be resolved by #403

**Comment by seanmcilroy29** [comment]
See - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/516
