### ISSUE TITLE
[Action Item] Measurement Quality update

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#185]
Add a new optional resource ”Measurement Quality” (6042) (R, integer) to the required objects

- [x] Rename the description to Measurement Quality Enumeration and create a new RR called Measurement Quality Percentage that is a range from 0..100

 - [x] Working Group to create a table with all the ID'd Objects and RRs that require to be modified & forward to OMA Staff

  - [x] OMA Staff Implement the changes required to Harmonise resource ”Measurement Quality”

**Comment by dirtyha** [comment]
Updated PR #159 so that the name of RR 6042 is Measurement Quality Indicator as suggested by @mkgillmore

**Comment by dirtyha** [comment]
Should I include the new RR Measurement Quality Percentage into the same PR #159 or create a new PR? What should be the id for the new RR?

**Comment by seanmcilroy29** [comment]
@dirtyha - The next RR id is 6049.
If you're going to register a new RR could you submit a new PR via https://devtoolkit.openmobilealliance.org/OEditor/LWMOEdit

**Comment by akeranen** [comment]
This one is resolved, right?

**Comment by jpradocueva** [comment]
yes this one can be closed. RR 6049 Measurement Quality Level has been registered. 

http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html

**Comment by seanmcilroy29** [comment]
See PR https://github.com/OpenMobileAlliance/lwm2m-registry/pull/516
