### ISSUE TITLE
[ICA] Smoke Alarm - 3407

### ISSUE THREAD

**Issue by QingAn** [OpenMobileAlliance/lwm2m-registry#199]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-07-16 11:13:12 UTC</td></tr><tr><td>Submitter's name</td><td>Qing An</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>ICA (IoT Connectivity Alliance)</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Smoke Alarm</td></tr><tr><td>Object Description</td><td>This is an alarm that should be raised if the meter detects CO2 concentration above a pre-configured threshold</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=90121e10-a747-4055-9c3a-8b793bdda28c_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/90121e10-a747-4055-9c3a-8b793bdda28c_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=90121e10-a747-4055-9c3a-8b793bdda28c_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

**Object Updates**
- [ ] The object Version 1.0
- [ ] The object URN allocation for this object will be reserved as oma:lwm2m:ext:3407

A new branch, `ICA`  has been created in the LwM2M registry for the WG to review your object

**Steps**
 - [ ] Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/ICA

- [x] Object passed Validation

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request to the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
@QingAn - Please note, that for the WG to Approve this object you must submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/ICA

**Comment by QingAn** [comment]
@seanmcilroy29 - New Pull Request has been made, please check: https://github.com/OpenMobileAlliance/lwm2m-registry/pull/208

**Comment by seanmcilroy29** [comment]
PR's ready for WG review
Object - #212 
RRs - #202

**Comment by seanmcilroy29** [comment]
@QingAn - Reusable Resources (RR) 6044, 6045, 6046, 6047, 6048 have been agreed by the WG.

To reflect the Agreed RRs, Comments have been applied against your submitted Object [3407](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/212) that requires you to apply directly.

**Comment by seanmcilroy29** [comment]
Object Approved - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/212
