### ISSUE TITLE
[Open-AIS] Feedback from Open-AIS

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#20]
Comments from Open - AIS experience:

However, I do think some of the learnings should trigger some clarification / discussion at your side:

-x- decide / document the correct and acceptable way to define string length: 
A: 
<type>String</type>
<RangeEnumeration>0-16 bytes</RangeEnumeration>
<units></units>
B:
<type>String</type>
<RangeEnumeration>0-16</RangeEnumeration>
<Units>byte</Units>

-x- consider new types / additional documentation to avoid some common "opaque“ types: 
—> IPv6 Address / Adresses.
—> Vector Data (Vectors consist of multiple single types, that are packed into a single resource. 
(My Suggestion / input for the vector discussion):
<type>Vector</type>
<RangeEnumeration>JSON-STRING</RangeEnumeration>, where the JSON-STRING given documents the components and structure of the vector data.

-x- suggest to allow for bit- or bytecount length definition within the RangeEnumeration field: 
Actual:  <RangeEnumeration>0-18446744073709551615</RangeEnumeration>
Proposed alternative: <RangeEnumeration>64 bits</RangeEnumeration> or .<RangeEnumeration>8 bytes</RangeEnumeration>

-x- With shared resources allow for specific Range definitions where the template definition is open: 
e.g. the use of shared resource 4001: <RangeEnumeration>0-16 bytes</RangeEnumeration> should be seen as compliant with the template / definition that says <RangeEnumeration></RangeEnumeration>

Practical issue: It would be helpful to have an XML template that allows to copy-paste the xml-snippet for a shared resource. This would ease the interpretation work substantially.

**Comment by ScottTaftPotter** [comment]
@mkgillmore : We would like to capture this feedback appropriately before closing this issue. Suggestion from the group is to assign specific tasks and drive them to a close.

**Comment by mkgillmore** [comment]
@hannestschofenig 
Create a pull request for lwm2m v1.2 to address these additional data types

**Comment by mkgillmore** [comment]
Ask the staff to transfer to DMSE

**Comment by seanmcilroy29** [comment]
Moved to LwM2M See issue - https://github.com/OpenMobileAlliance/LwM2M/issues/367
