### ISSUE TITLE
Object Validator returning error for IPSO objects

### ISSUE THREAD

**Issue by lucabotelit** [OpenMobileAlliance/lwm2m-registry#200]
While using the Object Validator I can see there are 14 errors related to your standard IPSO objects (see picture below)
 
![screen](https://user-images.githubusercontent.com/52996804/61367746-90d0c680-a88c-11e9-8e77-6e32521804b8.jpg)

**Comment by jpradocueva** [comment]
@mkgillmore this problem is related to the SenML units. We need to resolve this issue as soon as possible, it is creating confusion for those that are following lwm2m objects.

**Comment by seanmcilroy29** [comment]
SenML units have been registered and the related errors have now been removed

**Comment by seanmcilroy29** [comment]
SenML registry updated. 
All Object validator Errors removed
