### ISSUE TITLE
[ICA] Manhole Cover - 3408

### ISSUE THREAD

**Issue by QingAn** [OpenMobileAlliance/lwm2m-registry#213]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-07-30 03:30:53 UTC</td></tr><tr><td>Submitter's name</td><td>Qing An</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>ICA</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Manhole Cover</td></tr><tr><td>Object Description</td><td>Describe the status of a manhole cover</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=5c4298dc-73d2-49a7-a98e-e417fc5317c7_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/5c4298dc-73d2-49a7-a98e-e417fc5317c7_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=5c4298dc-73d2-49a7-a98e-e417fc5317c7_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

**Object Updates**
- [ ] The object Version 1.0
- [ ] The object URN allocation for this object will be reserved as oma:lwm2m:ext:3408

A new branch, `ICA_1`  has been created in the LwM2M registry for the WG to review your object

**Steps**
 - [ ] Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/ICA_1

- [x] Object passed Validation and well-formed

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request against the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
Object agreed - See #219
