### ISSUE TITLE
[Vaisala] Reusable resource - 6049 Measurement Quality Level

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#216]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-07-30 11:10:37 UTC</td></tr><tr><td>Submitter's name</td><td>Harri Hytönen</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Vaisala</td></tr><tr><td>Type of registration</td><td>Reusable resources</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=c6139f59-ed42-451d-9468-56564507232f_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/c6139f59-ed42-451d-9468-56564507232f_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=c6139f59-ed42-451d-9468-56564507232f_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration

A new branch, Vaisala-1 has been created in the LwM2M registry for the WG to review your Reusable resource:

Please submit a Pull Request with the content of your reusable resource against the common file in the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Vaisala-2

Steps:
1. Update the common.xml ID 6049 with Reusable Resource Definitions
2. Submit PR for Working Group review.

**Comment by seanmcilroy29** [comment]
RR agreed - See #218
