### ISSUE TITLE
[TUT] OMNA-Registration of LWM2M Meta Object -10300

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#22]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-19 09:43:09 UTC</td></tr><tr><td>Submitter's name</td><td>Tampere University of Technology</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LWM2M Meta Object</td></tr><tr><td>Object Description</td><td>We want to register existing object</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=99bdfea8-f8e1-48d1-9613-07f7834f2f5e_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/99bdfea8-f8e1-48d1-9613-07f7834f2f5e_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=99bdfea8-f8e1-48d1-9613-07f7834f2f5e_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Branch: [TUT](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/TUT)
Temporal ObjectID: 10300

**Comment by jpradocueva** [comment]
Errors found on the validation of 10300 Object:


Error Code |   Error Description | ObjectID: ResourceID
-- | -- | --
463 |    RangeEnumeration is different | 10300:4000
464 |    Units is different | 10300:4000

According to the Technical Specification, section 7.3.2 Reusable Resources. Values of Reusable Resources defined in OMNA cannot be modified when used inside of an Object.

**Comment by seanmcilroy29** [comment]
The Object has been reviewed by the Working Group and comments were submitted to the following Pull Request https://github.com/OpenMobileAlliance/lwm2m-registry/pull/32

Please can you review the comments and update accordingly. 
Once completed the Working Group will review the updates

**Comment by ScottTaftPotter** [comment]
Pull request #66 has superseded 32, closed.

**Comment by seanmcilroy29** [comment]
Resolved See PR - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/165
