### ISSUE TITLE
[GSMA] ConnectedDRX - 3409

### ISSUE THREAD

**Issue by dkhettry** [OpenMobileAlliance/lwm2m-registry#220]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-08-01 20:19:10 UTC</td></tr><tr><td>Submitter's name</td><td>Dhruv Khettry</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>GSMA</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>ConnectedDRX</td></tr><tr><td>Object Description</td><td>Object for Connected mode DRX used for Cat-M1 and NB-IoT</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=5e86d082-6434-44d0-97b9-0b0bf4790707_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/5e86d082-6434-44d0-97b9-0b0bf4790707_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=5e86d082-6434-44d0-97b9-0b0bf4790707_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

**Object Updates**
- [ ] Object ID 3409
- [ ] The object URN allocation for this object will be reserved as oma:lwm2m:ext:3409

A new branch, `GSMA`  has been created in the LwM2M registry for the WG to review your object

**Steps**
 - [ ] Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/GSMA

- [x] Object passed Validation

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request to the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
@dkhettry - Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/GSMA, to start the registration process

**Comment by seanmcilroy29** [comment]
@dkhettry - Note PR #230 was been closed as it was submitted against the``test`` branch. Could you please submit your PR against the ``GMSA`` branch with the content of the Object 3409 - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/GSMA.

An invite has been sent to https://github.com/OpenMobileAlliance/lwm2m-registry/invitations so you can join "lwm2m-registry" as a collaborator.

**Comment by seanmcilroy29** [comment]
@dkhettry - The IPSO WG will be holding a Conf Call tomorrow to review submitted Objects for Approval. 

Could you please submit your PR against the GMSA branch with the content of the Object 3409 - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/GSMA.

An invite has been sent to https://github.com/OpenMobileAlliance/lwm2m-registry/invitations so you can join "lwm2m-registry" as a collaborator.

**Comment by mkgillmore** [comment]
Group agrees to close this issue due to inactivity from the original submitter.  However we will keep the number 3409 reserved - IPSO WG agrees 11/19/2019
