### ISSUE TITLE
OMNA-Registration of radioLinkMonitoring

### ISSUE THREAD

**Issue by mnoyes73** [OpenMobileAlliance/lwm2m-registry#224]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-08-20 08:11:42 UTC</td></tr><tr><td>Submitter's name</td><td>Marie Noyes</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>radioLinkMonitoring</td></tr><tr><td>Object Description</td><td>My personal phone is being monitored and controlled.TW-14642-A01</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=7fc661ff-203d-41ce-987c-1fb16dc8e29c_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/7fc661ff-203d-41ce-987c-1fb16dc8e29c_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=7fc661ff-203d-41ce-987c-1fb16dc8e29c_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
This submission is a duplication of GSMA Object 3374 (radioLinkMonitoring) and isn't a valid submission
