### ISSUE TITLE
OMNA-Registration of BinaryAppDataContainer

### ISSUE THREAD

**Issue by aoncorici** [OpenMobileAlliance/lwm2m-registry#225]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-08-20 10:39:10 UTC</td></tr><tr><td>Submitter's name</td><td>Andreea Ancuta Corici</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Fraunhofer FOKUS Institut</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>BinaryAppDataContainer</td></tr><tr><td>Object Description</td><td>Propose additional Resources: Protocol, in case there are multiple Application Servers that support different protocols.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=79918cdd-33b0-4788-bb94-7e4bb2b7ab8e_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/79918cdd-33b0-4788-bb94-7e4bb2b7ab8e_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=79918cdd-33b0-4788-bb94-7e4bb2b7ab8e_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
@aoncorici - Your object submission is a duplication of OMA Object ID19 - BinaryAppDataContainer.

If you have an Issue/question proposing additional resources to this Object, it can be submitted via [lwm2m-registry Issues](https://github.com/OpenMobileAlliance/lwm2m-registry/issues) for the DM working group to review.
