### ISSUE TITLE
[OpenAIS] Review Units in types marked as "string"

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#227]
OpenAIS resources with "string" type should not have Units marked as Bytes.

https://github.com/OpenMobileAlliance/lwm2m-registry/pull/223#discussion_r324427474

**Comment by seanmcilroy29** [comment]
Issue can be closed - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/223#discussion_r324427474
