### ISSUE TITLE
RR 5501 description refinement

### ISSUE THREAD

**Issue by akeranen** [OpenMobileAlliance/lwm2m-registry#234]
The RR 5501 (Digital Input Counter) description is currently "The cumulative value of active state detected." This seems a bit confusing and could be refined.

**Comment by akeranen** [comment]
Something like "The cumulative number of times the digital input resource is detected being in active state". But need to be careful to not change the semantics here. Alternatively, could keep this as such and create a new RR in future that has more clear semantics.

**Comment by mkgillmore** [comment]
This issue has been covered with the latest changes
