### ISSUE TITLE
OMNA-Registration of HostDevice

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#25]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-20 01:31:22 UTC</td></tr><tr><td>Submitter's name</td><td>Joaquin Test</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Test - Please ignore</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>HostDevice</td></tr><tr><td>Object Description</td><td>Test, please ignore</td></tr><tr><td>Download Object</td><td><a href="http://dev_devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=c575bc6e-3c6d-4ae0-ac5c-aaab60e2cd50_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://dev_devtoolkit.openmobilealliance.org/OEditor/OMNA/c575bc6e-3c6d-4ae0-ac5c-aaab60e2cd50_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://dev_devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=c575bc6e-3c6d-4ae0-ac5c-aaab60e2cd50_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Test registration. To be closed.
