### ISSUE TITLE
[Action Item] Re-usable Resource 4010-4015 (Log*) descriptions

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#255]
Proposed Change

The descriptions of the Re-usable Resources for Logging don't seem to make much sense outside of the TS. For example RR LogStart:

**Actions: a) Start data collection (DC) b) LogStatus is set to 0 (running) c) DC is emptied (default) or extended according arg'0' value Arguments definitions are described in the table below.**

And RR LogStop:

**Actions: a) Stop data collection (DC) b) 1st LSB of LogStatus is set to "1"(stopped) c) DC is kept (default) or emptied according to arg'0' value Arguments definitions are described in the table below.**

These all should be reviewed and fixed to be understandable as stand-alone. Also, there are some missing while spaces in the descriptions.

**Comment by jpradocueva** [comment]
This issue is linked to: https://github.com/OpenMobileAlliance/LwM2M/issues/310 closed in LwM2M

**Comment by mkgillmore** [comment]
This actually affects RR 4011 and 4012.  PR needs to be created
