### ISSUE TITLE
[Vaisala] Fractional Timestamp - RR 6050

### ISSUE THREAD

**Issue by dirtyha** [OpenMobileAlliance/lwm2m-registry#259]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-10-25 10:01:21 UTC</td></tr><tr><td>Submitter's name</td><td>Harri Hytönen</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Vaisala</td></tr><tr><td>Type of registration</td><td>Reusable resources</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=12c3a3cb-ab3d-488d-a155-e004262dbd1f_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/12c3a3cb-ab3d-488d-a155-e004262dbd1f_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=12c3a3cb-ab3d-488d-a155-e004262dbd1f_Object.xml">Load Editor with object</a></td></tr>

**Comment by dirtyha** [comment]
As discussed in IPSO meeting 2019-10-24, this is the proposal for fractional timestamp RR for measurements. Additional note is that "Fractional Time" RR 5507 can not be used, since it is used for wall clock, not measurement timestamp, fractional seconds.

**Comment by seanmcilroy29** [comment]
A new branch, Vaisala has been created in the LwM2M registry for the WG to review your Reusable resource 6050:

Please submit a Pull Request with the content of your reusable resource against the common file in the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Vaisala

**Comment by seanmcilroy29** [comment]
RR-6050 Fractional Timestamp added in PR https://github.com/OpenMobileAlliance/lwm2m-registry/pull/265
