### ISSUE TITLE
[HuaXiang] OMNA-Registration of DeviceDataContainer -10309

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#27]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2018-12-21 11:46:56 UTC</td></tr><tr><td>Submitter's name</td><td>DengJia</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>HuaXiangIOT</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>DeviceDataContainer</td></tr><tr><td>Object Description</td><td>DeviceData Container Object of HuaXiangIOT.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=8fff1cee-59b8-430b-81ae-ce25b784d396_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/8fff1cee-59b8-430b-81ae-ce25b784d396_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8fff1cee-59b8-430b-81ae-ce25b784d396_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This Object has been submitted for discussion here: https://github.com/OpenMobileAlliance/lwm2m-registry/pull/33

**Comment by jpradocueva** [comment]
Several commits were applied after OMNA validation.

**Comment by seanmcilroy29** [comment]
The Object has been reviewed by the Working Group and comments were submitted to the following Pull Request https://github.com/OpenMobileAlliance/lwm2m-registry/pull/33

Please can you review the comments and update accordingly. 
Once completed the Working Group will review the updates

**Comment by jpradocueva** [comment]
PR #76 has been approved.
