### ISSUE TITLE
[CloudMinds] Robot - 10315

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#270]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-11-02 03:31:55 UTC</td></tr><tr><td>Submitter's name</td><td>Kenny Li</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>CloudMinds</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Robot</td></tr><tr><td>Object Description</td><td>This LWM2M Object includes robot information and links to the location object.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=4cb17b40-2a31-4147-9f30-3037cb997066_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/4cb17b40-2a31-4147-9f30-3037cb997066_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=4cb17b40-2a31-4147-9f30-3037cb997066_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
See Issue #272
Object submission grouped under this submission

Issue Closed
