### ISSUE TITLE
[CloudMinds] RCU - 10316

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#271]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-11-02 03:44:08 UTC</td></tr><tr><td>Submitter's name</td><td>Kenny Li</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>CloudMinds</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>RCU</td></tr><tr><td>Object Description</td><td>This LWM2M Object includes RCU(Robotic Control Unit) information and the link to RCU APPs.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=1651e846-7802-4b70-9774-59909d8bdefb_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/1651e846-7802-4b70-9774-59909d8bdefb_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1651e846-7802-4b70-9774-59909d8bdefb_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
See Issue https://github.com/OpenMobileAlliance/lwm2m-registry/issues/272
Object submission grouped under this submission

Issue Closed
