### ISSUE TITLE
[CloudMinds] Multiple Object submission 10315 - 10366

### ISSUE THREAD

**Issue by Kenny-SZ** [OpenMobileAlliance/lwm2m-registry#272]
## Registration Information ##
Our company operates smart robots for people, currently we build and operate an open end-to-end cloud robot system, and offer it as a service to the world. Now we intend to manage robot using LwM2M protocol, and need to define 52 OMA Objects for our and 3rd party Robots. Website of our company: [https://www.en.cloudminds.com/](url)
 
### 1. Choose the type of registration: ###
  - [x] ```Object```
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | **52 Objects** (10315-10366, 10317/10321/10325 are reserved for configuration of RCU/CCU/Robot)
Name of SDO, Company or individual    | **CloudMinds**
Object Name (as defined in the .xml file) |  **refers to name in the individual object xml files**
Short Object description, to be used in the pubic registry (max 134 characteres) | **refers to name in the individual object xml files**

[cloudminds-models20191104.zip](https://github.com/OpenMobileAlliance/lwm2m-registry/files/3803406/cloudminds-models20191104.zip)

<img width="524" alt="cloudminds-object-overview" src="https://user-images.githubusercontent.com/52695148/68113543-fd043280-ff2e-11e9-9294-db1885d5ae88.png">

**Comment by seanmcilroy29** [comment]
A new branch, `cloudminds`  has been created in the LwM2M registry for the WG to review your objects

**Steps**
 - [ ] Please submit a Pull Request for **each** object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/cloudminds

Steps | Actions
-- | --
1 | Submit Pull Request  for each object against the `cloudminds` branch
2 | Staff validates PR
3 | IPSO Working Group discuss the submitted Object registration
4 | Any issues will require the submitter to update the PR accordingly
5 | Staff validates object again after submitters updates
6 | IPSO Working Group Chair will merge the object
7 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
A new branch, `cloudminds`  has been created in the LwM2M registry for the WG to review your objects

**Steps**
 - [ ] Please submit a Pull Request for **each** object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/cloudminds

Steps | Actions
-- | --
1 | Submit Pull Request  for each object against the `cloudminds` branch
2 | Staff validates PR
3 | IPSO Working Group discuss the submitted Object registration
4 | Any issues will require the submitter to update the PR accordingly
5 | Staff validates object again after submitters updates
6 | IPSO Working Group Chair will merge the object
7 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
CloudMind Object Approved and Merged - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/411

**Comment by jpradocueva** [comment]
Hello, @Kenny-SZ,

We are reaching out to let you know that OMA is planning to merge this [Pull Request #685](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/685/files), which contains editorial changes to the following objects registered by CloudMinds:

- 10334, and
- 10335
Please reply here or let us know via helpdesk@omaorg.org if you have any comments.
Thanks
