### ISSUE TITLE
[IoTerop] MQTT Broker

### ISSUE THREAD

**Issue by dnav** [OpenMobileAlliance/lwm2m-registry#336]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-11-19 16:44:49 UTC</td></tr><tr><td>Submitter's name</td><td>David Navarro</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>IoTerop</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>MQTT Broker</td></tr><tr><td>Object Description</td><td>This LwM2M Object provides the information to connect to an MQTT Broker.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=5b2294ec-567d-4eea-a405-b9bcf4eb31f2_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/5b2294ec-567d-4eea-a405-b9bcf4eb31f2_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=5b2294ec-567d-4eea-a405-b9bcf4eb31f2_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

**Required Object Updates**
- [ ] Object Version 
- [ ] Object ID - 10367
 - [ ] The object URN allocation for this object will be reserved as urn:oma:lwm2m:x:10367

- [ ] Object License does not conform with the Required OMNA submission.
NOTE: OMA at the moment is collaborating with OneData Model (OneDM) to make the Objects more widely available with an agreed BSD 3 license.

**Steps** A new branch, IoTerop has been created in the LwM2M registry for the WG to review your object - Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/IoTerop

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request to the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by dnav** [comment]
Hi Sean,

Regarding the Object ID, would it be possible to keep IDs 18830 and 18831 ? The TCP port reserved for MQTT is 1883. It would make sense that the MQTT related Objects reuse that number. This is just a nice-to-have.

More problematic: the license. A BSD 3-clause license is a no-go for us for business reasons. As these Objects are more DM-related than Data, I'm not sure they are revelant to OneDM.

On a side-note, I could not find any requirement on the license in the OMNA registration documentation (https://github.com/OpenMobileAlliance/lwm2m-registry/wiki/Guidelines and https://www.openmobilealliance.org/documents/whitepapers/OMA-ORG-Guidelines_Creation_Registration_LwM2M_Objects_Resources-V1_0_1-20190115-A.pdf)

Regards,

**Comment by seanmcilroy29** [comment]
@dnav - I've updated the DDF folder to reflect your request
18830 - MQTT Broker
18831 - MQTT Publication

A new entry has been submitted in the wiki https://github.com/OpenMobileAlliance/lwm2m-registry/wiki/Guidelines#objectversion to highlight the License requirement.

The IoTerop branch is now ready for you to submit your Object against - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/IoTerop

**Comment by dnav** [comment]
Hi Sean,

After discussions with our legals, we are able to switch to a BSD license.

I created the PR #355 covering both Objects. Let me know if all issues are addressed.

Regards,

**Comment by seanmcilroy29** [comment]
Object Approved and merged - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/355
