### ISSUE TITLE
[IoTerop]  MQTT Publication

### ISSUE THREAD

**Issue by dnav** [OpenMobileAlliance/lwm2m-registry#337]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-11-19 16:48:24 UTC</td></tr><tr><td>Submitter's name</td><td>David Navarro</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>IoTerop</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>MQTT Publication</td></tr><tr><td>Object Description</td><td>This LwM2M Object is used to configure data reporting over MQTT.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=b76b1388-b849-4fa8-b0e2-68ce346f99fb_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/b76b1388-b849-4fa8-b0e2-68ce346f99fb_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=b76b1388-b849-4fa8-b0e2-68ce346f99fb_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

**Required Object Updates**
- [ ] Object Version 
- [ ] Object ID - 10368
 - [ ] The object URN allocation for this object will be reserved as urn:oma:lwm2m:x:10368

- [ ] Object License does not conform with the Required OMNA submission.
NOTE: OMA at the moment is collaborating with OneData Model (OneDM) to make the Objects more widely available with an agreed BSD 3 license.

**Steps** A new branch, IoTerop has been created in the LwM2M registry for the WG to review your object - Please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/IoTerop

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request to the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by dnav** [comment]
See PR #355

**Comment by seanmcilroy29** [comment]
Object Approved and merged - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/355
