### ISSUE TITLE
OMNA-Registration of Distance

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#36]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-09 00:50:28 UTC</td></tr><tr><td>Submitter's name</td><td>Joaquin Prado</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Please ignore</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Distance</td></tr><tr><td>Object Description</td><td>test please ignore</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=37f95851-7ef1-441a-a244-1237689600f7_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/37f95851-7ef1-441a-a244-1237689600f7_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=37f95851-7ef1-441a-a244-1237689600f7_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
Test
