### ISSUE TITLE
OMNA-Registration of Test Object

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#37]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-09 09:41:27 UTC</td></tr><tr><td>Submitter's name</td><td>Sean Mcilroy</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Test Org</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Test Object</td></tr><tr><td>Object Description</td><td>N/A</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=8ffae207-5ee2-42e1-a4d3-bc309dd9e80b_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/8ffae207-5ee2-42e1-a4d3-bc309dd9e80b_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=8ffae207-5ee2-42e1-a4d3-bc309dd9e80b_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Testing new Registration repo
