### ISSUE TITLE
OMNA-Registration of ActivitySensor

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#38]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-15 11:39:01 UTC</td></tr><tr><td>Submitter's name</td><td>mahsa</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>sarveen</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>ActivitySensor</td></tr><tr><td>Object Description</td><td>hello</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=f4623436-be92-4efd-a4de-84eb4c6cc62d_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/f4623436-be92-4efd-a4de-84eb4c6cc62d_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=f4623436-be92-4efd-a4de-84eb4c6cc62d_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your object registration but there are a number of observations with resource 5700.
 - Miss match with reusable resources on: Type
 - Miss match with reusable resources on: RangeEnumeration
 - Miss match with reusable resources on: Unit
 - No object version

Addition the submitted Object has no License declaration

Please could you review your Object submission ([guidelines](https://wiki.openmobilealliance.org/display/TOOL/Introduction+to+LightweightM2M)) and resolve the identified issues prior to reregistering this object via the [editor tool](http://devtoolkit.openmobilealliance.org/OEditor/Default).
