### ISSUE TITLE
[Units] CloudMinds invalid Units for review

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#385]
Submitted Units to be reviewed

-	Gigabyte – suggested registration  ``gigaB``
-	Mbps (megabits per second) – suggested registration ``Mbps``
-	m/h (meters per hour) 
-	cm (centre metres)

**Comment by cabo** [comment]
The current editor's copy of draft-ietf-core-senml-more-units.md (last change in https://github.com/core-wg/senml-more-units/commit/9f45131b925a98c62e0dc4e76baf5b20071a029c ) uses:

GB
Mbit/s
MB/s
m/h
cm

(I still don't quite get what m/h is being used for — robots that emulate sloths?)

**Comment by jpradocueva** [comment]
PR #390 has been created to update the local file containing additional senml units. This file is used to validate existing objects against units that have been agreed in SenML but not implemented yet. Once the units are implemented in senml the file will be clear of these pending units.

**Comment by seanmcilroy29** [comment]
Units updated in draft-ietf-core-senml-more-units.md - See https://github.com/core-wg/senml-more-units/commit/9f45131b925a98c62e0dc4e76baf5b20071a029c

**Comment by Kenny-SZ** [comment]
> The current editor's copy of draft-ietf-core-senml-more-units.md (last change in [core-wg/senml-more-units@9f45131](https://github.com/core-wg/senml-more-units/commit/9f45131b925a98c62e0dc4e76baf5b20071a029c) ) uses:
> 
> GB
> Mbit/s
> MB/s
> m/h
> cm
> 
> (I still don't quite get what m/h is being used for — robots that emulate sloths?)

Hi Cabo,
     Thanks for your comments and sorry for late reply. We support several types of robots, some of them are really slow(for example: receptionist robot), while some other robots may be faster than it.
But this is a common model, so we perfer to define unit based on the slowest robots.

    If we use km/h, the value will be really small for some types of robots.

B.R.
Kenny
