### ISSUE TITLE
[Schréder Hyperion] RFID 10370

### ISSUE THREAD

**Issue by tmms-schreder** [OpenMobileAlliance/lwm2m-registry#399]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2020-01-06 18:23:21 UTC</td></tr><tr><td>Submitter's name</td><td>Tiago Silva</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Schréder Hyperion</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>RFID</td></tr><tr><td>Object Description</td><td>Object to allow a LWM2M server to retrieve and store information in an RFID tag/device in range of the LWM2M host.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=03ae0bef-0193-41c7-912e-585938ce7191_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/03ae0bef-0193-41c7-912e-585938ce7191_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=03ae0bef-0193-41c7-912e-585938ce7191_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Thank you for your registration.

**Required Object Updates**
- [ ] Object ID - 10370
- [ ] The object URN allocation for this object will be reserved as urn:oma:lwm2m:x:10370
- [ ] Object License has been submitted under the copyright of ATT and does not conform with the Required OMNA submission.  OMA at the moment is collaborating with OneData Model (OneDM) to make the Objects more widely available with an agreed BSD 3 license, so it is suggested to apply this license with the copyright updated with ``Copyright (c) 2020 Schreder Hyperion.``  See - https://devtoolkit.openmobilealliance.org/OEditor/License and select BSD-3 Clause 

Validated - Well formed with no Editor validator errors

**Steps** A new branch, ``Schreder Hyperion`` has been created in the [LwM2M registry](https://github.com/OpenMobileAlliance/lwm2m-registry) for the WG to review your object - Please submit a Pull Request with the content of your object **against** the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Schr%C3%A9der-Hyperion

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request against the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by tmms-schreder** [comment]
@seanmcilroy29 would you be so kind to provide me with the necessary permissions to be able to upload the requested changes?

**Comment by seanmcilroy29** [comment]
Submitter requests to withdraw the Object for registration
