### ISSUE TITLE
IPSO sensor object average value

### ISSUE THREAD

**Issue by dirtyha** [OpenMobileAlliance/lwm2m-registry#41]
I work for a sensor manufacturer for environmental monitoring. Generally speaking I like what IPSO sensor objects have to offer. What we would like to see in sensor objects are harmonized resources for 1) average value (read) and 2) statistical period (read/write). Averaging is business as usual in weather station sensors, which are able to report current, min, max and averaged measurement values. For example, we use IPSO Rate object /3346 for reporting wind speed. Wind speed needs to reported as speed now, speed in gust (max) and standard 10 minute rolling average wind speed. Currently IPSO sensors already have min and max statistical values, which is nice, but not enough because there is no information about statistical period and no place for averaged value.

**Comment by mkgillmore** [comment]
@dirtyha Thanks for the comment,  are you proposing a new object/resource that can do the average.  Would a re-usable resource that allowed for average, statistical period, etc.

**Comment by dirtyha** [comment]
This issue is related to issue #40 that I created. Maybe they could be combined, but at the time I thought they could be separate.

Perhaps there could be a separate object to describe sensor meta data and IPSO SO could then have a object link type resource pointing to this object. The meta data object could be sensor manufacturer specific custom object and it could re-use existing or new re-usable resources.

**Comment by dirtyha** [comment]
We have solved this issue by creating a new object instance for averaged measurement.
