### ISSUE TITLE
Which is the recommended License

### ISSUE THREAD

**Issue by jaimejim** [OpenMobileAlliance/lwm2m-registry#417]
The repository has at the moment Objects that use either Apache 2 License or BSD-3 Clause License. Is it there any restriction or recommendation from DMSE or IPSO WG?

https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)
https://tldrlegal.com/license/bsd-3-clause-license-(revised)

**Comment by seanmcilroy29** [comment]
BSD-3 Clause License is the recommended license for submitted Objects as this is in line with OneDM requirements

**Comment by jpradocueva** [comment]
The LwM2M Editor has been aligned with the BSD-3 software license policy. 
https://devtoolkit.openmobilealliance.org/OEditor/License

**Comment by jaimejim** [comment]
Okidoki, thanks!
