### ISSUE TITLE
[UNCLEAR ATM] New "LTE-MTC Band Config" and "CoAP Config" Objects

### ISSUE THREAD

**Issue by jaimejim** [OpenMobileAlliance/lwm2m-registry#418]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [x] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] IPSO or DM
  - [ ] 3rd party Standards or Alliances
  - [ ] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 2 Objects and their resources. The current OIDs and RIDs are temporary, please assign the correct numbers. 
Name of SDO, Company or individual    | Ericsson
Object Name (as defined in the .xml file) |  "CoAP Config" , "LTE-MTC Band Config"
Short Object description, to be used in the pubic registry (max 134 characteres) | CoAP Config: This object is used to configure the CoAP transmission parameters (RFC7252) and other parameters that affect CoAP transmission. LTE-MTC Band Config: This object is used to configure the cellular band used by the device as well as to change the band. It is intended to be used on LTE bands, as in NB-IoT and LTE Cat M1 frequency bands.

**Comment by jpradocueva** [comment]
@jaimejim in addition to assign 2 ObjectsIDs how many Reusable Resources do you want to reserve too?

**Comment by jaimejim** [comment]
We decided in IPSO not to use reusable resources on these.

_I believe it is 14 of them. I am also reusing Resources with 48 and 5750. It might be that some of the ones I am registering are already there, in which case I'd be happy to reuse._

**Comment by jpradocueva** [comment]
The discussion of these objects have been moved to an internal IPSO WG repository. https://github.com/OpenMobileAlliance/ipso-wg

**Comment by jpradocueva** [comment]
@jaimejim this issue can be closed.

**Comment by mkgillmore** [comment]
See https://etherpad.openmobilealliance.org/p/IPSO_CC_26_Mar_2020  for update
