### ISSUE TITLE
Unifying "Application Type" RR descriptions

### ISSUE THREAD

**Issue by akeranen** [OpenMobileAlliance/lwm2m-registry#419]
Different objects have different description for the Application Type (5750) re-usable resource. These should be unified, for example like this: https://github.com/akeranen/lwm2m-registry/commit/88257165bd9b96178b032a31bef10819a9374027

**Comment by jpradocueva** [comment]
The LwM2M Editor Tool was updated a while ago to remove the constrain of keeping RR description frozen. This seems to be the main root of the current issue. We are in the process of bringing back the functionality to freeze again the RR description.

**Comment by mkgillmore** [comment]
Addressed by the overall RR pull request #456 merged today 5/14/2020
