### ISSUE TITLE
RR description errors

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#425]
## Validation of Reusable Resource Descriptions.
The LwM2M Editor tool now validates the Reusable Resource (RR) description inside of the Objects against the RR description in the Common.xml file. This file contains the RR registered in OMNA.

The tool has found over 300 errors with the descriptions:

Error | Time | Description | ObjectID and/or ResourceID
-- | -- | -- | --
465 |   | Description is different | 20:4013
465 |   | Description is different | 3200:5750
465 |   | Description is different | 3200:5751
465 |   | Description is different | 3201:5750
465 |   | Description is different | 3202:5601
465 |   | Description is different | 3202:5602
465 |   | Description is different | 3202:5603
465 |   | Description is different | 3202:5604
465 |   | Description is different | 3202:5750
465 |   | Description is different | 3202:5751
465 |   | Description is different | 3202:5605
465 |   | Description is different | 3203:5650
465 |   | Description is different | 3203:5750
465 |   | Description is different | 3203:5603
465 |   | Description is different | 3203:5604
465 |   | Description is different | 3300:5700
465 |   | Description is different | 3300:5601
465 |   | Description is different | 3300:5602
465 |   | Description is different | 3300:5603
465 |   | Description is different | 3300:5604
465 |   | Description is different | 3300:5750
465 |   | Description is different | 3300:5751
465 |   | Description is different | 3300:5605
465 |   | Description is different | 3301:5700
465 |   | Description is different | 3301:5601
465 |   | Description is different | 3301:5602
465 |   | Description is different | 3301:5603
465 |   | Description is different | 3301:5604
465 |   | Description is different | 3301:5605
465 |   | Description is different | 3302:5500
465 |   | Description is different | 3302:5505
465 |   | Description is different | 3302:5751
465 |   | Description is different | 3302:5903
465 |   | Description is different | 3302:5904
465 |   | Description is different | 3303:5700
465 |   | Description is different | 3303:5601
465 |   | Description is different | 3303:5602
465 |   | Description is different | 3303:5603
465 |   | Description is different | 3303:5604
465 |   | Description is different | 3303:5605
465 |   | Description is different | 3304:5700
465 |   | Description is different | 3304:5601
465 |   | Description is different | 3304:5602
465 |   | Description is different | 3304:5603
465 |   | Description is different | 3304:5604
465 |   | Description is different | 3304:5605
465 |   | Description is different | 3305:5800
465 |   | Description is different | 3305:5801
465 |   | Description is different | 3305:5802
465 |   | Description is different | 3305:5803
465 |   | Description is different | 3305:5804
465 |   | Description is different | 3305:5805
465 |   | Description is different | 3305:5810
465 |   | Description is different | 3305:5811
465 |   | Description is different | 3305:5812
465 |   | Description is different | 3305:5813
465 |   | Description is different | 3305:5814
465 |   | Description is different | 3305:5815
465 |   | Description is different | 3305:5821
465 |   | Description is different | 3305:5822
465 |   | Description is different | 3305:5605
465 |   | Description is different | 3306:5852
465 |   | Description is different | 3306:5853
465 |   | Description is different | 3306:5750
465 |   | Description is different | 3308:5900
465 |   | Description is different | 3308:5706
465 |   | Description is different | 3308:5750
465 |   | Description is different | 3311:5852
465 |   | Description is different | 3311:5805
465 |   | Description is different | 3311:5820
465 |   | Description is different | 3311:5706
465 |   | Description is different | 3311:5750
465 |   | Description is different | 3312:5851
465 |   | Description is different | 3312:5852
465 |   | Description is different | 3312:5805
465 |   | Description is different | 3312:5820
465 |   | Description is different | 3312:5750
465 |   | Description is different | 3313:5702
465 |   | Description is different | 3313:5703
465 |   | Description is different | 3313:5704
465 |   | Description is different | 3313:5603
465 |   | Description is different | 3313:5604
465 |   | Description is different | 3314:5702
465 |   | Description is different | 3314:5703
465 |   | Description is different | 3314:5704
465 |   | Description is different | 3315:5700
465 |   | Description is different | 3315:5601
465 |   | Description is different | 3315:5602
465 |   | Description is different | 3315:5603
465 |   | Description is different | 3315:5604
465 |   | Description is different | 3315:5605
465 |   | Description is different | 3316:5700
465 |   | Description is different | 3316:5601
465 |   | Description is different | 3316:5602
465 |   | Description is different | 3316:5603
465 |   | Description is different | 3316:5604
465 |   | Description is different | 3316:5605
465 |   | Description is different | 3316:5821
465 |   | Description is different | 3316:5750
465 |   | Description is different | 3317:5700
465 |   | Description is different | 3317:5601
465 |   | Description is different | 3317:5602
465 |   | Description is different | 3317:5603
465 |   | Description is different | 3317:5604
465 |   | Description is different | 3317:5605
465 |   | Description is different | 3317:5821
465 |   | Description is different | 3317:5750
465 |   | Description is different | 3318:5700
465 |   | Description is different | 3318:5601
465 |   | Description is different | 3318:5602
465 |   | Description is different | 3318:5603
465 |   | Description is different | 3318:5604
465 |   | Description is different | 3318:5605
465 |   | Description is different | 3318:5821
465 |   | Description is different | 3318:5750
465 |   | Description is different | 3319:5700
465 |   | Description is different | 3319:5601
465 |   | Description is different | 3319:5602
465 |   | Description is different | 3319:5603
465 |   | Description is different | 3319:5604
465 |   | Description is different | 3319:5605
465 |   | Description is different | 3319:5821
465 |   | Description is different | 3319:5750
465 |   | Description is different | 3320:5700
465 |   | Description is different | 3320:5601
465 |   | Description is different | 3320:5602
465 |   | Description is different | 3320:5603
465 |   | Description is different | 3320:5604
465 |   | Description is different | 3320:5605
465 |   | Description is different | 3320:5821
465 |   | Description is different | 3320:5750
465 |   | Description is different | 3321:5700
465 |   | Description is different | 3321:5601
465 |   | Description is different | 3321:5602
465 |   | Description is different | 3321:5603
465 |   | Description is different | 3321:5604
465 |   | Description is different | 3321:5605
465 |   | Description is different | 3321:5821
465 |   | Description is different | 3321:5750
465 |   | Description is different | 3322:5700
465 |   | Description is different | 3322:5601
465 |   | Description is different | 3322:5602
465 |   | Description is different | 3322:5603
465 |   | Description is different | 3322:5604
465 |   | Description is different | 3322:5605
465 |   | Description is different | 3322:5821
465 |   | Description is different | 3322:5750
465 |   | Description is different | 3323:5700
465 |   | Description is different | 3323:5601
465 |   | Description is different | 3323:5602
465 |   | Description is different | 3323:5603
465 |   | Description is different | 3323:5604
465 |   | Description is different | 3323:5605
465 |   | Description is different | 3323:5821
465 |   | Description is different | 3323:5750
465 |   | Description is different | 3324:5700
465 |   | Description is different | 3324:5601
465 |   | Description is different | 3324:5602
465 |   | Description is different | 3324:5603
465 |   | Description is different | 3324:5604
465 |   | Description is different | 3324:5605
465 |   | Description is different | 3324:5821
465 |   | Description is different | 3324:5750
465 |   | Description is different | 3325:5700
465 |   | Description is different | 3325:5601
465 |   | Description is different | 3325:5602
465 |   | Description is different | 3325:5603
465 |   | Description is different | 3325:5604
465 |   | Description is different | 3325:5605
465 |   | Description is different | 3325:5821
465 |   | Description is different | 3325:5750
465 |   | Description is different | 3326:5700
465 |   | Description is different | 3326:5601
465 |   | Description is different | 3326:5602
465 |   | Description is different | 3326:5603
465 |   | Description is different | 3326:5604
465 |   | Description is different | 3326:5605
465 |   | Description is different | 3326:5821
465 |   | Description is different | 3326:5750
465 |   | Description is different | 3327:5700
465 |   | Description is different | 3327:5601
465 |   | Description is different | 3327:5602
465 |   | Description is different | 3327:5603
465 |   | Description is different | 3327:5604
465 |   | Description is different | 3327:5605
465 |   | Description is different | 3327:5821
465 |   | Description is different | 3327:5750
465 |   | Description is different | 3328:5700
465 |   | Description is different | 3328:5601
465 |   | Description is different | 3328:5602
465 |   | Description is different | 3328:5603
465 |   | Description is different | 3328:5604
465 |   | Description is different | 3328:5605
465 |   | Description is different | 3328:5821
465 |   | Description is different | 3328:5750
465 |   | Description is different | 3329:5700
465 |   | Description is different | 3329:5601
465 |   | Description is different | 3329:5602
465 |   | Description is different | 3329:5603
465 |   | Description is different | 3329:5604
465 |   | Description is different | 3329:5605
465 |   | Description is different | 3329:5821
465 |   | Description is different | 3329:5750
465 |   | Description is different | 3330:5700
465 |   | Description is different | 3330:5601
465 |   | Description is different | 3330:5602
465 |   | Description is different | 3330:5603
465 |   | Description is different | 3330:5604
465 |   | Description is different | 3330:5605
465 |   | Description is different | 3330:5821
465 |   | Description is different | 3330:5750
465 |   | Description is different | 3331:5700
465 |   | Description is different | 3331:5750
465 |   | Description is different | 3332:5601
465 |   | Description is different | 3332:5602
465 |   | Description is different | 3332:5605
465 |   | Description is different | 3332:5750
465 |   | Description is different | 3333:5750
465 |   | Description is different | 3334:5702
465 |   | Description is different | 3334:5703
465 |   | Description is different | 3334:5704
465 |   | Description is different | 3334:5508
465 |   | Description is different | 3334:5509
465 |   | Description is different | 3334:5510
465 |   | Description is different | 3334:5511
465 |   | Description is different | 3334:5512
465 |   | Description is different | 3334:5513
465 |   | Description is different | 3334:5605
465 |   | Description is different | 3334:5603
465 |   | Description is different | 3334:5604
465 |   | Description is different | 3334:5750
465 |   | Description is different | 3335:5706
465 |   | Description is different | 3335:5750
465 |   | Description is different | 3336:5750
465 |   | Description is different | 3337:5601
465 |   | Description is different | 3337:5602
465 |   | Description is different | 3337:5605
465 |   | Description is different | 3337:5750
465 |   | Description is different | 3338:5548
465 |   | Description is different | 3338:5750
465 |   | Description is different | 3339:5548
465 |   | Description is different | 3339:5750
465 |   | Description is different | 3340:5525
465 |   | Description is different | 3340:5501
465 |   | Description is different | 3340:5526
465 |   | Description is different | 3340:5750
465 |   | Description is different | 3341:5548
465 |   | Description is different | 3341:5750
465 |   | Description is different | 3342:5501
465 |   | Description is different | 3342:5852
465 |   | Description is different | 3342:5750
465 |   | Description is different | 3343:5548
465 |   | Description is different | 3343:5852
465 |   | Description is different | 3343:5854
465 |   | Description is different | 3343:5750
465 |   | Description is different | 3344:5750
465 |   | Description is different | 3345:5501
465 |   | Description is different | 3345:5702
465 |   | Description is different | 3345:5703
465 |   | Description is different | 3345:5704
465 |   | Description is different | 3345:5750
465 |   | Description is different | 3346:5700
465 |   | Description is different | 3346:5601
465 |   | Description is different | 3346:5602
465 |   | Description is different | 3346:5603
465 |   | Description is different | 3346:5604
465 |   | Description is different | 3346:5605
465 |   | Description is different | 3346:5821
465 |   | Description is different | 3346:5750
465 |   | Description is different | 3347:5501
465 |   | Description is different | 3347:5750
465 |   | Description is different | 3348:5750
465 |   | Description is different | 3349:5912
465 |   | Description is different | 3349:5750
465 |   | Description is different | 3350:5544
465 |   | Description is different | 3350:5501
465 |   | Description is different | 3350:5750
465 |   | Description is different | 3353:6033
465 |   | Description is different | 3359:6033
465 |   | Description is different | 3365:6038
465 |   | Description is different | 3375:6034
465 |   | Description is different | 3378:6037
465 |   | Description is different | 3394:5500
465 |   | Description is different | 3394:5903
465 |   | Description is different | 3394:5904
465 |   | Description is different | 3396:5850
465 |   | Description is different | 3397:5850
465 |   | Description is different | 3399:5850
465 |   | Description is different | 3401:5502
465 |   | Description is different | 3401:5503
465 |   | Description is different | 10241:5905
465 |   | Description is different | 10241:5906
465 |   | Description is different | 10241:5908
465 |   | Description is different | 10254:5601
465 |   | Description is different | 10254:5602
465 |   | Description is different | 10254:5603
465 |   | Description is different | 10254:5604
465 |   | Description is different | 10254:5605
465 |   | Description is different | 10254:5750
465 |   | Description is different | 10257:5800
465 |   | Description is different | 10257:5802
465 |   | Description is different | 10257:5805
465 |   | Description is different | 10258:5603
465 |   | Description is different | 10258:5604
465 |   | Description is different | 10258:5750
465 |   | Description is different | 10258:5821
465 |   | Description is different | 10300:4000
465 |   | Description is different | 10311:5821
465 |   | Description is different | 10314:5701
465 |   | Description is different | 10314:5750

**Comment by jpradocueva** [comment]
Number of times that the description of the RRID fails validation (one per object).
The baseline of the Common.xml file was taken from the branch: ```RR_Application_Type```. The column PR indicates the PR number that contains changes against the Common.xml file in that branch. Once the Common.xml file is correct, we will apply PRs to the Objects.

RRID Common.xml| Count of Objects | #PR
-- | --  | --
4000 | 1 |
5500 | 2 |
5501 | 5 |
5502 | 1 |
5503 | 1 |
5505 | 1 |
5508 | 1 |
5509 | 1  |
5510 | 1 |
5511 | 1 |
5512 | 1 |
5513 | 1 |
5525 | 1 |
5526 | 1 |
5544 | 1 |
5548 | 4 |
5601 | 25 | #426 
5602 | 25 | #426
5603 | 27 | Correct description in Common.xml of "RR_Application_Type"
5604 | 27 | Correct description in Common.xml of "RR_Application_Type"
5605 | 27 | Correct description in Common.xml of "RR_Application_Type"
5650 | 1 |
5700 | 22 | Correct description in Common.xml of "RR_Application_Type"
5701 | 1 |
5702 | 4 |
5703 | 4 |
5704 | 4 |
5706 | 3 |
5750 | 47 | #426, #437
5751 | 4 | #437
5800 | 2 |
5801 | 1 |
5802 | 2 |
5803 | 1 |
5804 | 1 |
5805 | 4 |
5810 | 1 |
5811 | 1 |
5812 | 1 |
5813 | 1 |
5814 | 1 |
5815 | 1 |
5820 | 2 |
5821 | 19 | Correct description in Common.xml of "RR_Application_Type"
5822 | 1 |
5850 | 3 |
5851 | 1 |
5852 | 5 |
5853 | 1 |
5854 | 1 |
5900 | 1 |
5903 | 2 |
5904 | 2 |
5905 | 13 | Correct description in Common.xml of "RR_Application_Type"
5906 | 13 | Correct description in Common.xml of "RR_Application_Type"
5908 | 1 |
5912 | 1 |
6033 | 2 | #437
6034 | 1 |
6037 | 1 |
6038 | 1 |

**Comment by jpradocueva** [comment]
# Phase 1
## Define a canonic baseline for Common.xml file

### PR Rejected
This means that the content in the Common.xml file is correct as it is defined in "RR_Applicaton_Type"
* approved by IPSO WG, 16th Apr 2020
* repo & branc: [ipso-wg](https://github.com/OpenMobileAlliance/ipso-wg/pulls?q=is%3Apr+is%3Aopen+label%3A%22PR+Rejected%22)
* [#254](https://github.com/OpenMobileAlliance/ipso-wg/pull/254)
* [#253](https://github.com/OpenMobileAlliance/ipso-wg/pull/253)
* [#245](https://github.com/OpenMobileAlliance/ipso-wg/pull/245)
* [#244](https://github.com/OpenMobileAlliance/ipso-wg/pull/244)
* [#241](https://github.com/OpenMobileAlliance/ipso-wg/pull/241)
* [#236](https://github.com/OpenMobileAlliance/ipso-wg/pull/236)
* [#234](https://github.com/OpenMobileAlliance/ipso-wg/pull/234)
* [#232](https://github.com/OpenMobileAlliance/ipso-wg/pull/232)
* [#230](https://github.com/OpenMobileAlliance/ipso-wg/pull/230)
* [#229](https://github.com/OpenMobileAlliance/ipso-wg/pull/229)
* [#228](https://github.com/OpenMobileAlliance/ipso-wg/pull/228)

> These PRs will be now closed and won't be applied to Common.xml in "RR_Application_Type" branch of the "lwm2m-registry".

### PR Approved
* Approved by IPSO WG 16th Apr 2020
This means that the content of these PRs will be applied to the Common.xml file in the [RR_Application_Type](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/RR_Application_Type) branch of the [lwm2m_regitstry](https://github.com/OpenMobileAlliance/lwm2m-registry)

*  [251](https://github.com/OpenMobileAlliance/ipso-wg/pull/251)
*  [221](https://github.com/OpenMobileAlliance/ipso-wg/pull/221)

> These PRs will be now closed without being applied as they were created for analysis only.

**Comment by mkgillmore** [comment]
Group agreed to close 5/14/2020
