### ISSUE TITLE
OMNA-Registration of LwM2M Server

### ISSUE THREAD

**Issue by 4openmobilealliance** [OpenMobileAlliance/lwm2m-registry#435]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2020-04-15 19:47:50 UTC</td></tr><tr><td>Submitter's name</td><td>oma4</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>oma4 ignore</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LwM2M Server</td></tr><tr><td>Object Description</td><td>oma4 please ignore</td></tr><tr><td>Download Object</td><td><a href="https://remote.alnas.xyz:8017/OEditor/MODownloadZip?omna=108ce5c7-403b-4e8d-9749-192c4909d28d_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://remote.alnas.xyz:8017/OEditor/OMNA/108ce5c7-403b-4e8d-9749-192c4909d28d_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://remote.alnas.xyz:8017/OEditor/LWMOView?omna=108ce5c7-403b-4e8d-9749-192c4909d28d_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
close
