### ISSUE TITLE
OMNA-Registration of LwM2M Access Control

### ISSUE THREAD

**Issue by 4openmobilealliance** [OpenMobileAlliance/lwm2m-registry#436]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2020-04-15 19:59:26 UTC</td></tr><tr><td>Submitter's name</td><td>oma4-2-ignore</td></tr><tr><td>Defined By</td><td>Another SDO</td></tr><tr><td>Organization</td><td>oma4 - 2 ignore</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>LwM2M Access Control</td></tr><tr><td>Object Description</td><td>2nd test for oma4</td></tr><tr><td>Download Object</td><td><a href="https://remote.alnas.xyz:8017/OEditor/MODownloadZip?omna=e007d8ab-dd1b-40c1-86be-6d1d2b720889_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://remote.alnas.xyz:8017/OEditor/OMNA/e007d8ab-dd1b-40c1-86be-6d1d2b720889_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://remote.alnas.xyz:8017/OEditor/LWMOView?omna=e007d8ab-dd1b-40c1-86be-6d1d2b720889_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
close as it s part of a test
