### ISSUE TITLE
Which branch reflet the real/published LWM2M registry?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#438]
Hi,

It's not clear to me to know which branch represent the real/published LWM2M registry ?
Maybe the `prod` one ? 

Someone could confirm this ? 

Thx :pray:

**Comment by jpradocueva** [comment]
Yes, `prod` branch contains the final content that it is made public. It was call `prod` to dissuade people from taking the content from GitHub. The content was mirror in an ftp folder.
The group has recently changed that approach so going forward it will the the only place to obtain the set of final approve objects.

**Comment by sbernard31** [comment]
> The group has recently changed that approach so going forward it will the the only place to obtain the set of final approve objects.

You mean the `prod` branch will be the only place ?

**Comment by jpradocueva** [comment]
Yes, the `prod` branch contains the canonical information of the LwM2M Registry approved by the group.
In the near future the [Registry API](https://wiki.openmobilealliance.org/display/TOOL/Registry+API) service, the [LwM2M Registry](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) page and the [LwM2M Editor Tool](https://devtoolkit.openmobilealliance.org/OEditor/Legal?back=default.aspx) will all take the information from there and not from the [profile](http://www.openmobilealliance.org/tech/profiles/) folder.

Remender that the core of the content in the LwM2M Registry is defined in two files, also stored in the repository: 
* DDF.xml, describes the content of the Objects in registry
* Common.xml describes the content of the Reusable Resources in the registry.

These two files drive all the tools and systems and are stored in the repo too.

**Comment by sbernard31** [comment]
Thx a lot for this detailed answer, it's help a lot ! :pray:
