### ISSUE TITLE
[Registry API] Request by LWM2M version of the specification

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#439]
With the [Registry API](https://wiki.openmobilealliance.org/display/TOOL/Registry+API), is there a way to request all objects compatible the a given version of the specification ?

**Comment by jpradocueva** [comment]
Initially it was not defined to provide that information. Let me give it a second though as it may be possible to extract it. I will add the comment here after my research.

**Comment by sbernard31** [comment]
thx :pray:

**Comment by jpradocueva** [comment]
There is a way to do it although may be bit an "unorthodox" method.

The API provides information stored in the DDF.xml. You can see the [Metadata Information](https://wiki.openmobilealliance.org/display/TOOL/Registry+API) below:

![image](https://user-images.githubusercontent.com/3258579/80140487-dda0a680-855c-11ea-8e1b-92c697619461.png)

* [3], `SpecLink` indicates the Technical Specification assigned to the `URN`, [4]. By looking to the version in the URN or in the `Ver` you can know what Objects IDs are allocated to each LwM2M release.
Remember that Object produced by OMA are defined in [1], `Label` under the value "0".

The other way to find out, without using the API, is by taking one version of the specs and checking which Objects were released with it. But I am sure that you were not looking for that answer.

Let me know if this helps. 

>Note: if you need a better API features, I suggest you make a request to this list. I can do the work as long as it is approved by the group.

**Comment by sbernard31** [comment]
> Note: if you need a better API features, I suggest you make a request to this list. I can do the work as long as it is approved by the group.

Could you tell me which list you are talking about ? :pray:

**Comment by jpradocueva** [comment]
Probably the best one is this list as it is control by IPSO WG the owner of the LwM2M Registry.
https://github.com/OpenMobileAlliance/lwm2m-registry/issues

**Comment by sbernard31** [comment]
Ok right, so I'm in the good place. :-)

I'm a [Leshan](https://github.com/eclipse/leshan) maintainer and my needs is to keep my model up to date in Leshan library. Currently we only support LWM2M v1.0 so I would like to be able to request the object version for this version only.

Ideally, I would like to know if the model come from "core" spec too.

Currently models are embedded in the Library but we could also imagine a more dynamic system (mainly for the demo) where the model are downloaded dynamically directly thanks to LWM2M Registry API when a client support it.

Should we keep this issue as **feature request** or should I close this one and create a dedicated one.

Thx again.

**Comment by jpradocueva** [comment]
I suggested to close this one, and open a new Issue with your request.
I will bring to the attention of the IPSO Working Group chair your request and add it to the agenda topics for the group to discuss.
If you are invited to the IPSO WG meeting will you be able to attend and make your request to the group?

**Comment by sbernard31** [comment]
I created a new dedicated issue : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/444

Hoping this is clear enough. If you have more question do not hesitate to ask about our needs.

> If you are invited to the IPSO WG meeting will you be able to attend and make your request to the group?

Thx for the invitation but unfortunately I'm not so comfortable with oral/spoken English so I would prefer to avoid it and keep using asynchronous channel like github.

Thx again for your time :pray:

**Comment by jpradocueva** [comment]
No worries, I will relay your comment to the group. If I need further input I will come back to you.
You can send us emails directly to helpdesk@omaorg.org. I will share with you my own email so you can reach me whenever you need. We should work closer for the good of Leshan/LwM2M specs.

**Comment by sbernard31** [comment]
:+1:
