### ISSUE TITLE
missing `LWM2MVersion` tag in LWM2M_Connectivity_Monitoring-v1_1.xml ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#442]
Maybe not an issue but it seems that : [LWM2M_Connectivity_Monitoring-v1_1.xml](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/LWM2M_Connectivity_Monitoring-v1_1.xml) does not contains the `<LWM2MVersion>1.1</LWM2MVersion>` tag ?

**Comment by jpradocueva** [comment]
@hannestschofenig this issue should be reviewed by the DMSE WG. The version 1.1 of the Connectivity Monitoring is missing the LwM2M Version tag.
![image](https://user-images.githubusercontent.com/3258579/80394852-4b074c80-8867-11ea-999c-a6f9c0c3543a.png)

**Comment by mojanm** [comment]
I believe that to be a mistake. As I recall SignalSNR resource (resource ID 11) was added to Connectivity Monitoring to create v1.1. of the object while developing LwM2M v1.1.0 specifications. I think post LwM2M v1.1 approval, LAC (resource ID 12) was then added to create v1.2 of connectivity monitoring to go into LwM2M v1.1.1?

**Comment by jpradocueva** [comment]
In the schema lwm2m.xsd, the element "LWM2MVersion" was declared as optional, with a minimum occurrence of "0". It was done in this way because the elements "LWM2MVersion" and "ObjectVersion" were introduced a later stage. I have always suggested that these values should be added even if they were considered optional. 
Now, we have the situation where the object was evolving and we forgot to add that element.

We should consider to introduce a rule in the validation, if the object version is greater than "1.0" then we may consider to check that  the "LWM2MVersion" element is present.

**Comment by mojanm** [comment]
That sounds a good plan.
Just need to bear in mind that by doing so objects other than 0-7 and OSCORE that may have evolved without using a new data type will end up having to include LwM2MVersion in their xml which will be set to 0; personally think this to be OK.

**Comment by jpradocueva** [comment]
The group will have to confirm that they want to include this new validation criteria.

**Comment by mkgillmore** [comment]
@hannestschofenig We need to discuss this in the DMSE group meetings

**Comment by sbernard31** [comment]
That was just a question and there is maybe no issue at all :sweat_smile: 

`LWM2M_Connectivity_Monitoring-v1_1.xml` respect the xml schema of LWM2M 1.0 so maybe even if it was modify for LWM2M 1.1, if it is compatible with LWM2M 1.0 it could make sense to let it like this.

This is probably true in a general way. I mean upgrading LWM2MVersion should maybe only be done if new model require features which are not available in previous LWM2M version. :thinking:

**Comment by jpradocueva** [comment]
@hannestschofenig just to confirm from my side. 

At the moment we haven't received any request to update the validation tool with a new error code that indicates if any of these two parameters are missing from an Object:  "LWM2MVersion" or,and "ObjectVersion"

**Comment by mkgillmore** [comment]
Joaquin,

After my soon to be proposed pull request,  yes, objects that do not contain lwm2m_version or object_version should be flagged.

Matt

**Comment by jpradocueva** [comment]
@mkgillmore thanks Matt, in that case. I will prepare the requirements for it. This work can be considered as part of the tool maintenance for which we have a budget. I will notify to IPSO/DMSE the plans for introducing these two new error codes on time for the next meeting.

**Comment by jaimejim** [comment]
@sbernard31  IMO is a small errata introduced unintentionally. I hope it does not break anything.

Formally probably DMSE should discuss and possibly change it retroactively as it is errata introduced unintentionally on the XML.

**Comment by seanmcilroy29** [comment]
Issue resolved - See Final Publication https://github.com/OpenMobileAlliance/lwm2m-registry/pull/587
