### ISSUE TITLE
missing "Communications Characteristics" (17) object  and "Non-Access Stratum (NAS) Configuration"(18) ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#443]
It seems that object 17 was removed ? is it expected ? 

No more result at : http://www.openmobilealliance.org/api/lwm2m/v1/Object?ObjectID=17
No more link in : http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html
Does not exist in this github repository ?

(same for object 18)

**Comment by jpradocueva** [comment]
These objects have not been formally released by OMA yet. 
What you see in the registry is the placeholders for these two objects.
If you want to make an enquire about them, you can raise your question in the issues of the LwM2M for Developers, this list of issues is reviewed by DMSE Working Group who is in charge of the Objects developed by OMA for LwM2M. 
https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues

**Comment by sbernard31** [comment]
OK. 

We have those 2 objects available in Leshan demo, I don't know how this happened :thinking:
But if you say there are not yet released, I will just remove it from demo.

Thx for your help.

**Comment by jpradocueva** [comment]
Yes please remove them. The group has a new objects that they will be available at the next release.
