### ISSUE TITLE
[Registry API Feature Request] Requesting Object by LWM2M version.

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#444]
About the [Registry API](https://wiki.openmobilealliance.org/display/TOOL/Registry+API) : 

I'm a Leshan maintainer and my needs is to keep my model up to date in Leshan library. Currently we only support LWM2M v1.0 so I would like to be able to request the object version for this LWM2M version only.

Currently models are embedded in the Library but we could also imagine a more dynamic system (mainly for the demo) where the model are downloaded dynamically directly thanks to LWM2M Registry API when a client support it. This dynamic feature also need this kind of API.

(All of this is already doable, downloading the DDF.xml file from  this repository, then downloading each model ddf files then filtering using `<LWM2MVersion>` but this would be more elegant to just call a dedicated API)

Ideally, I would also like to filter/know if the model come from "core" spec too. (object 0,1,2,3,4,5,6,7 for LWM2M 1.0, but object 0,1,2,3,4,5,6,7 and **21** for LWM2M 1.1 and so on)

(Currently this is doable by keeping this information in Leshan and requesting directly by object id, but this would be more elegant if this information was available in LWM2M registry) 

(related old discussion : https://github.com/OpenMobileAlliance/lwm2m-registry/issues/439)

**Comment by mkgillmore** [comment]
@jaimejim will attempt to setup a call with @sbernard31 to discuss details about how we can best support this project

**Comment by jaimejim** [comment]
This issue fell through the cracks. 

IMO we could add the feature requested to the Registry API, a query by ```<LWM2MVersion>```. I do not know which WG (IPSO, DMSE) controls/decides on that, but I am definitely OK with it.

FYI @sbernard31 prefers interactions through the issue tracker, so others in DMSE and IPSO could answer here @hannestschofenig and @mkgillmore .

**Comment by hannestschofenig** [comment]
If you want to determine the list of objects defined in the respective LwM2M version, then you need to look at the specification.

If you want to filter all objects where the <LWM2MVersion> element contains a specific version number then you can do this via a script.

The group does not see a need to enhance the functionality of the API at this point in time.

**Comment by mkgillmore** [comment]
@sbernard31 We think this issue can be best resolved by parsing objects for the <LWM2MVersion>1.0</LWM2MVersion> tag on our lwm2m registry in git hub.  We have created a version history folder for this purpose https://github.com/OpenMobileAlliance/lwm2m-registry/tree/prod/version_history

**Comment by sbernard31** [comment]
Too bad :-/
