### ISSUE TITLE
bad resource Type for executable ressource(3) in object 10260 ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#446]
The model object of 10260 seems to be incorrect : 

```xml
<Item ID="3">
    <Name>Unset</Name>
    <Operations>E</Operations>
    <MultipleInstances>Single</MultipleInstances>
    <Mandatory>Mandatory</Mandatory>
    <Type>String</Type>
    <RangeEnumeration>
    </RangeEnumeration>
    <Units>
    </Units>
    <Description><![CDATA[Delete the RDB variable associated with this instance.]]> </Description>
</Item>
```
(see https://github.com/OpenMobileAlliance/lwm2m-registry/blob/test/10260.xml#L81)

Following the specification, I understand that executable resource should have an empty type : `<Type></Type>`

|  Data Type	|  Description |
|---	|---	|
| none|  No specific data type affected to that resource: it exclusively concerns Executable Resource.	|

(source : http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#11-0-Appendix-C-Data-Types-Normative)

**Comment by jpradocueva** [comment]
You are correct. This was detected a while ago and a new object version 2.0 was created. http://www.openmobilealliance.org/tech/profiles/lwm2m/10260-2_0.xml
At that time the group agreed that v1.0 should not be removed but just superseeded.

**Comment by sbernard31** [comment]
I see that 10260-2_0 has change semantically, I mean new resource new type so a new version, it makes sense !

But here this is an invalid model which does not respect the standard to me this should be fixed and  replaced by patched version like `10260-1_0_1.xml` or `10260-v1_0_1.xml` which only removed this `Type` tag issue.

I mean patch version exists for this kind of bug.

**Comment by jpradocueva** [comment]
You have a point. Unfortunately, didn't follow that approach at that time. But it can be done before the repository is updated. They are planning to remove Object version from the file name.

**Comment by sbernard31** [comment]
Just to let you know, if I embed the current version of `10260`, I get this log at **leshan-server-demo** start up : 
```
WARN DDFFileParser - Model for Resource Unset(3) in /models/10260.xml is invalid : an executable resource MUST NOT have a type(STRING)
```
So on my side, I will fix it internally.

(**leshan-server-demo** also embed the v2.0)

**Comment by mkgillmore** [comment]
5/14/2020 Agreed to close

**Comment by sbernard31** [comment]
And so you will provide a fixed version `10260-v1_0_1.xml` in the registry ?
