### ISSUE TITLE
Problem with 3380 Object

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#45]
```This issue was initially reporting in the "ipso-wg" repository: rhttps://github.com/OpenMobileAlliance/ipso-wg/issues/171```

Object 3380 registered by GSMA has failed validation due to Reusable Resource 6038.
The Type value for this Reusable Resource inside of the Object is set to "Boolean" but the same Reusable Resource in OMNA has been defined as "Integer". 

The group needs to decide what is the Object Version to apply here.
According to the TS- Core:
```
“7.2.1 General Policy
…
Object versioning aims at identifying the LwM2M Object modifications which can be categorized in 2 types defined below:
Evolution of type I: representing non-backward-compatible ("breaking") evolutions, namely:
a Resource characteristic (optional vs mandatory, data type, supported operations) is changed in the Object
a mandatory Resource is added to or removed from the Object.
a feature which is only defined by a new LwM2M Enabler, is added to the Object.
Evolution of type II: representing backward-compatible ("non-breaking") evolutions
an optional Resource is added or removed in the Object”
The staff can resolve this problem by creating and registering a new version 2.0 but as this was done by your company, we think that it is better to let you know and you can decide.
```
Is the new Object Version 2.0?

**Comment by jpradocueva** [comment]
To be discussed by the IPSO WG.

**Comment by mkgillmore** [comment]
Group agrees to create a 2.0 version that addresses the issues and to mark the 1.0 version as deprecated

**Comment by jpradocueva** [comment]
See PR #126

**Comment by seanmcilroy29** [comment]
PR https://github.com/OpenMobileAlliance/lwm2m-registry/pull/126 agreed and merged.
Can now be closed

**Comment by jpradocueva** [comment]
Merge branch 3380-2_0 into test branch

**Comment by jpradocueva** [comment]
See PR #126
