### ISSUE TITLE
10260 object - errors

### ISSUE THREAD

**Issue by jpradocueva** [OpenMobileAlliance/lwm2m-registry#46]
The following Object 10260, was updated to version 2.0.
However, the old object is still available and fail validation. See issues below:

Error| Description | Object
-- | --| --
201 | Name is different for same Object ID | 10260
413 | Incorrect Type/Operation combination | 10260:3
201 | Name is different for same Object ID | 10260

Suggestion
``` Remove the Object 10260 version 1.0 from the registry as it causes validation errors ```

**Comment by jpradocueva** [comment]
To be discussed by the IPSO WG. Potentially reach out to NetComm before depreciating.

**Comment by mkgillmore** [comment]
Group agrees 4/18/19 to mark 1.0 version of this object as obsolete and to update the object description in the registry

**Comment by jpradocueva** [comment]
See PR #127
