### ISSUE TITLE
[Registry API] /lwm2m/v1/Object?ObjectVersion=latest not working as expected

### ISSUE THREAD

**Issue by gh-axel-czarniak** [OpenMobileAlliance/lwm2m-registry#472]
Hello,

I'm using the OMA Registry API inside a project and I would like to retreive only the latest version of the XML object. 

An API was made for this kind of need: 
- lwm2m/v1/Object?ObjectVersion=latest 
    Retrieve a JSON file containing all the metadata information with the latest version of the Objects

The problem is that this API does not work as expected. When a XML has two different versions, this returns either the 1.0 version or none of the two versions

For example, there is many object that have two versions including Security, Server and Device. With a call on this API, only the Server XML is present and is in the 1.0 version and not the 1.1.

**Comment by jpradocueva** [comment]
@axelczk Thanks for raising this issue.
I have been able to reproduce the problem. http://www.openmobilealliance.org/api/lwm2m/v1/Object?ObjectVersion=latest

Let be investigate and find a resolution.
I will let you know once it is done.

**Comment by jpradocueva** [comment]
This problem has been resolved now.
 http://www.openmobilealliance.org/api/lwm2m/v1/Object?ObjectVersion=latest
There were an error in the code.
Thanks for raising the issue. If everything is ok on your side, please close the issue.

**Comment by gh-axel-czarniak** [comment]
It's good. Thanks !
