### ISSUE TITLE
OMNA-Registration of CO Detector

### ISSUE THREAD

**Issue by aushah22** [OpenMobileAlliance/lwm2m-registry#485]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2020-06-18 23:01:47 UTC</td></tr><tr><td>Submitter's name</td><td>Abhi Shah</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>CO Detector</td></tr><tr><td>Object Description</td><td>This is an alarm that should be raised if the sensor detects higher CO level</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=d9b19f05-24c9-4550-9feb-fd2e303e8b4f_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/d9b19f05-24c9-4550-9feb-fd2e303e8b4f_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=d9b19f05-24c9-4550-9feb-fd2e303e8b4f_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
This request is superseded by #486
