### ISSUE TITLE
OMNA-Registration of CO Detector

### ISSUE THREAD

**Issue by aushah22** [OpenMobileAlliance/lwm2m-registry#486]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2020-06-18 23:08:39 UTC</td></tr><tr><td>Submitter's name</td><td>Abhi Shah</td></tr><tr><td>Defined By</td><td>OMA Working Group</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>CO Detector</td></tr><tr><td>Object Description</td><td>This is an alarm that should be raised if the sensor detects higher CO level.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=482314f1-c273-4172-bff3-c19bf42e043c_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/482314f1-c273-4172-bff3-c19bf42e043c_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=482314f1-c273-4172-bff3-c19bf42e043c_Object.xml">Load Editor with object</a></td></tr>

**Comment by jpradocueva** [comment]
@aushah22 @asoloway64 This request seems to be repeated in three different areas. Here, #485 and #486. I am closing the last two and we will keep this one open.

The registration process can be seen here [README](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/test/README.md). 
If the intention to register this Object on behalf of your company? If this is the case, we will create a specific branch and send you the details of the next steps.

**Comment by aushah22** [comment]
Hi @jpradocueva ,
We have raised this request on behalf of Qualcomm Technologies Inc.
We are ok with closing request  #485.
#486 is the final one.

Thanks,
Abhi

**Comment by jpradocueva** [comment]
@seanmcilroy29 we need to create a placeholder for a new ObjectID in the "x" range for Qualcomm Technologies Inc. And send the branch to @aushah22 for registration.

**Comment by seanmcilroy29** [comment]
@aushah22 - ObjectID 10371 has been reserved for you in the `x range`.
For your registration please submit a PR with your Object against this branch - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Qualcomm

Steps | Actions | Comments
-- | -- | --
1 | Submit Pull Request against the nominated branch with your object | Staff validates PR
2 | IPSO discuss the submitted Object registration | Submitter to resolve issues raised by IPSO
3 | Staff validates PR | Submitter to resolve any issues
4 | IPSO Chair will merge the Approved object | Staff publish the Object to the LwM2m Registry

**Comment by asoloway64** [comment]
We will also like to reserve another object number for an additional object definition.

Thanks!

**Comment by asoloway64** [comment]
Hi Joaquin,

I created PR#489 Create 10371.xml<https://github.com/OpenMobileAlliance/lwm2m-registry/pull/489> against the qualcomm branch.

If you can let me know when this will be discussed, I can attend that IPSO meeting.

Thanks for the help!

Regards,
Alan

**Comment by seanmcilroy29** [comment]
@asoloway64 - I've reserved ObjectID 10372 for you. Could you use this branch for the submission of this Object?

**Comment by seanmcilroy29** [comment]
Object Approved - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/507
