### ISSUE TITLE
[Sierra Wireless] Object Registration  `DeviceExt` 

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#502]
### 1. Choose the type of registration: ###
  - [X] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [X] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [X] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | Sierra Wireless
Object Name (as defined in the .xml file) |  DeviceExt (but we are open to better proposition)
Short Object description, to be used in the pubic registry (max 134 characteres) | This object extends Device(/3) Object. It mainly provides features allowing better monitor of Reboot and Reset Factory operation.

## Some context :

This contribution is motivated by the issue raised at : https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/280#issuecomment-363483045

A first draft is visible at : https://rentry.co/edzod

**Comment by seanmcilroy29** [comment]
@sbernard31 Thank you for your registration.

**Required Object Updates**
- [ ] Object Version 1.0
- [ ] Object ID - 10371
- [ ] The object URN allocation for this object will be reserved as urn:oma:lwm2m:x:10371
- [ ] Update range enumeration from ``-`` to ``..``

**Steps** A new branch,  ```Sierra Wireless``` has been created in the LwM2M registry for the WG to review your object - Please submit a Pull Request with the content of your object against this featured branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Sierra_Wireless

Steps | Actions
-- | --
1 | Resolve observations
2 | Submit Pull Request to the nominated branch with your object
3 | Staff validates PR
4 | IPSO Working Group discuss the submitted Object registration
5 | Any issues will require the submitter to update the PR accordingly
6 | Staff validates object again after submitters updates
7 | IPSO Working Group Chair will merge the object
8 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by seanmcilroy29** [comment]
@sbernard31 - The feature branch is available for you to submit your Object - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Sierra_Wireless

As a note, the WG meets every Thursday to review submitted Objects.

If you are encountering any problems, please let me know

**Comment by sbernard31** [comment]
@seanmcilroy29, thanks I will try to find time to that before the end of the week. (probably available for new Thursday 23th meeting)

**Comment by sbernard31** [comment]
PR is created : #504.

**Comment by mkgillmore** [comment]
All issues have been resolved as of 9/15/2020
