### ISSUE TITLE
OMNA Reservation

### ISSUE THREAD

**Issue by SvanteAlnas** [OpenMobileAlliance/lwm2m-registry#523]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>Number of Objects</td><td>1</td></tr><tr><td>Number of Reusable Resources</td><td>0</td></tr><tr><td>Submitted by</td><td>SDO</td></tr><tr><td>Organization Name</td><td>TEST PLEASE IGNORE</td></tr><tr><td>Comment</td><td>TEST</td></tr>

**Comment by seanmcilroy29** [comment]
Test reservation
