### ISSUE TITLE
Smart Quotes Object Errors

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#541]
Error | Time | Description | ObjectID and/or ResourceID | Error update
-- | -- | -- | -- | -- 
420 |   | Invalid XML characters | 1:4 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 1:6 | https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 1:8 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 8:0 |  Smart quotes
420 |   | Invalid XML characters | 9:5 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 9:6 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 9:9 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 9:13 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 10:2 |  Star (*) Error
705 |   | Invalid XML characters | 11 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 11:7 |   https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 11:8 |  Hyphen (-) error
420 |   | Invalid XML characters | 12:13 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 12:17 |  Hyphen (-) error
420 |   | Invalid XML characters | 13:6 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 13:7 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 15:3 |  https://github.com/OpenMobileAlliance/DevCapMgmt/pull/31
420 |   | Invalid XML characters | 15:4 |  https://github.com/OpenMobileAlliance/DevCapMgmt/pull/31
420 |   | Invalid XML characters | 15:7 |  https://github.com/OpenMobileAlliance/DevCapMgmt/pull/31
420 |   | Invalid XML characters | 16:3 |  Smart quotes to be removed
420 |   | Invalid XML characters | 27:3 |  | â€“ Character to be removed
420 |   | Invalid XML characters | 2051:2 |  
420 |   | Invalid XML characters | 2053:1 |  
420 |   | Invalid XML characters | 10245:3 |  
420 |   | Invalid XML characters | 10245:4 |  
420 |   | Invalid XML characters | 10245:5 |  
420 |   | Invalid XML characters | 10245:6 |  
420 |   | Invalid XML characters | 10245:11 |  
420 |   | Invalid XML characters | 10245:12 |  
420 |   | Invalid XML characters | 10245:13 |  
420 |   | Invalid XML characters | 10245:15 |  
420 |   | Invalid XML characters | 10245:16 |  
420 |   | Invalid XML characters | 10256:5 |  
700 |   | Invalid XML characters | 10309

**Comment by jmudge** [comment]
Most of the above error messages that I've examined seem to be caused by the smart quote characters. However aren't characters such as &ldquo; (U+201C) valid in a UTF-8 XML CDATA section? If so then no particular action may be required regarding the related error messages, though the smart quotes could perhaps be replaced by ordinary quote " characters when the files are next being updated anyway for other reasons.

**Comment by jpradocueva** [comment]
@jmudge I have created #452 to address some of the errors. Sean will take care of the errors that are part of the "objects-lwm2m". There will be a small number of Objects that we will have to discuss how to take care of.

We need to introduce straight quotes because some parsing tools were having problems to interpret the smart quotes.

Also, I am investigating the error in 10245 and 10309 "-". The tool identifies it also as an error.

**Comment by seanmcilroy29** [comment]
Error | Time | Description | ObjectID and/or ResourceID | Error update
-- | -- | -- | -- | -- 
420 |   | Invalid XML characters | 1:4 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 1:6 | https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 1:8 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 8:0 |  Smart quotes
420 |   | Invalid XML characters | 9:5 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 9:6 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 9:9 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 9:13 |  https://github.com/OpenMobileAlliance/SwMgmt to be updated
420 |   | Invalid XML characters | 10:2 |  Star (*) Error
705 |   | Invalid XML characters | 11 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 11:7 |   https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 11:8 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 12  |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 12:13 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 12:17 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 13:6 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 13:7 |  https://github.com/OpenMobileAlliance/objects-lwm2m/pull/156
420 |   | Invalid XML characters | 15:3 |  https://github.com/OpenMobileAlliance/DevCapMgmt/pull/31
420 |   | Invalid XML characters | 15:4 |  https://github.com/OpenMobileAlliance/DevCapMgmt/pull/31
420 |   | Invalid XML characters | 15:7 |  https://github.com/OpenMobileAlliance/DevCapMgmt/pull/31
420 |   | Invalid XML characters | 16:3 |  Smart quotes to be removed
420 |   | Invalid XML characters | 27:3 |  ` â€“` Character to be removed
420 |   | Invalid XML characters | 2051:2 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 2053:1 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:3 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:4 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:5 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:6 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:11 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:12 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:13 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:15 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10245:16 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
420 |   | Invalid XML characters | 10256:5 |  https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542
700 |   | Invalid XML characters | 10309 | https://github.com/OpenMobileAlliance/lwm2m-registry/pull/542

**Comment by SvanteAlnas** [comment]
I have done some updates in the other thread, see: https://github.com/OpenMobileAlliance/OMA_LWM2M_Editor/issues/240

**Comment by seanmcilroy29** [comment]
Smart Quotes Object Errors removed
