### ISSUE TITLE
Wrong description for location object

### ISSUE THREAD

**Issue by k0d** [OpenMobileAlliance/lwm2m-registry#561]
I might be mistaken, but it seems like the description at the link below is wrong.

https://github.com/OpenMobileAlliance/lwm2m-registry/blob/5f648f79493d00768cdb43abe5aacdf91bd3334f/DDF.xml#L272

**Comment by jpradocueva** [comment]
@k0d  It appears that you are right, and the worrying part is that the validation tool didn't pickup that error. We will have to further investigate how it was possible that the tool didn't raise an error. Thanks for raising the issue!

**Comment by jpradocueva** [comment]
PR #563

**Comment by seanmcilroy29** [comment]
Wrong description for location object resolved and Published - See PR #563
