### ISSUE TITLE
Object 10243, Voltage as type String, should be float

### ISSUE THREAD

**Issue by kdhaka** [OpenMobileAlliance/lwm2m-registry#567]
Single Phase Power Meter Tension (Voltage) type is String. It should be Float:
https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/10243.xml#L97

3 Phase Power Meter Tension type is correct:
https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/10242.xml#L97

**Comment by jpradocueva** [comment]
Prepare a new branch where the DDF will be updated to v1.1 for this object.

**Comment by mojanm** [comment]
@mojanm will submit the necessary PR to create a new version of Single Phase Power Meter object with Tension Resource type changed to float. As Tension is a Mandatory resource, the new version of Object will be 2.0.

**Comment by seanmcilroy29** [comment]
Object updated - See https://github.com/OpenMobileAlliance/lwm2m-registry/pull/582
