### ISSUE TITLE
Typo in Actuation Object

### ISSUE THREAD

**Issue by akeranen** [OpenMobileAlliance/lwm2m-registry#577]
Resource 5853 ("Muti-state Output") of Actuation (3306) Object should be "Multi-state Output"

https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/3306.xml#L76

**Comment by jpradocueva** [comment]
Maintainer to create a Pull Request to be reviewed next week.

**Comment by seanmcilroy29** [comment]
Issue resolved - see PR https://github.com/OpenMobileAlliance/lwm2m-registry/pull/584
