### ISSUE TITLE
OMNA-Registration of ShareParkingLock

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#58]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-24 05:06:17 UTC</td></tr><tr><td>Submitter's name</td><td>DengJia</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>HuaXiangIOT Technologies Co., Ltd. </td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>ShareParkingLock</td></tr><tr><td>Object Description</td><td>This LwM2M Object provides the keying material of our technology product——ShareParkingLock.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=1e158f3d-1081-404f-b56b-32e6736a2479_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/1e158f3d-1081-404f-b56b-32e6736a2479_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=1e158f3d-1081-404f-b56b-32e6736a2479_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
@DengJia - Thankyou for your registration.
There are a couple of observations:
- [ ] The object ID allocation for this object will be reserved as ```10310```
- [ ] The object URN allocation for this object will be reserved as ```oma:lwm2m:x:10310```
These updates will be applied to the xml object file once the IPSO WG has completed its review and agreed on the publication of this object.

**Comment by seanmcilroy29** [comment]
Object has been updated in issue #60
