### ISSUE TITLE
Duplicate Timestamp resource in Location object description (version 1.1)

### ISSUE THREAD

**Issue by rlubos** [OpenMobileAlliance/lwm2m-registry#583]
The Timestamp resource (5518) is duplicated in the description of the Location object (3336) in version 1.1. It was already present in object version 1.0 and now there are two entries for the resource, first at [line 96](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/3336.xml#L96) and then at [line 116](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/3336.xml#L116).

Also, the indentation of the resources added in object version 1.1 seems to be one tab more compared to the other resources, not sure if that's intended?

**Comment by sbernard31** [comment]
I confirm this :

Leshan raises : 
```
Object 3336 in /models/3336.xml contains at least 2 resources with same id 5518.
```

**Comment by mkgillmore** [comment]
We confirm this issue and will attempt to address ASAP
