### ISSUE TITLE
[question] Which version of model should I use ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#585]
Hi,

**Some context :**   
  In Leshan we need LWM2M models to run our code and so we embed core models in our library.
  I call "core" models all objects defines in LWM2M core specification. (e.g. for LWM2M v1.1 : 0,1,2,3,4,5,6,7, 21)
  
  Leshan v1.x (released) implements LWM2M v1.0.x
  Leshan v2.x (in development)  implements LWM2M v1.1.x
  
**The question :**  
 I would like to know which version do you advice to embed (knowing that user is able to add more models manually)
  
 1. Should we embed all version of the object until the one defined in the specification ? 
 2. Should we embed all the version compatible with the targeted version of the specification ? 
 
 Eg. for object 3 and Leshan v2.0 (LWM2M v1.1.x) : 
-  With 1.) we embed only v1.0 and v1.1 (as v1.1 is the last one defined in LWM2M v1.1.x)
 - With 2.) we embed v1.0 v1.1 and v1.2 (all compatible with LWM2M v1.1.x).

It's hard to me to know which one is the better choice ? Any advises ?
I guess maybe 1) is a more predictive way to know what you should be found in Leshan library :thinking: 

**Bonus question :**   
 Does object versioning respect a kind of semantic version ? meaning that incrementing minor means only add new features and so backward compatibility ?

**Comment by sbernard31** [comment]
About the Bonus question, the answer seems to be in [core§7.2.2- Object Version Format.](http://www.openmobilealliance.org/release/LightweightM2M/V1_1_1-20190617-A/HTML-Version/OMA-TS-LightweightM2M_Core-V1_1_1-20190617-A.html#7-2-2-0-722-Object-Version-format) (from https://github.com/eclipse/leshan/issues/972#issuecomment-777632020)

**Comment by mkgillmore** [comment]
@sbernard31 Simon,
All possible versions of the objects are here:
https://github.com/OpenMobileAlliance/lwm2m-registry/tree/prod/version_history

If a Core Object version does not correspond to version contained in the LwM2M Enabler release supported by the
LwM2M Client, the Object Version MUST be provided by the LwM2M Client to the LwM2M Server.  The enabler specifications have examples of registration setting what version of the object is supported.  See 7.2.3. Object Definition and Object Version Usage from the lwm2m_1_2_core specification.
