### ISSUE TITLE
OMNA-Registration of ShareParkingLock

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#59]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-24 06:25:26 UTC</td></tr><tr><td>Submitter's name</td><td>DengJia</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>HuaXiangIOT Technologies Co., Ltd. </td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>ShareParkingLock</td></tr><tr><td>Object Description</td><td>This LwM2M Object provides the keying material of our technology product——ShareParkingLock.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=173bc7dd-bc41-43d3-b4e4-0b5449930063_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/173bc7dd-bc41-43d3-b4e4-0b5449930063_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=173bc7dd-bc41-43d3-b4e4-0b5449930063_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
This object has been updated in issue #60
