### ISSUE TITLE
[HuaXiangIOT] - OMNA-Registration of ShareParkingLock - 10310

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#60]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-24 08:55:55 UTC</td></tr><tr><td>Submitter's name</td><td>DengJia</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>HuaXiangIOT Technologies Co., Ltd. </td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>ShareParkingLock</td></tr><tr><td>Object Description</td><td>This LwM2M Object provides the keying material of our technology product——ShareParkingLock.</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=e6facc28-7329-483e-807d-57fa971a3664_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/e6facc28-7329-483e-807d-57fa971a3664_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=e6facc28-7329-483e-807d-57fa971a3664_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
@dengjia - Thankyou for your registration.
There are a couple of observations:

- [ ] The object ID allocation for this object will be reserved as ```10310```
- [ ] The object URN allocation for this object will be reserved as ```oma:lwm2m:x:10310```
These updates will be applied to the xml object file once the IPSO WG has completed its review and agreed on the publication of this object.

**Comment by jpradocueva** [comment]
@dengjia further comments that need to be addressed before accepting this submission:

- [ ] The legal disclaimer doesn't comply with any of the disclaimers suggested in the LwM2M Editor tool. The impact of that is that this Object may not be widely used. We suggest to use one of the licenses provided in the tool, please DO NOT USE OMA license; this license is dedicated to OMA members only.
- [ ] In the URN ```oma:lwm2m:x:22222:1.0``` there is not need to define the version "1.0". The version is added only when the object version is updated due to same changes to e.g. version "1.1".

**Comment by seanmcilroy29** [comment]
@dengjia - A place holder for this Object has been added to the HuaXiang.
Please can you 
- [ ] review the submitted comments highlighted above and update the object accordingly
- [ ] submit your object to https://github.com/OpenMobileAlliance/lwm2m-registry/tree/HuaXiang branch
- [ ] Once you've submitted the object an final validation will conducted prior to the Working Group providing comments

**Comment by seanmcilroy29** [comment]
The content of this file has been moved to 10309.xml object see issue #76
