### ISSUE TITLE
Choosing first IPSO models for OneDM convergence process

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#600]
Choosing the first IPSO models for OneDM convergence process

The OneDM/SDF work has now progressed to a state where we have "implementation stable" specification of the semantic description format (SDF) [1] and OneDM liaison group is now starting to implement the model converging/consolidation process (to end up with common models across ecosystems). We should select now a couple of IPSO models for the first trial of the consolidation process. 

**Question to the IPSO WG: what models of the starter/expansion packs should we propose for the first trial?**

**Comment by mkgillmore** [comment]
3303 has been made a version available.  

SDF draft https://datatracker.ietf.org/doc/html/draft-ietf-asdf-sdf-05

We will continue to examine SDF and consider over time changes to their models.

@jaimejim @mkgillmore Lets select a good set of objects

**Comment by akeranen** [comment]
We were planning to start with the [Voltage](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-voltage.sdf.json) and [Current](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-current.sdf.json) objects but we'll take another look at the current design pattern where the unit is a resource (as that can cause interop problems as discussed in our March meeting). For a variation of the sensor pattern, the [Direction](https://github.com/one-data-model/playground/blob/master/sdfObject/sdfobject-direction.sdf.json) object is another good candidate for consideration, and it doesn't have the unit problem.

I think we can close this issue for now.
