### ISSUE TITLE
Indentation/formatting issues in object definitions

### ISSUE THREAD

**Issue by akeranen** [OpenMobileAlliance/lwm2m-registry#602]
This is purely editorial issue. Some object XML files in the registry use mixed tabs and spaces for indentation. For example, Object 3336 has first 7 resource definitions indented with spaces only but the last 3 with tabs. I would recommend to use only spaces.

**Comment by mkgillmore** [comment]
@akeranen How many objects are inconsistent?  Perhaps we should try using tidyxml

**Comment by akeranen** [comment]
Good question, I haven’t done any thorough study. But yes, using consistent style fixer like tidyxml would make sense.

**Comment by hannestschofenig** [comment]
Matt has the AI to look at the issue.

**Comment by mkgillmore** [comment]
Group agrees that if indentation changes occur,  the objects do not need to have revisions.

**Comment by hannestschofenig** [comment]
https://github.com/OpenMobileAlliance/lwm2m-registry/edit/prod/3336.xml still has tabs.
