### ISSUE TITLE
[question] Why firmware object is single instance?

### ISSUE THREAD

**Issue by SeppoTakalo** [OpenMobileAlliance/lwm2m-registry#615]
I would like to raise a question regarding [Firmware update object 5](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/5.xml).

Why it is limited to single instance?

I'm working on embedded IoT device with multiple firmware images and looking for solution to update them all. If the given object id 5 would allow multiple instances, I would be able to specify for example that
5/0  would be bootloader
5/1 would be application firmware
5/2 would be modem firmware
 
Now when this is allowed, you could check each of the versions separately. For example:
```
5/0/6 = "BOOTLOADER"
5/0/7 = "v1.7.0"

5/1/6 = "application"
5/1/7 = "<git hash or version>"

5/2/6 = "modem"
5/2/7 = "1.3.0"
```

On the side note, I have been made aware that object ID 9 would allow multiple instances, but I can see that it defines uninstall and deactivation/activation as a mandatory resource. This is a requirement that not all embedded devices can implement.

So, would it be possible to modify object 5 to be a multi instance?

**Comment by hannestschofenig** [comment]
The Firmware Update Object should be seen as a delivery mechanism. We agree that having multiple instances of this Object would be nice. This was overlooked when creating the Object for LwM2M 1.0. For your particular use case, the package could contain indication on the recipient of the update. Please have a look at the SUIT manifest https://datatracker.ietf.org/doc/draft-ietf-suit-manifest/.

**Comment by SeppoTakalo** [comment]
Hi @hannestschofenig and thank you for your answer.

It is true that delivered package could contain metadata required to identify which target it is meant for. However, in my opinion, this feels a bit hacky for two reasons. Firstly, the firmware object exposes version string, but if you can deliver multiple images, which version this is, or should it be a combined string of all version numbers? Secondly, usually manufacturer or the update software already dictates the binary format, and might already contain verification of correct image. Feels unnecessary to pack signed image to another package which then should be processed and unpacked on limited resource device. Sometimes the components that we could update, have nothing in common. For example MCUboot could be used for application image, so it dictates which verification and signing is used for application. Then modem manufacturer have their own binary format and own signing mechanism, which it verifies.

For those two reasons, I would strongly prefer the simplicity of firmware object allowing me to transfer binaries in native format and if multiple instances would be allowed I could expose versions of each components as well.

I'm sorry I'm not aware of correct process, but what would it take to propose a change that Firmware Update object would be marked as multiple instance? Am I right on assuming that object definitions can be updated without touching the LwM2M specification?
