### ISSUE TITLE
OMNA-Registration of Name

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#62]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-25 08:54:05 UTC</td></tr><tr><td>Submitter's name</td><td>Sean Mcilroy</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Test Org</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Name</td></tr><tr><td>Object Description</td><td>Test org</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=91ec410b-16a0-47c3-85ef-832249894b6f_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/91ec410b-16a0-47c3-85ef-832249894b6f_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=91ec410b-16a0-47c3-85ef-832249894b6f_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Object submitted to conduct a test
