### ISSUE TITLE
Adding a new Test Object Definition

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#623]
In Leshan we have kind of Test Object Model which all kind of resource which allow us to do/write some units tests.

Recently a Leshan user opened an issue and I realize that it also create a kind of object like this on its own.  (https://github.com/eclipse/leshan/issues/1024#issuecomment-863570941)

Should we register a new Object like this which could help for testing for everybody ? 

In case this is not clear those object could have : 
- 1 execute resource
- 1 RW single instance resource of  each type
- 1 RW multi instance  resource of  each type

**Comment by sbernard31** [comment]
@bocajim, @mlasch, @qleisan, @tuve, @rettichschnidi   what do you think ?

**Comment by bocajim** [comment]
Personally (and as the creator of this particular object), I think it would be very helpful if we had a standard test object we encourage all clients/servers to be able to use.  As we add more encodings to the spec the number of permutations that need to be tested is difficult to test.  Having consistency makes test automation for interoperability much easier, as well as reduces development time validating all of the various encodings.

I've had to have team members implement similar objects in numerous clients and servers to test basic functionality which is a drag on actually developing an application.

And I agree, we need to add an exec so we have all resource types.

I would recommend we move away from my 666 object ID though. :)

**Comment by jpradocueva** [comment]
With regards to Object Ranges.
Please note that in the LwM2M Registry there is a section called ["ObjectID Classes"](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html), which defines the available Object ranges.

I see two possible options, to use the "reserved" range or the "ext-label" range. The IPSO/DMSE WG should be able to comment on which range is more suitable. @mkgillmore, @hannestschofenig, any comments?

**Comment by sbernard31** [comment]
@bocajim would you be OK to register this object at OMA, providing a PR to this repository ?
If the process is unchanged since last time, I did that you should first : 
- open a ticket (E.g. https://github.com/OpenMobileAlliance/lwm2m-registry/issues/502)
- then create a PR (E.g. https://github.com/OpenMobileAlliance/lwm2m-registry/pull/504)

@mkgillmore, @hannestschofenig any advice about the ID range  which should be chosen?

**Comment by bocajim** [comment]
Yeah, i can do that, we just got our OMA membership finalized.

Jim

**Comment by sbernard31** [comment]
@mkgillmore, @hannestschofenig  any comments ?

I guess it just missing the ID range to go forward on this topic ?

**Comment by seanmcilroy29** [comment]
@mkgillmore, @hannestschofenig 
Can you specify which ObjectID class this will be allocated to and I'll begin the registration process?

**Comment by hannestschofenig** [comment]
Regarding the object id range this object belongs to, I would put it in the  **2048 - 10240 range**. We could say it comes from the Eclipse Foundation (as a source)

FWIW I think this is a very useful object to register.

**Comment by seanmcilroy29** [comment]
ok - I'll reserve the next available ID 3441 under the ext-label, and the Owner will be the Eclipse Foundation

**Comment by sbernard31** [comment]
@bocajim, @fdesbiens is it OK to you to make  the Eclipse Foundation as the Owner of this Object ? It sounds a good idea to me. 

@fdesbiens, just in case you  are not aware of this :   
LWM2M has a registry where some additional device behavior are defined in Object Model file, Those models can be shared between servers and devices to help for interoperability.  See [LwM2M Registry](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html) for more details.

@seanmcilroy29, @jpradocueva,  so the next step is to create an new issue like this  : #502 ?

@bocajim could you open the issue  :pray: ?  (if this is the next step to do)

**Comment by seanmcilroy29** [comment]
@bocajim - Here is the readme file that outlines the process - https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/README.md

Click here to create a [new Issue](https://github.com/OpenMobileAlliance/lwm2m-registry/issues/new) - this'll provide you with a registration template. Once you submit your Issue, I'll reserve your registration and create a new branch for you to submit your PR.

**Comment by bocajim** [comment]
@sbernard31 I'm OK with it going under the Eclipse Foundation.  Also, someone needs to add an executable resource for completeness.

I'm very busy at the moment, so if you want to wait for me, I'll look at this towards the end of summer, otherwise anyone else is more than welcome to submit it.

**Comment by fdesbiens** [comment]
@sbernard31 Given the context you provided, it completely makes sense for the Foundation to be the owner. Our open source projects do not have their own juridical personality. Please let me know if you need anything from me to make this happen.

**Comment by sbernard31** [comment]
> I'm very busy at the moment, so if you want to wait for me, I'll look at this towards the end of summer, otherwise anyone else is more than welcome to submit it.

Thx to let us know that. I have also some task to finished first. I will inform you before to work on this.

**Comment by sbernard31** [comment]
@bocajim, I will begin to work on this.

**Comment by sbernard31** [comment]
I created the issue to start the process : #636

**Comment by mkgillmore** [comment]
Closed to do this work due to the creation of #636

**Comment by jpradocueva** [comment]
@sbernard31 , @mkgillmore I have created a new branch [3442_3443](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/3442_3443) for you to continue the development of the Test Objects for v1.1 and v1.2.

Please upload one pull request per Object or for both Objects. If you upload multiple pull requests to define an object the tool will identify some missing components and you will have multiple errors.
Ping me if you have any questions.

Also, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/3442_3443#readme) file to see how to pass validation. Thanks!
