### ISSUE TITLE
OMNA-Registration of Name

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#63]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-01-25 09:16:00 UTC</td></tr><tr><td>Submitter's name</td><td>Sean Mcilroy</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>hhh</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Name</td></tr><tr><td>Object Description</td><td>gfj</td></tr><tr><td>Download Object</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=a8adcac2-e811-4d27-998a-6c3ccc2d8198_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/OMNA/a8adcac2-e811-4d27-998a-6c3ccc2d8198_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=a8adcac2-e811-4d27-998a-6c3ccc2d8198_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
Object submitted to conduct a test
