### ISSUE TITLE
[AVSystem] Modbus Connection, Modbus Register Cluster

### ISSUE THREAD

**Issue by kFYatek** [OpenMobileAlliance/lwm2m-registry#635]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 2
Name of SDO, Company or individual    | AVSystem
Object Name (as defined in the .xml file) |  Modbus Connection, Modbus Register Cluster
Short Object description, to be used in the pubic registry (max 134 characteres) (Modbus Connection) | This LwM2M Object is used to configure a Modbus protocol connection.
Short Object description, to be used in the pubic registry (max 134 characteres) (Modbus Register Cluster) | This LwM2M Object represents a set of Modbus registers and acts as an interface to read and write their values.

Proposed object definitions can be viewed at https://gist.github.com/kFYatek/2a873a83b1f8d6abb9a6415d9b78ff07. These objects are already used internally at AVSystem, with object IDs 33618 and 33619, as belonging to our bulk reservation. We would like to have them properly, publicly registered; the linked definitions tentatively use IDs 13618 and 13619 but any two (preferably consecutive) Object IDs are acceptable, since a change of pool is required anyway.

**Comment by jpradocueva** [comment]
Due to lack of quorum, DMSE/IPSO postponed the review of this request for the next group meeting, Oct 19th.

**Comment by jpradocueva** [comment]
@kFYatek I have created a new branch https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10374_10375-AVSystem. As you can see the Objects ID for each of the registration is 10374 and 10375, the DDF.xml is updated accordingly but you will need to add the objects in the DDF property.

Please read the [README.md guidelines](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10374_10375-AVSystem#readme) to ensure a smooth validation. Ping me if you have any questions.

**Comment by kFYatek** [comment]
I have created the PR, #646. I hope that I did not do anything wrong.

**Comment by mkgillmore** [comment]
Group agreed to close this issue because the pull request 646 was merged

**Comment by kFYatek** [comment]
Thanks for merging! However, I don't see this on the default branch or in the web-based registry yet. Is this an omission on your side or are there any additional steps that need to be taken?

**Comment by jpradocueva** [comment]
@kFYatek there are additional steps that need to be done by me. I will do it this week.

**Comment by jpradocueva** [comment]
@kFYatek unfortunately, the group is reviewing object 3441 that was already merged into the "dev" branch. Until this review is not completed we cannot publish your two objects 10374 & 10375. Otherwise, we will publish incomplete content in 3441.xml. Please bear with us until this is resolved. Sorry for the inconvinience.

**Comment by kFYatek** [comment]
@jpradocueva That's not a problem. I was just confused about what was happening. Thank you for the information, please take your time.
