### ISSUE TITLE
HVAC IPSO Object not found

### ISSUE THREAD

**Issue by Ramzi04** [OpenMobileAlliance/lwm2m-registry#637]
I am looking for **HVAC** ( Heating, Ventilation, and Air Conditioning) object that is a composed object containing:
1.	Thermostat.
2.	Air Conditioner
3.	Temperature sensor
4.	Humidity sensor
5.	Heater

I looked for the **HVAC** IPSO object in the IPSO object registry [online](http://www.openmobilealliance.org/wp/omna/lwm2m/lwm2mregistry.html).
Unfortunately, I didn't find any trace for it?

Any help ?

**Comment by mkgillmore** [comment]
@Ramzi04  We IPSO have a few questions about what you would like to have.  

1) Are you looking to have 5 objects combined into a single object
2) What functionality are you looking for in each of the items you mentioned

**Comment by Ramzi04** [comment]
Thanks @mkgillmore  for the help.

I am actually an IoT developer and I am trying to create an IoT dataset using IPSO Objects.
One of the specifications in this dataset is to have a, **HVAC** (Heating, Ventilation, and Air Conditioning) data included.
HVAC is composed of :

1. **Thermostat** to manage the temperature.
2. **Air Conditioner** is commanded via Thermostat to , provides cooling.
3. **Temperature sensor** to indicate to the thermostat the temperature of the room.
4. **Humidity sensor** to indicate to the thermostat the humidity inside the room.
5. **Heater** is appliance whose purpose is to generate heat via the thermostat commands.

My question is, is this type of object (HVAC) registered in the IPSO registry? 
Otherwise, how do I add an HVAC object to my IoT dataset?

**Comment by hannestschofenig** [comment]
As mentioned in https://github.com/OpenMobileAlliance/OMA_LwM2M_for_Developers/issues/531 I would not attempt to create an object that describes an HVAC. 

IMHO this will not provide you with any value. 

Instead, I would see the entire IoT device that is being managed as the HVAC. That IoT device happens to have use these 5 objects (and in fact many more, for example, objects related to security, firmware updates, connectivity management, device information reporting, etc.).

**Comment by Ramzi04** [comment]
I appreciate your help @hannestschofenig.
