### ISSUE TITLE
[George Kent (Malaysia) Berhad] Object Registration (Periodic Activity)

### ISSUE THREAD

**Issue by BTE164** [OpenMobileAlliance/lwm2m-registry#640]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | George Kent (Malaysia) Berhad
Object Name (as defined in the .xml file) |  Periodic Activity
Short Object description, to be used in the pubic registry (max 134 characters) | Generic interface to set up periodic activity like hourly sensor reading/load activation and mechanism to retrieve the periodic data.

**Comment by BTE164** [comment]
Any one can create a branch for this?

**Comment by jpradocueva** [comment]
@BTE164 hi Muhammah, as a maintainer of this repository we only can create the branches once the group has reviewed the request. Next Tuesday will be an IPSO/DMSE Working /Group meeting. We will make sure that the group acknowledge this request.

**Comment by BTE164** [comment]
Thanks you @jpradocueva for the reply.

**Comment by jpradocueva** [comment]
Due to lack of quorum, DMSE/IPSO postponed the review of this request for the next group meeting, Oct 19th.

**Comment by jpradocueva** [comment]
@BTE164 I have created a branch [G-10376_10377-G-Kent-Malaysia](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10376_10377-G-Kent-Malaysia) for uploading one PR per each object to register.

As you can see Object ID 10376 correspond to your Object name `Periodic Activity` and Object ID 10377 for `Data Monitoring`

Please read the instructions in the [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10374_10375-AVSystem#readme) to ensure a successful validation.  Ping me if you have any questions.

**Comment by BTE164** [comment]
> @BTE164 I have created a branch [G-10376_10377-G-Kent-Malaysia](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10376_10377-G-Kent-Malaysia) for uploading one PR per each object to register.
> 
> As you can see Object ID 10376 correspond to your Object name `Periodic Activity` and Object ID 10377 for `Data Monitoring`
> 
> Please read the instructions in the [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10374_10375-AVSystem#readme) to ensure a successful validation. Ping me if you have any questions.

**Comment by BTE164** [comment]
@jpradocueva May I know how long do I have to upload the objects? I'm testing the objects with my device and requires a bit more time to fine tune the proposed objects.

**Comment by jpradocueva** [comment]
@BTE164 no worries, as long as you need. We are doing some changes to the way we work with GitHub if this has any impact on your branch I will let you know.

**Comment by jpradocueva** [comment]
See PRs #669 and #668
