### ISSUE TITLE
Add RSSI (6045) as optional resource to Gateway Object (25)

### ISSUE THREAD

**Issue by ahedin25** [OpenMobileAlliance/lwm2m-registry#643]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | Laird Connectivity

**Comment by jpradocueva** [comment]
Due to lack of quorum, DMSE/IPSO postponed the review of this request for the next group meeting, Oct 19th.

**Comment by ahedin25** [comment]
After some review, it is preferred to use an integer for RSSI and have the units as dBm instead of dBW.

**Comment by jpradocueva** [comment]
@ahedin25 The group has agreed. a while ago, that it is not possible to update existing resources. If it is really necessary, then a new Reusable Resource should be created. 
I am also adding here the chair of the IPSO Working Group, Matt ( @mkgillmore ) in case he would like to provide some additional comments.
