### ISSUE TITLE
Bad schema for object 502, 503, 504, 505 ?

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#656]
Leshan Model validator detects error for object 502, 503, 504, 505.

> LWM2MVersion is not consistent with xml schema(xsi:noNamespaceSchemaLocation) in /models/503.xml : 1.1  expected but was 1.0.

Leshan says that `LWM2MVersion` must be updated but maybe in this case this is rather the `noNamespaceSchemaLocation` which should be adapted. 

```diff
-<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openmobilealliance.org/tech/profiles/LWM2M-v1_1.xsd">
+<LWM2M xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://openmobilealliance.org/tech/profiles/LWM2M.xsd">
```

**Comment by jaimejim** [comment]
There were few additions (CoreLink and UnsignedInt) on v1.1 (CoreLnk and unisgned Integer) but the types are not used on 502, 503, 504, 505 so you can just change the schema link to `LWM2M.xsd` and keep the version 1.0 IMO. 

<img width="663" alt="image" src="https://user-images.githubusercontent.com/1798358/167584600-8dc19fd7-f054-4494-9e44-ebbf9b067a10.png">

**Comment by sbernard31** [comment]
> There were few additions (CoreLink and UnsignedInt) on v1.1 (CoreLnk and unisgned Integer) but the types are not used on 502, 503, 504, 505 so you can just change the schema link to LWM2M.xsd and keep the version 1.0 IMO.

I agree with that. :+1: 
This is what I done on my side in Leshan but **I think this should be fixed in LWM2M registry** too.

Any opinion about this ?

**Comment by rkandoi** [comment]
Yes, the proposal to update the registry and improve the guidelines will (hopefully) be discussed in the DMSE WG today. Will provide an update and/or a fix after that.

**Comment by rkandoi** [comment]
@sbernard31 : First, it was agreed that the fix you applied with Leshan will also be applied in the lwm2m-registry (in the near future).

Second, to be sure about the issue itself, would like to confirm with you my hypothesis that the issue is actually a Leshan specific issue. In other words, the XML schema validation for mentioned objects should still pass with the 1.1 schema. But perhaps Leshan is doing some additional checks which causes model validation to fail (sorry have not had the time to look at the Leshan code itself).

**Comment by sbernard31** [comment]
> First, it was agreed that the fix you applied with Leshan will also be applied in the lwm2m-registry (in the near future).

Good to know :tada: 

> Second, to be sure about the issue itself, would like to confirm with you my hypothesis that the issue is actually a Leshan specific issue. In other words, the XML schema validation for mentioned objects should still pass with the 1.1 schema. But perhaps Leshan is doing some additional checks which causes model validation to fail (sorry have not had the time to look at the Leshan code itself).

If you're question is :   
Are those file valid from a "pure" xml point of view ? and so are they valid from the LWM2M-v1_1.xsd point of view ?  
Yes I think there are.

But I would not says this is a "Leshan specific issue".
Leshan checks that the xml file respects the xsd but also do some LWM2M specific checks
One of this check is to be sure that `<LWM2MVersion>` and schema are consistent. 
(Note that Leshan allow to use custom model validator but by default we try to be pretty strict)
