### ISSUE TITLE
Object Registration(Edge Application Server Information)

### ISSUE THREAD

**Issue by ezhaboy** [OpenMobileAlliance/lwm2m-registry#657]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | Ericsson
Object Name (as defined in the .xml file) |  Edge Application Server Information
Short Object description, to be used in the public registry (max 134 characteres) | This is used for UE to obtain information about suitable Edge Application Server in Edge Data Network, and to support service continuity for the UE to minimize service interruption.

**Comment by jpradocueva** [comment]
@ezhaboy Daniel, thanks for starting the registration process.

Please proceed to submit your PR with the new  object`10378.xml` against the root of the branch https://github.com/OpenMobileAlliance/lwm2m-registry/tree/ericsson_10378.  Also, using the same PR upload the content of the same object in a new file `10378-1_0.xml' but inside of the folder `version_history`  as indicated in the [README](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/prod#readme) file of this repo

Feel free to get in contact if you have any questions.

**Comment by jpradocueva** [comment]
@ezhaboy Daniel, what do you want us to do with the branch https://github.com/OpenMobileAlliance/lwm2m-registry/tree/ericsson_10378.? 
This branch is a placeholder for your Object ID 10378. I cannot be used by any other object. We can close it as this object is reserved to you or keep it open.

**Comment by ezhaboy** [comment]
> @ezhaboy Daniel, what do you want us to do with the branch https://github.com/OpenMobileAlliance/lwm2m-registry/tree/ericsson_10378.? This branch is a placeholder for your Object ID 10378. I cannot be used by any other object. We can close it as this object is reserved to you or keep it open.

Please help to close, sorry for inconvenience.
