### ISSUE TITLE
Guidelines for constructing Objects/RR enhancement review

### ISSUE THREAD

**Issue by seanmcilroy29** [OpenMobileAlliance/lwm2m-registry#67]
**R&A Review - From 2019-01-31 at 08:00 GMT to 2019-02-13 at 18:00 GMT**

Submission of comments to enhance the current Object/RR guidelines

- [ ] http://member.openmobilealliance.org/ftp/Public_documents/DM/Permanent_documents/OMA-ORG-Guidelines_Creation_Registration_LwM2M_Objects_Resources-V1_0_1-20190115-A.zip

**Comment by jpradocueva** [comment]
New guidelines have been created. Next step is to develop context sensitive help on line tools.
