### ISSUE TITLE
Object 10377(Data Monitoring): Wrong resource 13 Type

### ISSUE THREAD

**Issue by BTE164** [OpenMobileAlliance/lwm2m-registry#674]
As per its description, the resource is supposed to hold CBOR data and thus needs to be of type "Opaque" instead of "Integer".
```

<Item ID="13">
<Name>Monitoring Results</Name>
<Operations>RW</Operations>
<MultipleInstances>Single</MultipleInstances>
<Mandatory>Mandatory</Mandatory>
<Type>Integer</Type>
<RangeEnumeration></RangeEnumeration>
<Units></Units>
<Description><![CDATA[Monitoring Results resource is a serialised accumulation of comparison results of data and the references, represented by a read-only serialised Opaque (Binary).
This resource use CBOR format encoded as following: 
1. array(Result Index 1, Result Timestamp 1, Result Value 1)
2. array(Result Index 2, Result Timestamp 2, Result Value 2)
...
n. array(Result Index n, Result Timestamp n, Result Value n)	

Result value is an integer containing bit flags described as per following:
bit 0: 0(Comparison A statement is false), 1(Comparison A statement is true)
bit 1: 0(Comparison B statement is false), 1(Comparison B statement is true)
bit 2: 0(Comparison C statement is false), 1(Comparison C statement is true)
other bits: unused
New result will be added when there is a change of current Result Value. Result Timestamp is a 32-bit integer representing the number of seconds since Jan 1st, 1970 in the UTC time zone, sampled when the change occurs. Result Index is the running number of the recorded changes. 
Number of available results is up to device's implementation and maximum result that can be accumulated should be stated in Monitoring Description resource.
]]>
</Description>
</Item>
```

**Comment by mkgillmore** [comment]
@BTE164 Are you ok with this being a 1.0 patch to fix or do you want a 1.1 version to address this issue?

**Comment by BTE164** [comment]
@mkgillmore , i'm ok with it being a 1.0 patch.

**Comment by mkgillmore** [comment]
I’ve created a branch and pull request to address this issue.  Please see https://github.com/OpenMobileAlliance/lwm2m-registry/pull/678
If you are ok with the patch,  I’ll merge it into prod.  Please let me know.

Thanks

Matt

From: Muhammad Bin Ahmad ***@***.***>
Sent: Tuesday, June 14, 2022 11:22 AM
To: OpenMobileAlliance/lwm2m-registry ***@***.***>
Cc: Gillmore, Matthew ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL] Re: [OpenMobileAlliance/lwm2m-registry] Object 10377(Data Monitoring): Wrong resource 13 Type (Issue #674)


@mkgillmore<https://urldefense.com/v3/__https:/github.com/mkgillmore__;!!F7jv3iA!2xMOI0TAgb9lY2T50Nu-_Pc-3J55QYvuZDj21gHWYbRorl0I7ZX0do_Ot68tRnnbwRYDa4uxI_IVB1agHnRwBtGU1xEO_Q$> , i'm ok with it being a 1.0 patch.

**Comment by mkgillmore** [comment]
Group agrees to close this issue on 6/21/2022

**Comment by BTE164** [comment]
Hi Matt,

 

Sorry for the late reply, I’m ok with the patch. Thank you.

 

Regards,

Muhammad Bin Ahmad
