### ISSUE TITLE
GSMA ESipa object

### ISSUE THREAD

**Issue by david-bohaty-thalesgroup** [OpenMobileAlliance/lwm2m-registry#692]
### 1. Choose the type of registration: ###
  - [X] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [X] 3rd party Standards or Alliances
  - [ ] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [X] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1 object
Name of SDO, Company or individual    | GSMA
Object Name (as defined in the .xml file) |  ESipa
Short Object description, to be used in the public registry (max 134 characteres) | ESipa interface as described in GSMA SGP.32

**Comment by jpradocueva** [comment]
@david-bohaty-thalesgroup please submit your pull request:
- [ ] against this branch, `gsma_3443`, https://github.com/OpenMobileAlliance/lwm2m-registry/tree/gsma_3443 
- [ ] ObjectID: `3443`
- [ ] ObjectName: `ESipa`
- [ ] Description: It must match the description inside of the Object, "ESipa interface as described in GSMA SGP.32". If this description is not the same, please update the DDF.xml accordingly.

> Please refer to https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/README.md for instructions on how to create and submit a new Object.
> If you have any problem, please send us your questions to helpdes@omaorg.org.

**Comment by jpradocueva** [comment]
@david-bohaty-thalesgroup please submit your pull request as suggested above.

**Comment by david-bohaty-thalesgroup** [comment]
Hi,
will do, still waiting for the final "go" from GSMA WG7.

David
________________________________

**Comment by jpradocueva** [comment]
@david-bohaty-thalesgroup, thanks for the update. Take your time, I know how long the internal process can take. I have identified an issue with the reserved number ID 3443. Is it possible to change it if we have to? Or is that number now tidy up with other references? My email is jprado@omaorg.org if you want to have a direct chat.

**Comment by david-bohaty-thalesgroup** [comment]
Hello Joaquin,
the object id 3443 has been included in the GSMA SGP.32 specs. The specs have not been published yet, but it would require a Change Request with approval to change the id. So, it would be preferred to avoid the change (but in worst case, it is doable).

I tried to write to your email directly but I did not receive any response.

Best regards,
David


________________________________

**Comment by david-bohaty-thalesgroup** [comment]
Hi David,
I'm sorry for not getting back to you sooner.
I will pass on the information to the Working Group for them to review this issue and decide.
The group is meeting tomorrow, Tuesday, Feb 14th.
We will let you know the outcome of the discussion.
Regards
Joaquin

From: David Bohaty ***@***.***>
Date: Monday, February 13, 2023 at 7:14 AM
To: OpenMobileAlliance/lwm2m-registry ***@***.***>, Joaquin Prado ***@***.***>
Subject: Re: [OpenMobileAlliance/lwm2m-registry] GSMA ESipa object (Issue #692)
Hello Joaquin,
the object id 3443 has been included in the GSMA SGP.32 specs. The specs have not been published yet, but it would require a Change Request with approval to change the id. So, it would be preferred to avoid the change (but in worst case, it is doable).

I tried to write to your email directly but I did not receive any response.

Best regards,
David


________________________________

**Comment by jpradocueva** [comment]
@david-bohaty-thalesgroup I sent you an email but also providing there the same feedback.
There is a proposal - GSMA to keep ObjectID `3443` that needs to be confirmed by the group during the week.  
Also, we would like to suggest that GSMA should submit the object for pre-validation. We won't approve the Object until we receive your confirmation. The pre-validation will guarantee that the object is valid, well-formed, and pass all the tests listed on this page https://wiki.openmobilealliance.org/display/TOOL/Validation+Error+Code .
Please let me know if you have any questions.

**Comment by mkgillmore** [comment]
Closed with merging PR 700
