### ISSUE TITLE
Change of resource type and instance number confirmation

### ISSUE THREAD

**Issue by gmazzoleni** [OpenMobileAlliance/lwm2m-registry#702]
Dear community,

I am writing on behalf of the uCIFI alliance and would like to get a confirmation about the possibility to update a few resources in a uCIFI specific object (3416 - Outdoor Lamp Controller), where the data type would need to be changed from Integer to Float and from Single instance to Multi Instance.

By reading in https://www.openmobilealliance.org/documents/whitepapers/OMA-ORG-Guidelines_Creation_Registration_LwM2M_Objects_Resources-V1_0_1-20190115-A.pdf at section 5.3.1.2 it seems that such kind of modification could be allowed, given that the Object Version is properly increased

Could you please confirm that this kind of modifications are supported and allowed?

Many thanks and best regards,
Giulio Mazzoleni

**Comment by jpradocueva** [comment]
Hello @pdx048 Giulio, yes, it is possible to create a new revision of the Objects.
Please refer to https://www.md2html-tool.com/docs/OpenMobileAlliance/LwM2M/master/0abdbd4/TS_Core/OMA-TS-LightweightM2M_Core-V1_2_1-20221209-A_full.html#7-2-0-72-Object-Versioning Section 7.2.1 General Policy to see what should be the version of the new Object.  Based on your description of the changes, the new Object should be registered as v2.0.
Once you are ready to proceed, please let us know and we will create a specific branch for you to submit the PR.

**Comment by gmazzoleni** [comment]
Thank you very much @jpradocueva for the clarification and for pointing me to correct section of the documentation.
That is exactly what I was looking for.

We are still internally finalizing the changes and will create the PR for sure as soon as we will be ready.

Closing the topic
