### ISSUE TITLE
Location object 6 update (position RW + out of position alarm)

### ISSUE THREAD

**Issue by gmazzoleni** [OpenMobileAlliance/lwm2m-registry#703]
Dear community,

I am writing on behalf of the uCIFI Alliance and would like to get some feedbacks about the possibility of extending the Location object 6 by:

1. changing Latitude, Longitude and Altitude resources to read and write in order for the user to be able to manually store location information (e.g. for devices that are not equipped with GNSS modules)
2. adding an additional set of reaources related to expected position, distance threshold and alarm resource that the device may set when the current position is more distant than the configured threshold in respect to the expected postion (and clear when less distant)

Would such modifications be useful?

I do not know if the iter would be more complex, given that such object is part of the basic OMA objects included in the official documentation, but I have started to create a pull request that summarizes such modifications.
https://github.com/OpenMobileAlliance/lwm2m-registry/pull/701
(I still need to fix it in order to pass the validation process)

Many thanks and best regards,
Giulio Mazzoleni

**Comment by jpradocueva** [comment]
Hello @pdx048, Giulio, Object [6](http://devtoolkit.openmobilealliance.org/OEditor/LWMOView?url=https%3A%2F%2Fraw.githubusercontent.com%2FOpenMobileAlliance%2Flwm2m-registry%2Fprod%2F6.xml) is an Object created by OMA. The Object is updated and maintained in a private repository. Once the Object has been formally agreed by OMA, it is moved to the [OMNA LwM2M Registry](https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html) for publication. 

The changes you suggested in PR #701 will be reviewed and discussed by the OMA DMSE/IPSO Working Group, and you should receive an update via this issue or in the PR.

**Comment by gmazzoleni** [comment]
Thank you very much @jpradocueva for the clarification.
Closing this issue, then, to avoid confusion.
