### ISSUE TITLE
Calibrate Coefficient, Calibration Offset and Calibrate Offset resources

### ISSUE THREAD

**Issue by Mierunski** [OpenMobileAlliance/lwm2m-registry#706]
### 1. Choose the type of registration: ###
  - [ ] ```Object``` 
  - [x] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Reusable Resource(s)``` to register  | 3
Name of SDO, Company or individual    | AVSystem
Resource Name (as defined in the .xml file) |  1. Calibrate Coefficient<br/>2. Calibration Offset<br>3. Calibrate Offset
Short Object description, to be used in the public registry (max 134 characteres) | 1. Execute sensor calibration on device to recalculate Current Calibration resource value. <br/>2. Offset used by sensor. <br/>3. Execute sensor calibration on device to recalculate Current Offset resource value.

As many sensors have slope/coeficient and offset it would be nice to have resources that are responsible for their storage and recalibration. There is already resource 5821	Current Calibration, presented resources are addition to this.

[Reusable_Resources.zip](https://github.com/OpenMobileAlliance/lwm2m-registry/files/10993614/Reusable_Resources.zip)

**Comment by jpradocueva** [comment]
@Mierunski, we have created a new branch for you to submit the PR with the content for those Reusable Resources
https://github.com/OpenMobileAlliance/lwm2m-registry/tree/rr-AVSystem 

Please follow the guidelines in [README](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/README.md) for creating the PR to add these Reusable Resources.

**Comment by mkgillmore** [comment]
Resolved with PR710
