### ISSUE TITLE
What is meant by water meter, "Blocked Meter"

### ISSUE THREAD

**Issue by SimonPeacock** [OpenMobileAlliance/lwm2m-registry#708]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
I was reading the section on the Water meter object (urn:oma:lwm2m:ext:3424) but have been unable to get a suitable definition of what "Blocked Meter" means.
Does it mean there is an obstruction in the water meter/pipe?

Thanks
Simon

**Comment by mkgillmore** [comment]
@SimonPeacock This object was submitted by uCIFI.  I cannot speak for them... however I believe it means no water flow

**Comment by jpradocueva** [comment]
@SimonPeacock, Christophe ORCEAU from Kurrant was the person that registered these objects on behalf of uCIFI.

**Comment by mkgillmore** [comment]
Closed 4/11/2023
