### ISSUE TITLE
Presence Alarm Object Registration

### ISSUE THREAD

**Issue by soveryPC** [OpenMobileAlliance/lwm2m-registry#716]
## Registration Information ##

Create Version 1.0 of a new Object and create a new reusable resource.

### 1. Choose the type of registration: ###
  - [X] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [X] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [X] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register | 1 Object (10285)
Name of SDO, Company or individual | South East Water Corporation
Object Name (as defined in the .xml file) | Presence Alarm
Short Object description, to be used in the public registry (max 134 characters) | Where supported by the device this is an alarm that should be raised if the device detects presence above a pre-configured threshold.

[10285.zip](https://github.com/OpenMobileAlliance/lwm2m-registry/files/12234474/10285.zip)

Note that this object includes one newly proposed resource (6057 - Averaging Time Period) which has been submitted under issue #717

**Comment by gocadimic** [comment]
@soveryPC,
The DDF.xml file was updated with a new Object 10285 placeholder and customized as requested. Also, a placeholder for Reusable resource 6057 has been created in the `Common.xml` file.
All changes have been made to the new branch [sew-10285.](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/sew-10285). Submitting the new object and RR should be continued there.

For version 1.0 of Object 10285, a fully qualified Obj10285.xml file should be submitted to the given branch. Please make sure that the content of the DDF.xml and Common.xml files matches the request in PR #716 and PR #717.
Once the new Object will be submitted, the same Obj10285.xml file has to be submitted to the version_history folder, with the same content as in DDF.xml, named Obj10295-1_0.xml.

The final step would be creating a PR against `prod` branch. 

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by soveryPC** [comment]
Thank you for creating the associated branch. I have created the 10285.xml file and updated Common.xml file but I have been unable to push these files to the Github repository since I don't think I have push access rights?

$ git push origin sew-10285
remote: Permission to OpenMobileAlliance/lwm2m-registry.git denied to soveryPC.
fatal: unable to access 'https://github.com/OpenMobileAlliance/lwm2m-registry.git/': The requested URL returned error: 403

**Comment by jpradocueva** [comment]
@soveryPC, unfortunately, we don't provide push rights. You will need to fork the repository, and then you can create a PR against the upstream branch sew-10285. If you have any problem, please contact me via helpdesk@omaorg.org, and we can organize a Zoom call to resolve the issue. Thanks, and sorry for the inconvenience.

**Comment by soveryPC** [comment]
Repository has been forked. Branch updated and pull request created.
Please advise if any issues exist.

**Comment by jpradocueva** [comment]
The registration of this object is completed. The Issue can be closed.
