### ISSUE TITLE
Averaging Time Period Resource Registration

### ISSUE THREAD

**Issue by soveryPC** [OpenMobileAlliance/lwm2m-registry#717]
### 1. Choose the type of registration: ###
  - [ ] ```Object``` 
  - [X] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [X] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [X] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1 Reusable Resource (6057)
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) |  Averaging Time Period
Short Object description, to be used in the public registry (max 134 characters) | A value used to specify the time period over which data should be averaged. This value can be changed by doing a write command

			<Item ID="6057">
				<Name>Averaging Time Period</Name>
				<Operations>RW</Operations>
				<MultipleInstances>Multiple</MultipleInstances>
				<Mandatory>Optional</Mandatory>
				<Type>Float</Type>
				<RangeEnumeration>0.0..86400.0</RangeEnumeration>
				<Units>s</Units>
				<Description><![CDATA[A value used to specify the time period over which data should be averaged.This value can be changed by doing a write command]]></Description>
			</Item>

Note that this resource has been proposed due to the newly created object proposal "Presence Alarm" found in issue #716

**Comment by jpradocueva** [comment]
This Reusable Resource was registered. Closing the Issue.
