### ISSUE TITLE
M-Bus Meter Registration

### ISSUE THREAD

**Issue by antonpernisch** [OpenMobileAlliance/lwm2m-registry#718]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | CellQoS, a.s.
Object Name (as defined in the .xml file) |  M-Bus Meter
Short Object description, to be used in the public registry (max 134 characteres) | This LwM2M object is designed to provide a standardized representation of an M-Bus based meter within an IoT ecosystem.

**Comment by gocadimic** [comment]
@antonpernisch,
The DDF.xml file was updated with a new Object 10480  placeholder and customized as requested.
All changes have been made to the new branch [CellQoS-10480](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/CellQoS-10480). Submitting the new object should be continued there.

A fully qualified Obj-10480.xml file should be submitted to the given branch for version 1.0. Please make sure that the content of the DDF.xml matches the request in PR #[718](https://github.com/OpenMobileAlliance/lwm2m-registry/issues/718).

Once the new Object will be submitted, the same Obj 10480.xml file has to be submitted to the version_history folder, with the same content as in DDF.xml, named 10480-1_0.xml.
The final step would be creating a PR against the prod branch.

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by jpradocueva** [comment]
@antonpernisch, we are closing this Issue. If you are still interested in submitting the object please let us know.
