### ISSUE TITLE
New Object: Speed Test

### ISSUE THREAD

**Issue by FredRodermund** [OpenMobileAlliance/lwm2m-registry#721]
### 1. Choose the type of registration: ###
  - [X ] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [X ] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [ ] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | Vodafone
Object Name (as defined in the .xml file) |  Speed Test
Short Object description, to be used in the public registry (max 134 characters) | tbc

**Comment by gocadimic** [comment]
@FredRodermund,
The DDF.xml file was updated with a new Object 10481 placeholder and customized as requested.
All changes have been made to the new branch [vodafone-10481](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/vodafone-10481). Submitting the new object should be continued there.

A fully qualified Obj-10481.xml file should be submitted to the given branch for version 1.0. Please make sure that the content of the DDF.xml matches the request in PR #721.

Once the new Object will be submitted, the same Obj 10481.xml file has to be submitted to the version_history folder, with the same content as in DDF.xml, named 10481-1_0.xml.
The final step would be creating a PR against the prod branch.

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by jpradocueva** [comment]
This object has been registered. The Issue can be closed.
