### ISSUE TITLE
New Object : DYM IoT edge commands and data protocols

### ISSUE THREAD

**Issue by dymlabs** [OpenMobileAlliance/lwm2m-registry#731]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | DYM Labs (Debug Your Mind Labs LLP)
Object Name (as defined in the .xml file) |  DYM IoT edge commands and data protocols
Short Object description, to be used in the public registry (max 134 characteres) | This LWM2M object is used between DYM IoT Platform and Edge IoT Device Manager for control command and data exchange.

**Comment by gocadimic** [comment]
@dymlabs,

The DDF.xml file was updated with a new Object 10482 placeholder and customized as requested.
All changes have been made to the new branch [10482-DYN-Lab](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10482-DYN-Lab). Submitting the new object should be continued there.

A fully qualified Obj-10482.xml file should be submitted to the given branch for version 1.0. Please make sure that the content of the DDF.xml matches the request in https://github.com/OpenMobileAlliance/lwm2m-registry/issues/731.

Once the new Object is submitted, the same Obj 10482.xml file has to be submitted to the version_history folder, with the same content as in DDF.xml, named 10482-1_0.xml.
The final step would be creating a PR against the prod branch.

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by dymlabs** [comment]
Thanks  Gocadimic !!

However can you please rename the branch 104820-**DYN**-Lab to 104820-**DYM**-**Labs**.  I can understand this  is more related with code activity. It would be great if you can rename please.

Meanwhile we will follow your instructions and update DDF.xml, Obj-10482.xml for submission.

Regards,
Arch Lead - DYM IoT Group

**Comment by gocadimic** [comment]
@dymlabs,

The name of the new branch has been changed to [10482-DYM-Labs](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10482-DYM-Labs), as requested.

Please let us know if you need any further assistance.

**Comment by dymlabs** [comment]
Thanks a lot..

**Comment by dymlabs** [comment]
Hi @gocadimic,

Getting issue while push the change into branch (10482-DYM-Labs). Seems permission (403) is not granted.
Please check the logs below:
```
anayf@LAPTOP-2EH6JARI MINGW64 /e/Clients/DYM/IoTGW/Patent/LWM2M_Reg/10482-DYM-Labs/lwm2m-registry (10482-DYM-Labs)
$ git push https://github.com/OpenMobileAlliance/lwm2m-registry.git
remote: Permission to OpenMobileAlliance/lwm2m-registry.git denied to dymlabs.
fatal: unable to access 'https://github.com/OpenMobileAlliance/lwm2m-registry.git/': The requested URL returned error: 403
```

**Comment by gocadimic** [comment]
Hi @dymlabs,

Our policy is not to provide write access to our repository. Therefore, you are not permitted to push changes as you have experienced.

We recommend forking a repository in your private area.
If you want to work locally, you must clone, do the changes locally, and send them to your private repo, from where you can submit a PR. For more information, see [About forking](https://docs.github.com/en/get-started/quickstart/contributing-to-projects#about-forking).
Please make sure that you are using the branch  [10482-DYM-Labs](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/10482-DYM-Labs) created for your changes.

If you need any further assistance, don't hesitate to contact us.

**Comment by dymlabs** [comment]
Hi @gocadimic Thanks !!

We have created a fork and pushed the changes. Also raised a PR  [DYM IoT Edge commands and data protocols Objects v1.0](https://github.com/OpenMobileAlliance/lwm2m-registry/pull/733)

Kindly let us know for next step. Thanks !!

**Comment by jpradocueva** [comment]
This object has been registered, the PR can be closed.
