### ISSUE TITLE
URN for `Test` Range 

### ISSUE THREAD

**Issue by sbernard31** [OpenMobileAlliance/lwm2m-registry#737]
Recently, I see that there is a new [`Test` range of ID for object](https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html).

Category | Label | URN | Object ID range | Description 
-- | -- | -- | -- | -- 
Test |  n/a | n/a | 42769 - 42800  | Object IDs for testing purpose. These IDs MUST NOT be used in production as collisions with other object IDs are possible. 

There is no URN define, is it expected ? 

[This documentation](https://github.com/OpenMobileAlliance/lwm2m-registry/wiki/Guidelines#object-urn) say : 
> The composition of this element is: `urn:oma:lwm2m:<oma|ext|x>:<ObjectID>:<version>`

For implementation which valid model before to load it, this is unclear what should be done.

Could you clarify that please :pray:

**Comment by mkgillmore** [comment]
@sbernard31 the group DMSO agrees this should be in the "x" range.  Would you like further clarification in the https://github.com/OpenMobileAlliance/lwm2m-registry/wiki/Guidelines#object-urn documentation ?

**Comment by sbernard31** [comment]
I think  https://github.com/OpenMobileAlliance/lwm2m-registry/wiki/Guidelines#object-urn documentation is clear enough.

But IF `x` label should be used for **Test** category THEN I think that **Test**  row of **ObjectID Classes** table should be updated 

![image](https://github.com/OpenMobileAlliance/lwm2m-registry/assets/840294/deaa0edf-cdc8-4584-956a-4232df8a5c2f)

This table is available [here](https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html) by clicking on **Object Classes** Tab.

**Comment by sbernard31** [comment]
Probably with something like : 

Category | Label | URN | Object ID range | Description 
-- | -- | -- | -- | -- 
Test |  ~n/a~  <br/> **x** | ~n/a~  <br/> `urn:oma:lwm2m:x:<id>:<version>` | 42769 - 42800  | Object IDs for testing purpose. These IDs MUST NOT be used in production as collisions with other object IDs are possible.

**Comment by mkgillmore** [comment]
Group agrees to make the changes.  Appendix D needs to change along with the table used in the website

**Comment by jpradocueva** [comment]
Resolved in PR https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/pull/244

**Comment by mkgillmore** [comment]
@sbernard31 We believe this is resolved and will be made available on OMA's website and will appear in LwM2M 1.2.2 and later revisions
