### ISSUE TITLE
[ADMIN] Reserve bulk object for Grinn

### ISSUE THREAD

**Issue by gocadimic** [OpenMobileAlliance/lwm2m-registry#751]
Requested by Piotr L. Figlarek in https://helpdesk.openmobilealliance.org/browse/OPEN-8060  

### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [ ] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 50
Name of SDO, Company or individual    | Grinn sp. z.o.o
Object Name (as defined in the .xml file) |  <your text>
Short Object description, to be used in the public registry (max 134 characteres) | <your text>

**Comment by jpradocueva** [comment]
@gocadimic, is this the reservation that changed the name of the company? If the registration is completed, please close the issue.

**Comment by gocadimic** [comment]
@jpradocueva, this company initially asked for a bulk reservation on behalf of Watts A/S, but as it turned out, they also requested the same for themselves.

**Comment by gocadimic** [comment]
Resolved in [PR #217](https://github.com/OpenMobileAlliance/technical.openmobilealliance.org/pull/217).
