### ISSUE TITLE
Object 10284 error

### ISSUE THREAD

**Issue by SimonPeacock** [OpenMobileAlliance/lwm2m-registry#752]
Object 10284 seems to be a copy paste error.  the description doesn't match the name

Simon

**Comment by mkgillmore** [comment]
@SimonPeacock Which is correct, the name or the description of the name.  Typically the current name would be a resource in the object itself

**Comment by mkgillmore** [comment]
@SimonPeacock any updates?  If I do not hear back in two weeks,  this issue will be closed

**Comment by SimonPeacock** [comment]
I am guessing the name is correct, but the data included isn't.  Take a look at urn:oma:lwm2m:x:10283 which is reboot.

**Comment by workgreg** [comment]
Thanks for bringing this to my attention. Looks like the descriptions of 10283 and 10284 are incorrect. Following it up with a colleague now.

**Comment by workgreg** [comment]
| Object ID | Name | Description |
| ---------- | ------- | ------------ |
| 10282 | Daughter Board Failure Alarm | This binary status must indicate that the Meter MCU can no longer communicate with a daughter board |
| 10283 | Device Reboot Event | This event records the fact that the device has rebooted |
| 10284 | Time Synchronisation Alarm | This alarm records the fact that a significant (e.g. >5mins) time adjustment was required on the device |

**Comment by mkgillmore** [comment]
@workgreg was this addressed via PR with your table that you supplied in comments?

**Comment by workgreg** [comment]
Fixed here - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/768/commits/4cd8d231fa3c3944a698674f1add4d597245efb6

Then broken again here - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/768/commits/761a1c3678933934658c5a7b6dbc66b6cfcdc5b8 and here - https://github.com/OpenMobileAlliance/lwm2m-registry/pull/768/commits/f7ca98b7f4b3661d102e938362267a371725a16d !!!

**Comment by mkgillmore** [comment]
@jpradocueva @workgreg We (OMA) are looking into this

**Comment by jpradocueva** [comment]
This issue was addressed by PR #782
