### ISSUE TITLE
Object 10340 mismatch of type and description

### ISSUE THREAD

**Issue by akeranen** [OpenMobileAlliance/lwm2m-registry#755]
The Object 10340 seems to have some mismatch of types (boolean) and what is said in descriptions, e.g., in [Resource 2](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/b62ffc2c40c69f10d6e2f449441af84ba8aa48e2/10340.xml#L64) "Camera Status" description says "The status of the camera, 1:Enabled, 0:Disabled".  Should be "true: enabled, false:disabled".

Probably good to check all Objects for similar errors. I think I've seen this issue also before.

**Comment by jpradocueva** [comment]
@Kenny-SZ this issue reports a problem with one of the Objects registered by your company. Could you please investigate and let us know if you need any assistance? Thanks. Joaquin
