### ISSUE TITLE
Manhole level monitoring - object definitions.

### ISSUE THREAD

**Issue by workgreg** [OpenMobileAlliance/lwm2m-registry#761]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 7 new objects
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Water Level Readings
Short Object description, to be used in the public registry (max 134 characters) | Periodic water level measurements.
Object Name (as defined in the .xml file) | Tilt Readings
Short Object description, to be used in the public registry (max 134 characters) | Periodic tilt measurements.
Object Name (as defined in the .xml file) | Water Level Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the water level in a tank, manhole, etc. exceeds the specified threshold.
Object Name (as defined in the .xml file) | Trend Readings
Short Object description, to be used in the public registry (max 134 characters) | Periodic trend (rate of change) measurements.
Object Name (as defined in the .xml file) | Tilt Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the tilt/inclination of the device exceeds the specified threshold.
Object Name (as defined in the .xml file) | Trend Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the trend (rate of change) of a sensor input exceeds a specified threshold.
Object Name (as defined in the .xml file) | Manhole
Short Object description, to be used in the public registry (max 134 characters) | This object provides site commissioning configuration for devices operating in a sewer manhole.

**Comment by gocadimic** [comment]
@workgreg,

The DDF.xml file was updated with new Object 10487-10493 placeholders and customized as requested.
All changes have been made to the new branch [sew-reserve-placeholder](https://github.com/workgreg/lwm2m-registry/tree/sew-reserve-placeholder). Submitting the new object should be continued there.

A fully qualified Obj-10487.xml, Obj-10488.xml, Obj-10489.xml, Obj-10490.xml, Obj-10491.xml, Obj-10492.xml, Obj-10493.xml files should be submitted to the given branch for version 1.0. Please make sure that the content of the DDF.xml matches the request in https://github.com/OpenMobileAlliance/lwm2m-registry/issues/761.

Once the new objects are submitted, the same objects Obj-10487.xml....Obj-10493.xml files have to be submitted to the version_history folder, with the same content as in DDF.xml, named 10487-1_0.xml....10493-1_0.xm
The final step would be creating a PR against the prod branch.

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by mkgillmore** [comment]
@workgreg Do you intend to address issue #752 with this issue and PR?

**Comment by workgreg** [comment]
> @workgreg Do you intend to address issue #752 with this issue and PR?

Happy to address #752 in the PR for this issue.

**Comment by workgreg** [comment]
I've identified a requirement for one more object which I'd like to add as part of this issue.

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    |  South East Water Corporation
Object Name (as defined in the .xml file) | Fault Code 
Short Object description, to be used in the public registry (max 134 characters) | This object reports device specific fault codes

**Comment by mkgillmore** [comment]
ok,  let me know if you need any help

**Comment by workgreg** [comment]
> ok, let me know if you need any help

I've already sent a pull request for this issue. Should I create a new issue for the additional object? If not, will you reserve a placeholder object ID or should I choose an object ID?

**Comment by mkgillmore** [comment]
Your call if you would like to create a new issue.   It would be easier for me if you created an issue for the new object.

From: workgreg ***@***.***>
Sent: Thursday, June 27, 2024 8:28 PM
To: OpenMobileAlliance/lwm2m-registry ***@***.***>
Cc: Gillmore, Matthew ***@***.***>; Comment ***@***.***>
Subject: [EXTERNAL] Re: [OpenMobileAlliance/lwm2m-registry] Manhole level monitoring - object definitions. (Issue #761)

ok, let me know if you need any help I've already sent a pull request for this issue. Should I create a new issue for the additional object? If not, will you reserve a placeholder object ID or should I choose an object ID? —Reply to this
ZjQcmQRYFpfptBannerStart
Warning! This email comes from outside the company.
This message came from outside of Itron, if you suspect it to be spam, please delete it or if you suspect a phishing attempt, please report it using the Phish Alert Report button. Be careful and think before you click.
ZjQcmQRYFpfptBannerEnd

ok, let me know if you need any help

I've already sent a pull request for this issue. Should I create a new issue for the additional object? If not, will you reserve a placeholder object ID or should I choose an object ID?

**Comment by workgreg** [comment]
I've created a new issue - #770

**Comment by mkgillmore** [comment]
Addressed with PR #768
