### ISSUE TITLE
Sensor parameterisation object registration

### ISSUE THREAD

**Issue by walzsi** [OpenMobileAlliance/lwm2m-registry#765]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  |  3 new objects
Name of SDO, Company or individual    | autosen GmbH
Object Name (as defined in the .xml file) |  Periodic Sensor Sampler
Short Object description, to be used in the public registry (max 134 characteres) | The autosen Periodic Sensor Sampler object can be used to sample one or more sensor value(s) at periodic intervals.
Object Name (as defined in the .xml file) |  Periodic Sensor Upload
Short Object description, to be used in the public registry (max 134 characteres) | The autosen Periodic Sensor Upload object can be used to upload sampled sensor data at periodic intervals.
Object Name (as defined in the .xml file) |  Sensor Alarm
Short Object description, to be used in the public registry (max 134 characteres) | The autosen Sensor Alarm object can be used to set alarm conditions for sampled sensor data.

**Comment by gocadimic** [comment]
@walzsi,

The DDF.xml file was updated with new Object 10494-10496 placeholders and customized as requested.
All changes have been made to the new branch [autosen-reserve-placeholder](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/autosen-reserve-placeholder). Submitting the new object should be continued there.

A fully qualified Obj-10494.xml, Obj-10495.xml, and Obj-10496.xml files should be submitted to the given branch for version 1.0. Please make sure that the content of the DDF.xml matches the request in https://github.com/OpenMobileAlliance/lwm2m-registry/issues/765.

Once the new objects are submitted, the same objects Obj-10494.xml....Obj-10496.xml files have to be submitted to the version_history folder, with the same content as in DDF.xml, named 10494-1_0.xml....10496-1_0.xm
The final step would be creating a PR against the prod branch.

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by mkgillmore** [comment]
This was resolved and the group agrees to delete the issue
