### ISSUE TITLE
Manhole level monitoring - fault code object

### ISSUE THREAD

**Issue by workgreg** [OpenMobileAlliance/lwm2m-registry#770]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 1
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Fault Code
Short Object description, to be used in the public registry (max 134 characters) | This object reports device specific fault codes

**Comment by gocadimic** [comment]
@workgreg,

The DDF.xml file was updated with a new 10497 placeholder.

All changes have been made to the new branch [sew-obj-10497-placeholder](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/sew-obj-10497-placeholder). Submitting the new object should be continued there.

A fully qualified 10497.xml file should be submitted to the given branch for version 1.0. Please make sure that the content of the DDF.xml matches the request in [#770](https://github.com/OpenMobileAlliance/lwm2m-registry/issues/770).
Once the new Object is submitted, the 10497.xml file, with the same content as in DDF.xml, must be submitted to the version_history folder and named 10497-1_0.xml.

The final step would be creating a PR against the prod branch.

For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme).

**Comment by mkgillmore** [comment]
Issue resolved on 8/27/2024 re: PR#773
