### ISSUE TITLE
Bulk reservation for autosen

### ISSUE THREAD

**Issue by walzsi** [OpenMobileAlliance/lwm2m-registry#778]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 50
Name of SDO, Company or individual    | autosen
Object Name (as defined in the .xml file) | 
Short Object description, to be used in the public registry (max 134 characteres) |

**Comment by gocadimic** [comment]
Hello @walzsi,
Thank you for your request.
The bulk reservation of Object IDs 35800-35849 has been allocated to Autosen.
The Objects won’t be published in the OMA SpecWorks LwM2M Registry and will be kept private.
Please see[ OMNA web page.](https://technical.openmobilealliance.org/OMNA/LwM2M/LwM2MRegistry.html)
The process for registering any LwM2M Object is available in the README file of the GitHub repo:[ https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/README.md](https://github.com/OpenMobileAlliance/lwm2m-registry/blob/prod/README.md).
Please let us know if you have any further questions.
I believe that this issue can now be closed.
Thank you
