### ISSUE TITLE
Water tank monitor

### ISSUE THREAD

**Issue by workgreg** [OpenMobileAlliance/lwm2m-registry#781]
### 1. Choose the type of registration: ###
  - [x] ```Object``` 
  - [ ] ```Reusable Resource```
  
### 2. Choose the [Object Class](http://www.openmobilealliance.org/wp/OMNA/LwM2M/LwM2MRegistry.html#registry-table): ###
  - [ ] 3rd party Standards or Alliances
  - [x] Private companies
  - [ ] Private individuals (not allowed Reusable Resources registration)
  
## 3. Confirm Software License
  - [x] Tick this box confirming that your submission has included a [software license](http://devtoolkit.openmobilealliance.org/OEditor/License).
  
Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 5
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Discharge
Short Object description, to be used in the public registry (max 134 characters) | This LWM2M object provides water discharge events for a water tank monitoring device.
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Discharge Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the water level fails to change within a given period of time after a discharge event is started.
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Valve Alarm
Short Object description, to be used in the public registry (max 134 characters) | This alarm is raised when the valve state fails to change after a given period of time. This alarm only applies to valves with the status feedback feature.
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Discharge Status
Short Object description, to be used in the public registry (max 134 characters) | This event is recorded when a discharge event starts and stops.
Name of SDO, Company or individual    | South East Water Corporation
Object Name (as defined in the .xml file) | Water Tank
Short Object description, to be used in the public registry (max 134 characters) | This object provides site specific configuration for devices operating in a water tank.

**Comment by gocadimic** [comment]
Hello @workgreg  ,
As requested, we created a new branch [sew-10498-10502](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/sew-10498-10502), with the 5 placeholders for the objects reservation, IDs 10498-10502.
Your next step is to fork l[wm2m-registry](https://github.com/OpenMobileAlliance/lwm2m-registry) repository and, there prepare your objects contribution. Once it is ready, please raise a PR against the [sew-10498-10502](https://github.com/OpenMobileAlliance/lwm2m-registry/tree/sew-10498-10502) branch.
Once we see your PR, we will proceed with the validation.
Please let us know if you have any questions.
For more explanation, see [README.md](https://github.com/OpenMobileAlliance/lwm2m-registry#readme)

**Comment by mkgillmore** [comment]
Closed per 12/3/2024 DMSO meeting
