### ISSUE TITLE
OMA LwM2M Registry API returns XML documentation page instead of JSON metadata for object definitions

### ISSUE THREAD

**Issue by moise-iot** [OpenMobileAlliance/lwm2m-registry#785]
## Registration Information ##

When querying the [OMA LwM2M Registry API](https://wiki.openmobilealliance.org/display/TOOL/Registry+API) to retrieve the definition of an object, the response retrieve is the documentation xml page instead of the expected JSON file containing metadata information the Object. This issue occurs across the majority of API calls, even though the documentation specifies JSON as the expected response format

## Step to reproduce

1. Use the API endpoint (e.g., http://www.openmobilealliance.org/api/lwm2m/v1/Object?ObjectID=3) to retrieve an object's definition.

2. Observe that the response returns an XML path rather than JSON.

<img width="972" alt="image" src="https://github.com/user-attachments/assets/aa317212-a15b-40ab-857f-28049f49ccc5">
  
## Expected Behavior:
The API should return the object's metadata in JSON format, as outlined in the OMA documentation.

## Actual Behavior:
The API responds with an XML documentation page.

Concept            | Description
:----------------|:------------------------------
Number of ```Object(s)``` or ```Reusable Resource(s)``` to register  | 3
Name of SDO, Company or individual    | IoTerop
Object Name (as defined in the .xml file) |  Device
Short Object description, to be used in the public registry (max 134 characteres) | This LwM2M Object provides a range of device related information which can be queried by the LwM2M Server, and a device reboot and factory reset function

**Comment by jpradocueva** [comment]
@moise-iot thanks for raising this issue. We are working in some redirects and this one went wrong. We will address it soon.

**Comment by moise-iot** [comment]
thank you

**Comment by jpradocueva** [comment]
@moise-iot, this problem was resolved last night. It should be working ok. Otherwise, please email me at helpdesk@omaorg.org
