### ISSUE TITLE
[Golden maple data] Air_Temperature_Humidity - 10310	

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#79]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-03-11 06:16:53 UTC</td></tr><tr><td>Submitter's name</td><td>mintchest mintchest</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Golden maple data, co.ltd.</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Air_Temperature_Humidity	</td></tr><tr><td>Object Description</td><td>Sensor to detect air temperature and humidity</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=fbc6ccf3-b766-4bca-9d6a-02a173598aa8_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/fbc6ccf3-b766-4bca-9d6a-02a173598aa8_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=fbc6ccf3-b766-4bca-9d6a-02a173598aa8_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
@mintchest - Thankyou for your registration.
- The object ID allocation for this object will be reserved as 10310
- The object URN allocation for this object will be reserved as oma:lwm2m:x:10310

- A new branch has been created in the LwM2M registry for the WG to review your object - https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Golden-maple-data

- [ ] Please upload your object as a PR against this newly created Golden-maple-data branch to commence the validation and review process.

An observation 
- [ ] The legal disclaimer doesn't comply with any of the disclaimers suggested in the LwM2M Editor tool. We suggest to use one of the licenses provided in the tool, please DO NOT USE OMA license; this license is dedicated to OMA members only. https://devtoolkit.openmobilealliance.org/OEditor/License

**Comment by peaceblues** [comment]
Thanks, But I don't fully understand what's the next step, still use the editor to register the same object, or just submit .xml file of the object to github?

**Comment by jpradocueva** [comment]
@peaceblues if your object is 10310, then please submit a Pull Request with the content of your object agains the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Golden-maple-data.

The registration process is under review, in any case the current steps are:

1/ The first part is to submit the object using the tool, (what you have done already). 
2/ Then the staff evaluates if the Object is legit and validate it. We also point out a few areas that may need improve.
3/  In the next step, you need to submit a Pull Request with your object, please address the issues that have been mention above.
4/ The staff will make sure that the content of the PR validates correctly we will ensure that ObjectID and URN are correct.
5/ The IPSO Working Group will discuss your registration and may provide comments if they see any issue.
6/ In case there is an issue, you will need to update your Pull Request accordingly.
7/ The staff will validate again your updates to ensure that the object validates correctly.
8/ Once everything is ok, the Chair of the IPSO Working Group will merge your object
9/ The staff will publish the Object in the OMNA LwM2M Registry

Please let us know if you have any question.

**Comment by peaceblues** [comment]
For object and resource, both of them have multiple/single and mandatory/optional parameters, I don't fully understand, resource multiple/single means there's multiple/single resources in one object, while multiple/single object means there's multiple/single objects in one client, is that right?

Mandatory/optional of resource is easy to understand, while those of objects is very confused, could you please clarify these?

Thanks!

**Comment by peaceblues** [comment]
@jpradocueva thanks for your help, I've created PR for the object 10310, would you please review?

Besides that, I don't fully understand multiple/single and mandatory/optional of objects/resources.

Resource multiple/single means there're multiple/single resources in one object, while multiple/single object means there're multiple/single objects in one client, is that right?

Mandatory/optional of resource is easy to understand, while those of objects is very confused, could you please clarify these?

Thanks again!

**Comment by seanmcilroy29** [comment]
Appendix D. LwM2M Object Template and Guidelines Section D1 Object Template of http://openmobilealliance.org/release/LightweightM2M/V1_1-20180710-A/OMA-TS-LightweightM2M_Core-V1_1-20180710-A.pdf provides an overview of Object and Resource definitions.

**Comment by peaceblues** [comment]
@seanmcilroy29 thanks. I've updated .xml file, please review?

**Comment by seanmcilroy29** [comment]
@mintchest - Please note a number of comments have been submitted to your PR #82  
Please can you review and submit your comments asap so the Working Group can agree the object

**Comment by jpradocueva** [comment]
The PR #82 was closed due to lack of response from the submitter.
