### ISSUE TITLE
[Vaisala] Solar Radiation - 10311

### ISSUE THREAD

**Issue by github-oma** [OpenMobileAlliance/lwm2m-registry#85]
<!DOCTYPE html><html><head><meta charset="utf-8" /></head><body><table><tr><td>New OMNA registration request</td><td>2019-03-19 07:01:37 UTC</td></tr><tr><td>Submitter's name</td><td>Harri Hytönen</td></tr><tr><td>Defined By</td><td>Private company</td></tr><tr><td>Organization</td><td>Vaisala</td></tr><tr><td>Type of registration</td><td>Object</td></tr><tr><td>Object Name</td><td>Solar Radiation</td></tr><tr><td>Object Description</td><td>This object is used to report solar radiation flux density measured by a pyranometer or similar sensor.</td></tr><tr><td>Download Object</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/MODownloadZip?omna=100d736f-7f74-4c6e-aad8-fe941d9e9f78_Object.xml">Link to object (zip)</a></td></tr><tr><td></td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/OMNA/100d736f-7f74-4c6e-aad8-fe941d9e9f78_Object.xml">Link to object</a></td></tr><tr><td>Load the object into the tool</td><td><a href="https://devtoolkit.openmobilealliance.org/OEditor/LWMOView?omna=100d736f-7f74-4c6e-aad8-fe941d9e9f78_Object.xml">Load Editor with object</a></td></tr>

**Comment by seanmcilroy29** [comment]
@Harri - Thankyou for your registration.

- The object ID allocation for this object will be reserved as 10311
- The object URN allocation for this object will be reserved as oma:lwm2m❌10311

A new branch Vaisala has been created in the LwM2M registry for the WG to review your object 
- [ ]  please submit a Pull Request with the content of your object against the branch: https://github.com/OpenMobileAlliance/lwm2m-registry/tree/Vaisala 

Observations to be addressed;
- [ ] Update Object ID to 10311
- [ ] Add LwM2M version
- [ ] Add Object version
- [ ] Update Object urn to urn:oma:lwm2m:x:10311
- [ ] Remove spaces between ```<Units> </Units>``` [All resources]
- [ ] Remove space in ```<Type> </Type>``` for resource 5605
- [ ] Remove space in ```<RangeEnumeration> </RangeEnumeration>``` 5518
- [ ] All the descriptions need to be reviewed as they differ from the registry i.e. resource 5601
```<Description>The minimum value measured by the sensor since power ON or reset</Description>```
Should be 
```<Description>The minimum value measured by the sensor since it is ON or Reset, expressed in the unit defined by the "Sensor Units" resource if present.</Description>```

Outline of steps

Steps | Actions
-- | --
1 | Submit object using the tool
2 | Staff evaluates Object. Comments added for submitter to resolve
3 | Submitter submits a Pull Request to the nominated branch with your object
4 | Staff validates PR 
5 | IPSO Working Group discuss the submitted Object registration
6 | Any issues will require the submitter to update the PR accordingly
7 | Staff validates object again after submitters updates
8 | IPSO Working Group Chair will merge the object
9 | Staff publish the Object to the OMNA LwM2M Registry

**Comment by Harri** [comment]
Hi,

You got wrong Harri tagged in there :) https://github.com/Harri is me, Harri Paavola. Harri Hytönen is someone else.

**Comment by dirtyha** [comment]
@seanmcilroy29 , can you check that I have rights to push changes?

**Comment by jpradocueva** [comment]
@dirtyha in order to submit your PR you will need to fork the repository into your personal account and then send the PR agains the [Vaisala] branch. Unfortunately, we don't grant write access to external users.

**Comment by jpradocueva** [comment]
See PR #123
